### ISSUE TITLE
CodeQL (CLI) setup configuration inside Linux docker container

### ISSUE THREAD

**Issue by FaiqueAli** [github/codeql#10383]
**CodeQL setup inside Linux docker container**

Hi guys,  

I have followed the installation process for the codeql cli `(https://docs.github.com/en/code-security/code-scanning/using-codeql-code-scanning-with-your-existing-ci-system/installing-codeql-cli-in-your-ci-system#setting-up-the-codeql-cli-in-your-ci-system) `inside the Linux(ubuntu:18.04) docker container.
I download the codeql bundle using this ('https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-linux64.tar.gz') [link](https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-linux64.tar.gz).
I extracted the .tar file but when I verify my setup using the command `/home/codeql# codeql resolve qlpacks` it says
`bash: codeql: command not found`

can anyone suggest to me what I am doing wrong?
Many thanks :)

**Comment by jketema** [comment]
Thanks for your question.

Before running `codeql` did you update your path as the documentation you linked to explains you need to do: "After you extract the CodeQL CLI bundle, you can run the `codeql` executable on the server: ... By adding `/<extraction-root>/codeql` to your `PATH,` so that you can run the executable as just `codeql`"? Without this Linux will not be able to located the `codeql` binary.

Note that alternatively you can specify the full path the `codeql` as the documentation also mentions: "By executing `/<extraction-root>/codeql/codeql`, where `<extraction-root>` is the folder where you extracted the CodeQL CLI bundle."

**Comment by FaiqueAli** [comment]
Thank you very much for your reply,
I managed to generate database using the full path `/home/codeql/codeql`.
could you please let me know how can I setup path/env variable in Ubuntu I am very new to this OS.
Thanks :)

**Comment by jketema** [comment]
> could you please let me know how can I setup path/env variable in Ubuntu I am very new to this OS.

It's probably best to search the internet for this, as this is not CodeQL specific and also depends on the shell you're using.

**Comment by FaiqueAli** [comment]
Thank you :)

**Comment by aibaars** [comment]
@FaiqueAli Note that you can also use `./codeql` when your are in the same directory as where `codeql` is installed. One difference between Windows and OSX/Linux is that Windows looks in the current working directory and the `PATH` variable to resolve a command, while OSX/Linux only look in the `PATH`.
