### ISSUE TITLE
Successfully created database, but cannot find the file 'functions.rel' in the directory 'db-cpp/default'.

### ISSUE THREAD

**Issue by hyperlyz** [github/codeql#10770]
When I executed "codeql database create db --language=cpp --command="cmds.sh --overwrite", but don't find functions in the database.

**Comment by hyperlyz** [comment]
cmds.sh is

**Comment by jketema** [comment]
Hi @hyperlyz I see you almost immediately closed this issue. Does this mean you managed to resolve the issue already?

**Comment by hyperlyz** [comment]
cmds.sh is
![1665490201206](https://user-images.githubusercontent.com/20871123/195086010-5b855ac5-a77e-4f67-9223-548556164378.jpg)
![image](https://user-images.githubusercontent.com/20871123/195086173-dc278787-55c8-4462-9700-496844df4b71.png)

My log is 
[build-tracer.log](https://github.com/github/codeql/files/9754973/build-tracer.log)

**Comment by jketema** [comment]
Thanks for the additional info. You seem to be running a CodeQL version that is a few months old by now. To start, would it be possible for you to update to a more recent version of CodeQL and try again? Many of the issues I'm seeing in `build-tracer.log` should be fixed in recent versions. I'm not sure if that will completely resolve your issue, but it will make it easier for us to diagnose it.

**Comment by hyperlyz** [comment]
> Thanks for the additional info. You seem to be running a CodeQL version that is a few months old by now. To start, would it be possible for you to update to a more recent version of CodeQL and try again? Many of the issues I'm seeing in `build-tracer.log` should be fixed in recent versions. I'm not sure if that will completely resolve your issue, but it will make it easier for us to diagnose it.

thanks, i have solved it after update codeql.
