### ISSUE TITLE
False positive - Uncontrolled data used in path expression

### ISSUE THREAD

**Issue by nbauma109** [github/codeql#10948]
I remember fixing this issue after alert was raised by codeql v1.

https://github.com/nbauma109/jd-gui-duo/commit/520074bbe5885b6d834786103d79a8cfab267eab#diff-2c6badc6debfeb602f5f3d326bcb57d5dc9d7b482895a1469c45a62d52a9e284R86-R91

But with codeql v2 the alert was raised again. Or something more needs to be fixed ?
Removing file separators from path is non-negociable, though.

**Comment by hmakholm** [comment]
Can you point to the actual alert you're getting?

Just looking at the code, at least I'd say you'll probably also want to reject _absolute_ paths as part of this filtering.

**Comment by nbauma109** [comment]
![IMG_20221024_215623](https://user-images.githubusercontent.com/9403560/197616367-3ce9ea6c-66f3-4310-9433-eb027dccd7b4.jpg)

It's a desktop application. I need to be able to load files from anywhere, the paths will always be absolute, they're not relative to some location.

**Comment by hmakholm** [comment]
Hmm, it turns out the query that computes this alert was updated in release 2.11.1 of CodeQL. This involved a rewriting of how it identifies sanititizers, which is probably why you're now getting an alert due to the possibility of an absolute path slipping through.

It's not easy for an automated analysis to quantify _how_ user-controlled an input is. Immediately I'd say it's right to flag this up for human attention -- it's enough on the fence that it could easily be something one would want to fix. If, based on your knowledge of the code base and its intended application, you are sure that a user who can control this input would _already_ be in a position to do bad things, the most appropriate course of action might be for you to dismiss the alert. (And in that case, there's probably not much point in filtering out `..` either).

Thanks for the report, though.
