### ISSUE TITLE
Which edges are automatically added by taint analysis?

### ISSUE THREAD

**Issue by chennbnbnb** [github/codeql#11360]
I found CodeQL will automatically add edge sometimes, 
for example: suppose ``buffer`` is tainted, and codeql will find this flow correctly
```java
        Set<byte[]> set = new HashSet<>();
        set.add(buffer);

        for (byte[] buf : set) {
            ObjectInputStream ois = new ObjectInputStream(new ByteArrayInputStream(buf));
            ois.readObject();
        }
```

but when I do this [code QL CTF](https://securitylab.github.com/ctf/codeql-and-chill/), I found this necessary to add some edge manually. 
for example: ``map.keySet()``, suppose ``map`` contains tainted data, I need to add edge ``map=>map.keySet()``

so I want to figure out which edges are automatically added by taint analysis?

**Comment by MathiasVP** [comment]
Hi @chennbnbnb,

Dataflow/taintflow edges can be added in quite a few places:
- The most basic kinds of dataflow/taintflow steps are the defined deep inside the dataflow library. For Java, you can see some of those [here](https://github.com/github/codeql/blob/main/java/ql/lib/semmle/code/java/dataflow/internal/DataFlowUtil.qll#L138).
- Additionally, we add a lot of dataflow/taintflow edges as part of modeling common libraries. For example, many files in https://github.com/github/codeql/tree/main/java/ql/lib/semmle/code/java/frameworks are about adding additional edges to all dataflow/taintflow configurations.
- Sometimes, however, a dataflow/taintflow edge isn't appropriate for _all_ dataflow/taintflow analysis problems (for instance, because it adds spurious flow that is not appropriate in all cases). In such cases, you can augment your specific dataflow/taintflow analysis with additional edges via the `DataFlow::Configuration`'s `isAdditionalFlowStep` (or `TaintTracking::Configuration`'s `isAdditionalTaintStep`).

Does that answer help?

**Comment by chennbnbnb** [comment]
it helps me a lot, thanks

**Comment by chennbnbnb** [comment]
it helps me a lot, thanks
