### ISSUE TITLE
Java: No code seen during build for discord.jv

### ISSUE THREAD

**Issue by seailz** [github/codeql#11464]
**Description of the issue**

Getting a  ` Error: No code found during the build. Please see:` error even when there is clearly code in the repo.https://github.com/discord-jv/discord.jv/actions/runs/3568478501/jobs/5997392461

Maven - Java

**Comment by smowton** [comment]
It looks like the problem is that commit's `pom.xml` specifies `<packaging>pom</packaging>`, whereas I note current `main` does not. As such a `mvn package` at that commit doesn't build any Java, whereas one on `main` does. CodeQL determines what code is relevant to your project by following along with the build process, and therefore with `<packaging>pom</packaging>` we don't see any code to extract.

I suggest either removing the `<packaging>pom</packaging>` line as done on `main`, or else replace the `autobuild` step with a manual build step that compiles the Java files you want to analyse. This could be a particular `mvn` command that runs the relevant compilation, or even a hand-rolled `javac` invocation, so long as it somehow results in compilation of your code.
