### ISSUE TITLE
[Question] CodeQL analysis consuming more memory than --ram parameter

### ISSUE THREAD

**Issue by chmodxxx** [github/codeql#11676]
Hello,

We are currently running analysis on CI , the command we using `codeql database analyze ..   --ram "7000"`  under Large container (4 CPU 8GB RAM), unfortunately CI is exiting in analysis part with the code 137 which suggest OOM issue. Not sure how codeQL didn't respect the --ram parameter and tried to use more resources than that value.

Was wondering if this is already tracked/known or I misunderstood something regarding the --ram parameter. 

Thanks

**Comment by MathiasVP** [comment]
Hi @chmodxxx,

Thanks for your issue! We normally advice that you leave some memory for system processes, and it sounds like 1GB isn't sufficient in this case. Could you try running with `--ram 6500` or `--ram 6000` and see if that succeeds?

**Comment by chmodxxx** [comment]
Will give that a go and see if it works, thanks.

**Comment by chmodxxx** [comment]
@MathiasVP  unfortunately that didn't fully work, some repos are not ooming anymore but some other repos are still ooming, I think resources bump is the only work around left right ?

**Comment by MathiasVP** [comment]
I'm glad it worked for some of your repositories 🎉!

It may be that you need a bigger runner for the remaining repositories, but to diagnose whether this is the case (or whether there is some other performance problem) would you mind rerunning some of the OOM'ing runs with debugging enabled and uploading the log to this issue?

Running with debugging enabled saves the database as an artefict, so if you're comfortable sharing this with us we can also see if we can reproduce your OOM'ing issues so that we can improve the analysis.

For information on how to enable debugging, please see [this](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging) page.
