### ISSUE TITLE
JavaAnalyze fails while uploading large sarif files

### ISSUE THREAD

**Issue by suprithIUB** [github/codeql#11865]
Log snippet below

```Cleaning up databases
Uploading results
  Processing sarif files: ["/home/runner/work/hadoop/results/java.sarif"]
  Error: Cannot create a string longer than 0x1fffffe8 characters```

<!-- JavaAnalyze fails while uploading large sarif files  -->

**Comment by tausbn** [comment]
Thank you for your question! 

I think this is the same issue seen in #8712 and #8764. Most likely this is caused by too many alerts having large dataflow paths attached to them, which can lead to the sarif file exceeding 512MB in size (which is more than the Code Scanning API allows). 

You could try reducing the number of paths as detailed at the end of this comment: https://github.com/github/codeql/issues/8712#issuecomment-1095221359

**Comment by suprithIUB** [comment]
Thank you @tausbn it worked.
