### ISSUE TITLE
A missing import statement in the document

### ISSUE THREAD

**Issue by doriscullen** [github/codeql#12274]
In the document "CodeQL language guides"-"CodeQL for C and C++"-"Detecting a potential buffer overflow", I suppose that `import semmle.code.cpp.controlflow.SSA` should be added in the code snippet "the query in full".

![image](https://user-images.githubusercontent.com/61410303/220569812-f11a1805-f1a9-47e2-8dba-3fcbe1424cbb.png)

The doc link is https://codeql.github.com/docs/codeql-language-guides/detecting-a-potential-buffer-overflow/#extending-the-query-to-include-allocations-passed-via-a-variable

**Comment by jketema** [comment]
Hi @doriscullen, Thanks for your report. The example works without the import you suggest, because the SSA library is transitively imported through `cpp`. It is a bit sloppy though, given that all other examples on the page do import the library explicitly. I'll have a look to see if this can be made more uniform.

**Comment by jketema** [comment]
https://github.com/github/codeql/pull/12275
