### ISSUE TITLE
cpp/inconsistent-null-check: Possible False positive

### ISSUE THREAD

**Issue by ryao** [github/codeql#12492]
**Description of the false positive**

https://github.com/ryao/zfs/security/code-scanning/494

CodeQL's cpp/inconsistent-null-check says `The result of this call to avl_find is not checked for null, but 82% of calls to avl_find check for null.` for this code:

```
	dle = avl_find(&dl->dl_tree, &dle_tofind, NULL);
	VERIFY3P(dle, !=, NULL);
```

There is an assertion to ensure that dle is not NULL. However, this code is built both in userspace and in the kernel.

In the kernel, `VERIFY3P()` is defined here:

https://github.com/ryao/zfs/blob/67a1b0379159c46bcd60a462a2790248046c8804/include/os/linux/spl/sys/debug.h#L122-L131

In userspace, `VERIFY3P()` is defined here:

https://github.com/ryao/zfs/blob/67a1b0379159c46bcd60a462a2790248046c8804/lib/libspl/include/assert.h#L104-L112

If CodeQL is complaining about the kernel version, this is a false positive. If CodeQL is complaining about the userspace version, it probably is not a false positive, because the userspace code has a feature that permits assertions to be disabled at runtime for the ZFS debugger:

https://github.com/ryao/zfs/blob/67a1b0379159c46bcd60a462a2790248046c8804/lib/libspl/include/assert.h#L43-L47

There is detection in the CPP for both Clang's static analyzer and Coverity so that they are given versions that have the ability to turn off assertions at run time disabled at the source level, but there is none for CodeQL. If the issue is just that the detection is not in place for CodeQL, I am not sure how to address this. If there were a macro or a way to get the autobuilder to pass -DCODEQL to the c preprocessor, then it would be easy to set noreturn based on that so that the assertion is properly annotated for CodeQL to understand it.

**Comment by redsun82** [comment]
Hi @ryao, thanks for this question.

CodeQL will analyse whatever is built by the default steps (in your case that means `./autogen.sh`, then `./configure`, then `make`). So whether it's analysing the build for the kernel, for userspace or for both depends on what gets built by default. In case it is building both, CodeQL C/C++ analysis has a mechanism to distinguish elements in the DB depending on the final link targets, so both kernel and userspace entities should coexist in the DB without ambiguity.

About your question of injecting a define (`-DCODEQL`, or why not even faking `-D__clang_analyzer__`), probably the best way would be to drive that with an environment variable. I did test however that setting and exporting `CFLAGS` seems to not have any effect on the build of zfs. If it were the case, one could set it in `GITHUB_ENV` in the action just like it is already done for `MAKEFLAGS`.

Finally, be aware that a certain amount of false positives for a `@precision medium` query is to be expected, and due to our current focus on security queries raising the precision of this query will not probably happen any time soon.

I hope this is helpful!

**Comment by ryao** [comment]
Thanks. Unfortunately, I will not have time to pursue this further for a couple weeks as I will be traveling, but I will look into this more deeply after I return. In the interim, I see no reason to keep this open, so I am closing it.
