### ISSUE TITLE
False positive: CWE-78 OS Command Injection

### ISSUE THREAD

**Issue by LostBenjamin** [github/codeql#12753]
[This query](https://github.com/github/codeql/blob/944ca4a0da5b206fbdaf2958da0c65853dda5eb4/python/ql/src/Security/CWE-078/CommandInjection.ql) produces different results for the two semantically equivalent programs below:

CodeQL reports this as a bug:
```
from flask import Flask, request
import subprocess

app = Flask(__name__)

@app.route("/ls")
def ls():
    dirname = request.args.get('dirname')
    ls_cmd = ["ls", dirname]
    ls_out = subprocess.check_output(ls_cmd, shell=True)
    return ls_out
```

CodeQL does not report this as a bug:
```
from flask import Flask, request
import subprocess

app = Flask(__name__)

@app.route("/ls")
def ls():
    dirname = request.args.get('dirname')
    ls_out = subprocess.check_output(["ls", dirname], shell=True)
    return ls_out
```

The first program seems a false positive. Why does this happen?

**Comment by RasmusWL** [comment]
Hi @LostBenjamin. Note that your code does not do what you intend, since you're using BOTH `shell=True` and passing a list of arguments.

Quoting from [the documentation](https://docs.python.org/3.10/library/subprocess.html#subprocess.Popen):

> On POSIX with shell=True, the shell defaults to /bin/sh. (...) If args is a sequence, the first item specifies the command string, and any additional items will be treated as additional arguments to the shell itself. That is to say, [Popen](https://devdocs.io/python~3.10/library/subprocess#subprocess.Popen) does the equivalent of:
> 
> Popen(['/bin/sh', '-c', args[0], args[1], ...])

So you should probably rewrite this to be

```
subprocess.check_output(["ls", dirname])
```

### Difference in behavior

Overall, this query tries to only flag when a user can control which executable is used, not what arguments are passed to it. So in the case of `subprocess.check_output(["ls", dirname])` we recognize the list-literal, and only care if the user could control the first element (`"ls"`) which is not the case... so no alert.

I completely agree that the first case should be handled in the same way, such that this is a false positive. The reason it's treated differently, is that we currently taint the entire list when it contains a tainted element. We've been discussing how we can drop this behavior, but it'll take a bit of work to achieve.

We've also discussed writing a new query to alert when a user can control the argument to an executable (as in your case), but don't think it has quite the same severity as being able to control the entire command.
