### ISSUE TITLE
Improve handling for mismatching placeholders in query message

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#13061]
### Version
CodeQL extension version: 1.8.4 
CodeQL CLI version: 2.13.1 
Platform: win32 x64

### Description
Preliminary remarks: This issue might be a combination of missing diagnostics from the CodeQL CLI and the handling in the VS Code extension. If you think this rather belongs to https://github.com/github/vscode-codeql, feel free to move this issue there.

----

When there is a mismatch for placeholders in the query message the current behavior of CodeQL CLI respectively the VS Code extension is not ideal. Take for example this query:

```ql
/**
 * @kind problem
 */

import java

from Class c, Method m
where
  m.getDeclaringType() = c
select c, "and $@"
```

The query message here is malformed because it specifies one placeholder (`$@`) but does not provide a value for it. Currently this only leads to warnings similar to the following in the console:
```
[WARN] bqrs interpret> While processing rule dummy-id, got too few placeholders, expected 1 got 0, tuple [new Runnable(...) { ... }, and $@].
```

However, it:
- Does not show any warnings in the VS Code editor
- Does not show any results (~~neither for local query runs~~ nor for variant analysis; edit: looks like for query runs against a local database it shows them as "raw results")

And you might overlook that warning in the console, especially for VS Code.

### Desired solution
If possible it would be great if a warning (or even error) for such malformed hardcoded query messages could be shown in VS Code (and be emitted by CodeQL CLI during compilation).

Additionally, even though the message is malformed it should still produce results in my opinion. A potentially incorrect message is in my opinion way less severe than a missing result. Especially considering that this issue also occurs when the query message is dynamically created and happens to include `$@` by accident.

**Comment by aibaars** [comment]
Thanks for your detailed report. I'll ask the team to have a look.

**Comment by jbj** [comment]
I talked to the team about this, and the sentiment was that this is doable and doesn't break any abstraction barriers. We can extend the metadata verifier that's used in the language server to check the placeholders in all `@kind problem` queries with a constant query message.

In internal discussion, an extension was also proposed (and got three +1's):
> It would also be nice to have a check for `path-problem` queries, i.e., that the correct number of columns are selected and that the `edges` and `nodes` predicates (exist and) have matching types

Let's discuss this on Monday.

**Comment by Marcono1234** [comment]
Thanks!

Will this only be about detecting this problem at query compilation time, or is this also about displaying these query results nonetheless, even if their message might be a bit incorrect?

Because as mentioned in the description, for the case where the query message is created dynamically and might end up containing `$@` by accident (e.g. if it occurs in a string literal in the queried code), I guess this cannot be caught during compilation.
Consider this (contrived) example:
```codeql
/**
 * @kind problem
 */

import java

from Class c, string message
// Let's assume the `$@` in the message actually comes from the queried code,
// e.g. content of a string literal
where message = "custom message $@"
select c, message
```

In that case the VS Code extension shows for a query run against a local database "No Alerts. See raw results.". At least the raw results include the results though. 
But for Variant Analysis no results at shown at all (if you want I can report that at https://github.com/github/vscode-codeql though).

**Comment by kaspersv** [comment]
Thanks for the bug report. We have added additional static checks for extra placeholders in alert messages and changed the dynamic behaviour to treat extra placeholders as text. Both improvements are scheduled for release with v. 2.14.0 of the CodeQL CLI, which is expected to be released within a few weeks. 

With the change in dynamic behaviour, results with extra placeholders will should up both under the "alerts" and "#select" tab in VS Code. For instance, running your initial motivating example on an OpenJDK database yields:

![image](https://github.com/github/codeql/assets/4310256/5e72de26-618e-4c63-a270-422b90b75df5)
![image](https://github.com/github/codeql/assets/4310256/73a200e4-6ac0-468c-b206-71b29a5e0da8)

You also mention cases where the alert message is created dynamically with elements from the analysed code. In cases where those elements could contain placeholders (`$@`), the recommended why to use them in alert messages is by inserting them using a placeholder instead of appending them directly to the alert message. For instance, imagine an analysis that finds complex expressions that always evaluate to false. If we use the following select:
```
select ..., "The complex expression '" + e.toString() + "' always evaluates to false in $@.", ..., ...
```
then an expression such as `"$@" == "@$"` would inject an additional placeholder and break the alert message interpretation. Instead, we can use
```
select ..., "The complex expression '$@' always evaluates to false in $@.", e, e.toString(), ..., ...
```
to ensure the `$@` in `"$@" == "@$"` is not interpreted as a placeholder in the alert message.

**Comment by kaspersv** [comment]
I am closing this issue as completed. Feel free to reopen or file a new issue if you feel the issue has not been sufficiently addressed.
