### ISSUE TITLE
Kind error in /go/ql/src/Security/CWE-020/ExternalAPIsUsedWithUntrustedData.ql

### ISSUE THREAD

**Issue by y0utiao** [github/codeql#13171]
Error Message:
``` 
Interpreting /usr/share/codeql_home/codeql_repo/go/ql/src/Security/CWE-601/OpenUrlRedirect.ql...
Interpreting /usr/share/codeql_home/codeql_repo/go/ql/src/Security/CWE-601/BadRedirectCheck.ql...
Interpreting /usr/share/codeql_home/codeql_repo/go/ql/src/Security/CWE-020/ExternalAPIsUsedWithUntrustedData.ql...
A fatal error occurred: Could not process query metadata for /usr/share/codeql_home/codeql_repo/go/ql/src/Security/CWE-020/ExternalAPIsUsedWithUntrustedData.ql.
Error was: Unknown kind "Table". [UNSUPPORTED_KIND]
```

The metadata @kind should be [problem | path-problem]， why [table] in this ql?

**Comment by MathiasVP** [comment]
Hi @y0utiao,

The queries that we run as part of Code Scanning all have kind `problem` or `path-problem`, but there are many other kinds that we use for internal things (and since all of this is open source you can also run them yourself!). I'm not sure these are all documented somewhere, but you really shouldn't need to know about them 😄.

The kind `table` is just saying specifying that the output of the query shouldn't be interpreted as a normal query result like in Code Scanning. Instead, it's just a tabular output.

This query is useful if you want to quickly do a manual review the "interesting" parts of a codebase (for instance, if you're a security researcher looking for projects with potential vulnerabilities). Thus, it's not intended to be run as part of any of our security suites.

**Comment by y0utiao** [comment]
Understood， Thank you for your answer.
