### ISSUE TITLE
Go: RangeStmt declaring variables with := does not contain a DefineStmt

### ISSUE THREAD

**Issue by JasperSurmont** [github/codeql#13241]
**Description of the issue**

Not sure if this is an oversight or intended, but the following does not contain a `DefineStmt`:
```go
var arr []int = {0,1}

for i := range arr {
   ...
}
``` 
If intended, what is the reasoning behind this?

**Comment by jketema** [comment]
Thanks for your question. I've asked the CodeQL Go team whether they can provide more insight into this.

**Comment by mbg** [comment]
Hi @JasperSurmont, thank you for the question about this! I am on the CodeQL Go team and can confirm that this is intentional. The reasoning for it relates to the Go language specification, which our AST types like `DefineStmt` are modelled after. 

Go distinguishes between [Short Variable Declarations](https://go.dev/ref/spec#Short_variable_declarations) (which `DefineStmt` corresponds to) and For statements with [Range Clauses](https://go.dev/ref/spec#For_range) (which you have in your example and which are modelled by `RangeStmt`). Since Go makes this distinction, so do we at the AST level. 

Was there anything in particular you were trying to accomplish where you hoped that `DefineStmt` would cover the range statement case as well? E.g. such as trying to find all assignments?

**Comment by JasperSurmont** [comment]
Thanks for the answer!

In my case I just had a `Variable v` and I wanted to eliminate cases where `v` is declared using the short hand operator (range or not). I ended up simply splitting it up:  using `v.getDeclaration() = DefineStmt.getAnLhs()`, `v.getDelcaration() = RangeStmt.getKey()` and `v.getDeclaration() = RangeStmt.getValue()`

This works, but I was simply wondering if there was a more compact way to do it :)
