### ISSUE TITLE
A fatal error occurred: Cannot determine dbscheme of dataset

### ISSUE THREAD

**Issue by psamsel** [github/codeql#13311]
Hi, `codeql database analyze` with some javascript files on macOS 13 (intel) gives the following error: 

```
Running queries.
A fatal error occurred: Cannot determine dbscheme of dataset; candidates include /.../jsfiles/databases/test/db-javascript/semmlecode.javascript.dbscheme and /.../jsfiles/databases/test/db-javascript/._semmlecode.javascript.dbscheme
```

Commands used to create a database and analyse it are below. The `codeql database create` runs without any errors or warnings. 

```shell
$ codeql database create ./databases/test --language="javascript" --source-root="."
...
Finalizing database at /.../jsfiles/databases/test.
Successfully created database at /.../jsfiles/databases/test.

$ codeql database analyze --ram=9000 --threads=10 --format="csv" --output="./result.csv" ./databases/test /.../codeql-main/javascript/ql/src/codeql-suites/javascript-*
```

I used the newest repo for codeql queries, although I believe this is something about codeql CLI, not queries. Would you be able to shed some light on this issue?

**Comment by aibaars** [comment]
My guess would be that CodeQL does not know which dbscheme file to choose because there are two files with `.dbscheme` extension. Could you try removing the one starting with `._`:  `/.../jsfiles/databases/test/db-javascript/._semmlecode.javascript.dbscheme` ? I'm not sure where it came from, it might be some metadata file created by the Finder or so.

**Comment by psamsel** [comment]
And it worked! At least `codeql` went into query compilation phase so I assume it runs ok. Thanks a lot.
