### ISSUE TITLE
Predicate to catch a load in C/C++?

### ISSUE THREAD

**Issue by scottconstable** [github/codeql#14025]
Hi,

I'm trying to write a predicate that can catch any source-level load in a C/C++ analysis. One option is to try to match all of the C/C++ AST nodes that can load data from a pointer access, field access, array access, etc. But this seems very complex and brittle, especially since the same AST node could either be a load or a store, depending on the surrounding context. Another option is to use CodeQL IR's `LoadInstruction`. But I find that this approach is too imprecise. For example:
```C
int local_var;
...
int another_local_var = local_var; // this assignment is represented by a LoadInstruction in CodeQL IR
```

So my question is: how can I write a predicate (or does one already exist??) that can match any source-level load in C/C++?

**Comment by MathiasVP** [comment]
Hi @scottconstable,

There are multiple ways of solving this issue. We have a (somewhat old, but still useful) library for detecting source-level loads (see [this predicate](https://github.com/github/codeql/blob/main/cpp/ql/lib/semmle/code/cpp/controlflow/Dereferenced.qll#L92)) which enumerates the AST elements that represents loads of various kinds. Note that this predicate also attempts to be smart and perform some interprocedural analysis to find arguments that will be dereferenced inside the body of the target function. This may or may not be the behaior you want, so if you don't want this behavior you either:
- Exclude this cases manually by using the [dereferencedByOperation](https://github.com/github/codeql/blob/main/cpp/ql/lib/semmle/code/cpp/controlflow/Dereferenced.qll#L31) predicate (which the top-level predicate is calling internally), or
- Roll your own implementation by enumerating the AST cases you want to consider

As you point out yourself, the IR does offer a uniform way of getting this information. However, as you also notice, there's a `LoadInstruction` in an example like:
```
int local_var;
...
int another_local_var = local_var;
```
because `local_var` has an lvalue-to-rvalue conversion (see [cppreference](https://en.cppreference.com/w/cpp/language/value_category) for more information on this). So the IR is correct in that there's a load happening here, but you may not care about all of these loads. You can exclude these by using a predicate like:
```ql
predicate dereferenced(Expr e) {
  exists(LoadInstruction load, Instruction address |
    e = load.getUnconvertedResultExpression() and // i.e., `e` is the result of the dereference. Alternatively, you could also look at `load.getSourceAddress().getUnconvertedResultExpression()` if you're interested in the expression corresponding to the _address_ of the load.
    address = load.getSourceAddress() and
    not address.isGLValue() // and the load isn't from a glvalue-to-rvalue conversion
  )
}
```

I hope this helps!

**Comment by scottconstable** [comment]
Hi @MathiasVP,

Thank you for the examples. Since my analysis is almost entirely based on IR, I feel like `dereferencedByOperation` is undesirable. I tried your `dereferenced` predicate, and found that it did not match loads of the form:
```C
int x = ptr->some_int;
```
I wrote the following predicate, which so far seems to match anything that I would generally expect to compile into a load:
```CodeQL
Instruction getMemoryAddressInstruction(Instruction i) {
  (
    result = i.(LoadInstruction).getSourceAddress() or
    result = i.(LoadInstruction).getSourceAddress().(FieldAddressInstruction).getObjectAddress()
  ) and
  not result instanceof FieldAddressInstruction and
  not result instanceof VariableAddressInstruction and
  not result instanceof ConstantValueInstruction
}

predicate isLoad(Instruction address, LoadInstruction load) {
  address = getMemoryAddressInstruction(load)
}
```
I basically just modified this existing class to apply to loads specifically, rather than any instruction that computes a memory address: https://github.com/github/codeql/blob/8624ff12be59149b977bc4356f8cd8a5108e84e5/cpp/ql/lib/experimental/semmle/code/cpp/rangeanalysis/InBoundsPointerDeref.qll#L37

I will go ahead and close this issue because this predicate meets my requirements. I hope that others with find this thread useful!
