### ISSUE TITLE
Why does CodeQL output many duplicate paths in alerts?

### ISSUE THREAD

**Issue by flyboss** [github/codeql#14227]
Hello,

I've come across an example ql file called [TaintedPath.ql](https://github.com/github/codeql/blob/main/javascript/ql/src/Security/CWE-022/TaintedPath.ql) provided by CodeQL. This script is used to address a path injection problem illustrated in this [example JavaScript file](https://github.com/github/codeql/blob/main/javascript/ql/src/Security/CWE-022/examples/TaintedPath.js). 

After executing TaintedPath.ql,  CodeQL does find two alerts which are true positives. But for each of alerts, CodeQL outputs many duplicate paths. See below image. For the first alerts, CodeQL outputs 16 paths which are all the same. 

![20230915151834](https://github.com/github/codeql/assets/17377518/85db96bc-865c-4acb-bc0d-41f16c397030)

My enviroment is Windows 11; CodeQL extension for Visual Studio Code v1.8.12; CodeQL command-line toolchain 2.13.5.

**Comment by asgerf** [comment]
We're aware of the issue with this query.

It happens because the query internally distinguishes between whether the value is an absolute or relative path, and whether it normalized or not. Under the hood these different paths correspond to the different states the value can take. So one path might demonstrate how a normalized relative path can pass through, while another demonstrates how an unnormalized absolute path can pass through. The problem arises when there are there are many combinations of absolute/relative and normalized/raw paths that can pass through, and simply showing all of these paths isn't very helpful to the end-user.

**Comment by flyboss** [comment]
Thank you very much! I have managed to retrieve the impact factors, but I have a few questions regarding the concepts of "whether the value is an absolute or relative path and if it is normalized or not". Are these concepts provided by CodeQL or based on program language theory? Could you please provide me with more detailed documentation on these topics?

Besides, can we set some configurations to avoid showing all of the same paths? As I want to count true/false positives/negatives.

**Comment by asgerf** [comment]
> I have a few questions regarding the concepts of "whether the value is an absolute or relative path and if it is normalized or not". Are these concepts provided by CodeQL or based on program language theory?

The concepts I'm talking about here are just file system (POSIX) paths:
- A normalized path is (for our purposes) a path where all `../` segments, if any, occur at the beginning of the string. 
- An absolute path is one that starts with `/`.

> Besides, can we set some configurations to avoid showing all of the same paths? As I want to count true/false positives/negatives.

It's not currently possible to avoid the duplication. If you want to count TPs/FPs, count the alerts, not the paths. You also can't count FNs/TNs based on the paths, because there can be infinitely many feasible paths, there is no way to enumerate all of the paths in the UI or in a SARIF file.

**Comment by flyboss** [comment]
Thanks a lot!  I got it.
