### ISSUE TITLE
codeql-cpp: missing source file for small-size project

### ISSUE THREAD

**Issue by xiaofen9** [github/codeql#14593]
codelql extractor for cpp missed source files for my small projects.
For example, for the case I provide, it even miss main.c
Could you help check what is the bug? I've upload the small project I am testing.

![image](https://github.com/github/codeql/assets/20917869/f257b97e-33ad-485c-8a0e-34408447cd9f)

https://drive.google.com/file/d/1jvK4XfjI_4_AHWz-T6MPfK_Y9WKssVMh/view?usp=sharing

Here is the command I use
```
codeql database create --language=cpp --ram=2048 --overwrite --source-root  benchmark/c/cqe/KPRCA_00023 -c make k23.qldb
```

And I am using CodeQL command-line toolchain release 2.15.0.

**Comment by jketema** [comment]
Hi @xiaofen9,

Thanks for your question. Before creating the database did you remove all the object files and executables from your `out` directory? CodeQL will only pick up on source files when they are actually compiled, it will not find source files that are skipped because an object file already exists.

**Comment by xiaofen9** [comment]
Ah, you are right! Thanks!
