### ISSUE TITLE
Support for langVersion 12 and Net 8

### ISSUE THREAD

**Issue by jennyf19** [github/codeql#14803]
Which version of the CodeQL github action supports langVersion 12 and NET 8? or do you have an ETA for when this will be supported. Thanks!

```[tasklist]
### Tasks
```

**Comment by mbg** [comment]
Hi @jennyf19 👋 

We do not currently have a version of CodeQL that officially supports C# 12 and .NET 8. We will update our [public roadmap](https://github.com/orgs/github/projects/4247/views/1?filterQuery=label%3A%22github+advanced+security%22+label%3Acodeql) once we have an ETA for when we will have formal support.

In the meantime, do you have any particular issues you are currently running into when trying to analyse a C# 12 / .NET 8 project with the latest version of CodeQL?

**Comment by jennyf19** [comment]
@mbg here is the latest run with c#12/net 8 : https://github.com/AzureAD/microsoft-identity-web/actions/runs/6881055373 

Is there a way to force the C#12 for CodeQL?

**Comment by Gigas002** [comment]
Autobuild also fails, when encounters net8.0:

https://github.com/Gigas002/dotnet_gh_deploy/actions/runs/6890027998/job/18742215635#step:4:1

**Comment by mbg** [comment]
@jennyf19 It looks like the "Build with .NET 8" step in your workflow doesn't actually compile or run any tests there -- it stops after restoring projects. If I compare that to successful CodeQL runs on your repository, it seems that they [eventually](https://github.com/AzureAD/microsoft-identity-web/actions/runs/6886469222/job/18732206676#step:7:144) get to a "Starting test execution" message, which doesn't happen in your case with .NET 8. It is unlikely that CodeQL is responsible for that, so you may want to investigate why the tests don't get compiled and run at all. CodeQL will only be able to analyse your code if it actually gets compiled while CodeQL is active.

@Gigas002 Your issue is that .NET 8 was not installed on the GitHub Actions runner. See [my reply](https://github.com/github/codeql-action/issues/1996#issuecomment-1814442673) to a previous question about this. You can resolve this with a manual `setup-dotnet` step in your workflow that installs .NET 8, although I believe the GitHub Actions images have now been updated to include .NET 8 by default anyway so just re-running your workflow may work now.

**Comment by Gigas002** [comment]
@mbg Oh, the autobuild action seems to work with `net8.0` now indeed. Thanks for noticing this!

**Comment by turbo** [comment]
C# 12 / .NET 8 are now supported: https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/
