### ISSUE TITLE
zero files scanned results in green build

### ISSUE THREAD

**Issue by Dor-bl** [github/codeql#14841]
**Description of the issue**

Not sure if it's by design or not but if the workflow shows that 0 files were scanned why is the job successful?

`CodeQL scanned 0 out of 190 C# files in this job. Typically CodeQL is configured to analyze a single CodeQL language per job, so check the status page for overall coverage information across all jobs: https://github.com/Dor-bl/dotnet-client/security/code-scanning/tools/CodeQL/status/`

further details:
https://github.com/Dor-bl/dotnet-client/actions/runs/6915796013/job/18815217610#step:5:421

**Comment by MathiasVP** [comment]
Hi @Dor-bl

Could you rerun your workflow with debugging enabled so that we can debug this issue a bit more? You can see how to enable debugging [here](https://github.blog/changelog/2022-08-01-debugging-codeql-analysis-in-code-scanning-made-easier-by-obtaining-detailed-logs-and-debugging-artifacts-from-the-codeql-action/)

In the meantime, I will ask around to figure out if this is by design or not 🙂.

**Comment by aibaars** [comment]
We ran into a similar problem elsewhere. There seems to be a problem on Windows when comparing the list of scanned files and the list of files in the repository resulting in CodeQL reporting that no files were scanned because there is no overlap between the two lists. This should hopefully be fixed soon.

In the meantime, you can use the "Tool status" page to view the coverage percentage and download a CSV file with the list of scanned files.

Alternatively, you can check the SARIF file using the `jq` command to count the number of scanned files:
```
jq '[.runs[0].invocations[0].toolExecutionNotifications[].locations[].physicalLocation.artifactLocation.uri] | group_by(.) | map(select(length==2)) | length' csharp.sarif
```

**Comment by aibaars** [comment]
> We are seeing massive inconsistencies with the scanned files count across different languages (Java and C# primarily). We have a repo that isn't reporting any scanned files but when we create a new repo with the same files it will show 100% are scanned.
> 
> By using the method mentioned by [@aibaars](https://github.com/aibaars) we are able to confirm the scan accuracy from the latest sarif files.. less than ideal but better than thinking we are not scanning any files
> 
> comparing `find . -name "*.cs" | wc -l` and the files from the sarif file is enough for us to validate.

@DanBradbury Could you open a new issue instead of commenting on a closed one? Could you share logs and workflow files of the analysis runs on the two copies of the same repository?

The original problem reported in this issue was a bug in the code that counted file paths on Windows reporting `0` as a result. Only the summary count was wrong, the SARIF file correctly reported all file paths. Unless you are using an version of CodeQL, your problem should have a different cause. Which version of CodeQL is used can be found in the logs.

 Since fairly recently Java and C# code can be analysed without performing a build (`buildmode: none`). In this mode CodeQL scans all the `*.cs` files it can find. In the other build modes CodeQL analyses only the source files that are parsed by the compiler during a build. So if for whatever reason you are not building all your code then CodeQL would not analyse all the files. Which build mode is used can be found in the logs, and also in the workflow file.
