### ISSUE TITLE
Will Objective C and Objective C++ be supported in CodeQL?

### ISSUE THREAD

**Issue by yagoldin** [github/codeql#14923]
A lot of my team's iOS code is written in objective c and objective c++. I was wondering if these languages were going to ever be supported?

**Comment by intrigus-lgtm** [comment]
(Not speaking for GitHub in any capacity)

CodeQL _used_ to support Objective C a long long time ago (see https://github.com/github/securitylab/discussions/121#discussioncomment-32824 and https://github.com/github/securitylab/discussions/121#discussioncomment-32971).

I don't think that there are any plans to add back support for Objective C, because Swift has overtaken Objective C in popularity and supporting a language properly is a **lot** of work.

**Comment by jketema** [comment]
Hi @yagoldin,

Objective C/C++ are not a priority at the moment - in part because these languages see limited use. If at any point we'll look into support it, it will show up on the public roadmap https://github.com/orgs/github/projects/4247.

**Comment by jketema** [comment]
I'm closing this issue as completed for now.
