### ISSUE TITLE
Null Pointer deref false positive

### ISSUE THREAD

**Issue by tardigrade-9** [github/codeql#14945]
Objective of the query: For all extern functions which expect non null args, check if NULL check is done before.
I've chosen strcmp, strlen as functions for now. 
```
#include <iostream>
#include <cstring>

bool test_func(const char* str1, const char* str2) {
    return strcmp(str1, str2) == 0;
}

int main() {
    const char* str1 = NULL;
    const char* str2 = "World";
    int len = strlen(str1);
    int len2 = str1? strlen(str1): 0;
    test_func(str1, str2);
    if(test_func(str1, str2))
        std::cout << "Equal" << std::endl;
    else
        std::cout << "Not equal" << std::endl;
    
    if(str1 && test_func(str1, str2))
        std::cout << "Equal" << std::endl;
    else
        std::cout << "Not equal" << std::endl;
    
    if(str1){
        if(test_func(str1, str2))
            std::cout << "Equal" << std::endl;
        else
            std::cout << "Not equal" << std::endl;
    }
    return 0;
}
```

Here's the query
```

/**
 * @kind path-problem
 */
import cpp
import semmle.code.cpp.dataflow.new.DataFlow
import semmle.code.cpp.controlflow.Guards
import Flow::PathGraph


module UAFConfig implements DataFlow::ConfigSig {
     predicate isSource(DataFlow::Node source) {
           exists(Expr e | e = source.asExpr() |
                 e.(NullValue).getValue().toInt() = 0
                 ) 
     }

     predicate isSink(DataFlow::Node sink) {
           exists(FunctionCall fc|
                 (fc.getTarget().hasName("strcmp") or fc.getTarget().hasName("strlen")) and 
                 //fc.getTargetType().(RoutineType).hasCLinkage() and 
                 fc.getArgument(0) = sink.asExpr() and
                 sink.getType().getUnspecifiedType() instanceof PointerType
           )

     }

     predicate isBarrier(DataFlow::Node node) {
           exists(GuardCondition gc, Variable v |  
                 validCheckExpr(node.asExpr(), v) and
                 gc.controls(node.asExpr().getBasicBlock(), _)
                 )
           
     }
}

module Flow = DataFlow::Global<UAFConfig>;

from Flow::PathNode source, Flow::PathNode sink
where Flow::flowPath(source, sink)
select sink, source, sink, "Null ptr deref: $@ and $@.", source,
  "source", sink, "deref"
```
Even though there's no guard for str1, ` if(test_func(str1, str2))` this flow is **not** marked as NULL flow. 

Can someone please explain this behaviour, or point me to documentation where I can cover such scenarios.
Expected TP:
int len = strlen(str1);
test_func(str1, str2);
if(test_func(str1, str2))

**Comment by tardigrade-9** [comment]
I figured out that GuardCondition protects  something inside `if(){..}` and not inside the condition. But how to check something like `if(a && foo(a))` where a dominates foo(a).

**Comment by MathiasVP** [comment]
Hi @tardigrade-9,

The answer is a little bit complicated, unfortunately.

1. First, your barrier is slightly incorrect:

You want your barrier to say that any mention of the variable inside the branch guarded by the condition is safe. However, your current barrier:
```ql
exists(GuardCondition gc, Variable v |  
  validCheckExpr(node.asExpr(), v) and
  gc.controls(node.asExpr().getBasicBlock(), _)
)
```
states that the guard condition _itself_ is a barrier instead of any nodes that are guarded by it is a barrier (because of the use of `validCheckExpr`). The proper fix here would be to use the [value numbering](https://codeql.github.com/docs/codeql-language-guides/hash-consing-and-value-numbering/) library to say that any expression that evaluates to the same value as the guard condition is a barrier.

2. Second, is that we (unfortunately) have two guards libraries, and one of them is able to reason about the `if(..guarded..)` pattern that you describe, and the other one isn't. The one you import here using `import semmle.code.cpp.controlflow.Guards` unfortunately isn't able to do this. The `import semmle.code.cpp.controlflow.IRGuards` library is, though!

We can get around both of these problems by using the `DataFlow::BarrierGuard` module to create the correct barrier automagically. Unfortunately, the interface is a bit annoying (since it digs into our internal representation of your program). We'd like to improve this situation eventually, but for now that's the best we can do:

```ql
/**
 * @kind path-problem
 */

import cpp
import semmle.code.cpp.dataflow.new.DataFlow
import semmle.code.cpp.controlflow.IRGuards
import Flow::PathGraph

/**
 * Holds if `g` is a guard that ensures that `e` is not null when `g` evaluates to `branch`
 */
predicate isNotNullCheck(IRGuardCondition g, Expr e, boolean branch) {
  g.comparesEq(any(Instruction instr | instr.getUnconvertedResultExpression() = e).getAUse(),
    any(ConstantValueInstruction const | const.getValue() = "0").getAUse(), 0, false, branch)
}

module UAFConfig implements DataFlow::ConfigSig {
  predicate isSource(DataFlow::Node source) {
    exists(Expr e | e = source.asExpr() | e.(NullValue).getValue().toInt() = 0)
  }

  predicate isSink(DataFlow::Node sink) {
    exists(FunctionCall fc |
      (fc.getTarget().hasName("strcmp") or fc.getTarget().hasName("strlen")) and
      //fc.getTargetType().(RoutineType).hasCLinkage() and
      fc.getArgument(0) = sink.asExpr() and
      sink.getType().getUnspecifiedType() instanceof PointerType
    )
  }

  predicate isBarrier(DataFlow::Node node) {
    node = DataFlow::BarrierGuard<isNotNullCheck/3>::getABarrierNode()
  }
}

module Flow = DataFlow::Global<UAFConfig>;

from Flow::PathNode source, Flow::PathNode sink
where Flow::flowPath(source, sink)
select sink, source, sink, "Null ptr deref: $@ and $@.", source, "source", sink, "deref"
```

Here, we use the `DataFlow::BarrierGuard` module and instantiate it with a predicate that tells the module what is considered to be a valid guard. And in this case it's any check that compares the expression to a null value.

Using the above query I get two results. The first result corresponds to your `int len = strlen(str1);` TP, and the last result contains two paths that correspond to the `test_func(str1, str2);` and `if(test_func(str1, str2))` TPs.

I hope that helps!

**Comment by tardigrade-9** [comment]
Thank you so much for the quick help! Appreciate it.
