### ISSUE TITLE
CodeQL not detecting YAML workflow vulnerabilities using on.push & on.pull_request

### ISSUE THREAD

**Issue by cpc-perrej** [github/codeql#15239]
## **CodeQL not detecting YAML workflow vulnerabilities using on.push & on.pull_request**

I'm trying to implement CodeQL Security Scanning to our internal GitHub Action repositories to scan YAML files for vulnerabilities.

I've used two different script injection attacks from GH blog and GH workshops to test CodeQL pickup of vulnerabilities in YAML files.

1. [Check Issue Comment](https://github.com/githubuniverseworkshops/workflow-script-injection/blob/main/.github/workflows/check-issue-comment.yml)
2. [Check PR Title](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#example-of-a-script-injection-attack)

The first attack is detected by CodeQL only if the workflow is being executed with on.issue and **_NOT_** detected if being executed with on.push and/or on.pull_request

The second attack is not being detected by CodeQL at all.

Is this a bug or am I misunderstanding something? In this current situation the only way I see this being caught would be with a code review.

Also, would it be possible to add a scanning category specifically for GitHub Actions, instead of having to use the 'javascript' option.

P.S. - I'm putting powershell scanning on my 2024 Christmas list.

### **Screenshots:**
![image](https://github.com/github/codeql/assets/108813358/e5a49bce-7e92-47c3-b7f1-61a3b46c46bc)
![image](https://github.com/github/codeql/assets/108813358/bf292fe8-7661-4de1-95f7-69bc72b56a40)
![image](https://github.com/github/codeql/assets/108813358/cc09c688-9d90-43b7-8d0e-e6ab05cc8759)

**Comment by intrigus-lgtm** [comment]
The idea is pretty much that there is no vulnerability when using a `push` trigger.
This is because only people with **write access** should be able to push new commits. If somebody can push new commits, guarding against script injection is pointless. And commits indirectly pushed by merging a PR should have been code reviewed.

When using a `pull_request` trigger, the code receives a token with read permissions if the PR is from a fork.
So an attacker cannot do anything bad with this token.

**Comment by jonthenerd** [comment]
A few points on this:

 - CodeQL is also there to provide a level of assistance to GitHub Action authors, such that composite actions can also have script injection vulnerabilities found during authorship.
 - Many corporate environments disable forks and instead use general permissions, branch protection settings, and environment protection settings to provide the guardrails needed.
 - Even a person with write access can make a mistake, and others (humans) are capable of missing the item in PR. 

What harm does identifying this vulnerability in these scenarios cause? Or does it only address the vulnerability for some portion of the population which needs it and does not affect the others?

**Comment by MathiasVP** [comment]
> Also, would it be possible to add a scanning category specifically for GitHub Actions, instead of having to use the 'javascript' option.

We agree this would be useful and are thinking about it 👍

As for your first part of the question, I'll forward this to our JS team and hopefully they can explain the reasons for not flagging up these alerts

**Comment by asgerf** [comment]
As @intrigus-lgtm also mentioned, the query is focused on issues that an external user could exploit. However it seems reasonable to flag these issues as well, so I've opened https://github.com/github/codeql/pull/15275 to expand the scope of the query a bit.

**Comment by JarLob** [comment]
Hi @cpc-perrej,

The reason it doesn't report an injection on `pull_request` is that there is even more straightforward way. On `pull_request` it uses the workflow from the pull request, not from target repository. So even if your workflow in not vulnerable I can make a pull request from external fork with `echo 'pwned'` and it will run it with read only permissions. It is remote code execution (with read-only permissions and no access to secrets) by design. It was abused by crypto miners in the past and this is why there is the `first time contributors` check now.

Regarding `on: push`. The `on:` defines when the workflow is started. Depending on the trigger some github event context fields are available and some are not. Basically there is no such info available as pull request title when workflow runs on push event. So if there is the `${{ title }}` injection if will be always empty.

You can experiment with https://docs.github.com/en/actions/learn-github-actions/contexts#example-printing-context-information-to-the-log yourself to see what context information is available on what trigger and let us know if we missed anything.

**Comment by asgerf** [comment]
Closing the issue for the reason described above. ☝

**Comment by jonthenerd** [comment]
@asgerf and @JarLob we'll need to take some time to compare what you're describing to what we're seeing.
