### ISSUE TITLE
False positive: Modification of parameter with default for Python copy.deepcopy

### ISSUE THREAD

**Issue by njzjz** [github/codeql#15317]
**Description of the false positive**

When I use `copy.deepcopy` from the Python standard library to copy a `dict`, and then modify the copied `dict`, CodeQL gives [Modification of parameter with default](https://codeql.github.com/codeql-query-help/python/py-modification-of-default-value/). 

**Code samples or links to source code**

```py
    data = copy.deepcopy(data)
    variables = data.pop("@variables")
```

https://github.com/deepmodeling/deepmd-kit/blob/5fbca37d456f6abd06668d4a7941c87b9cc26ebe/deepmd_utils/model_format/network.py#L206-L207

It seems to complain that `deepcopy` may return `_nil`. However, after I read the code for `deepcopy` (https://github.com/python/cpython/blob/b6535ea7ecf40c51a9a13089d961c29abeaffa5e/Lib/copy.py#L128-L140), I think it never returns `_nil`.

**URL to the alert on GitHub code scanning (optional)**

https://github.com/deepmodeling/deepmd-kit/security/code-scanning/1509

**Comment by tausbn** [comment]
Thank you for your report!

I think what's happening here is the following. Internally, the query in question is implemented using the data-flow library. By default (because data-flow is all about the values being passed around), we treat `copy.deepcopy` as a function that preserves such flow, as this is the correct interpretation for all of our security analyses.

However, in this case it's not actually the _value_ that's important, but rather its _identity_ (i.e. its location in memory). Thus, in this case, `copy.deepcopy` should actually _block_ the flow that is there by default.

This should hopefully be an easy fix, as all it requires is that we additionally treat `copy.deepcopy` as a barrier for data-flow (for this particular query).
