### ISSUE TITLE
False positive - Incomplete string escaping or encoding

### ISSUE THREAD

**Issue by manojsridharsrinivasan** [github/codeql#15610]
**Description of the false positive**

I am using replace with regex and with g for global replace but still CodeQL is complaining `Incomplete string escaping or encoding`

**Code samples or links to source code**

`name = name.replace(/[\[\]]/g, "\\$&");`

The regex is `/[\[\]]/g` which has `g` at the end. And this is valid regex for replacing square brackets open and close.

**Comment by smowton** [comment]
Reproducing this I note that the specific message is "This does not escape backslash characters in the input.". This is because while your regex will replace `[` with `\[` as desired, it will replace `\[` with `\\[`, leaving the `[` once again unescaped.

For this reason the query checks that the incoming `name` has had any backslashes escaped beforehand, which can be achieved with a similar regex replace operation.

**Comment by manojsridharsrinivasan** [comment]
I will now try with `name.replace(/(?<!\\)[\[\]]/g, "\\$&"`

**Comment by manojsridharsrinivasan** [comment]
It worked, Thank You.

**Comment by smowton** [comment]
It has successfully tricked CodeQL, but I'm not sure it has worked as intended! For example, consider I could now provide `\\[`; the regex replace would not fire, and the parsed result would again be an unescaped `[`. Assuming the downstream reader will decode `\\` to `\` and `\[` to `[`, I think the correct fix is to escape both existing backslashes and `[` and `]` characters.
