### ISSUE TITLE
[Java] What annotations should I use to improve the processing of this predicate

### ISSUE THREAD

**Issue by chmodxxx** [github/codeql#16991]
### Discussed in https://github.com/github/codeql/discussions/16975

<div type='discussions-op-text'>

<sup>Originally posted by **chmodxxx** July 14, 2024</sup>
Hello, 

I have this predicate : 

```
predicate callsFooApi(Method m) {
    exists(delegatedMethod dm |  
     dm.getSignature() = m.getSignature() and 
      (  
         callsOne(dm) or 
         callsTwo(dm) or 
         callsThree(dm)
     )
   )

}

```

So I want to know how I can : 

- short circuit the logic so that if a single delegated Method passes one of the booleans (callsOne .. callsThree), we should stop looking at other delagated Methods. 
- short circuit the actual calls logic so that if callsOne passes, we don't need to verify callsTwo and callsThree 

I know there are a bunch of annotations that codeQL supports, but im not sure how to pick the right ones. 

For reference the delegated method logic is needed since our java code has a bunch of methods overriding each other from difference interfaces and looking at getAnOverride and/or getAnImpl doesn't find all the necessary methods, so resolving methods by signature works in our case.  
Also the callsOne ... callsThree are predicates that perform dataflow and we are ranking them from least resources consuming to most. </div>

**Comment by aibaars** [comment]
The way QL programs are evaluated is very different from most other languages. Things like "short-cutting" the evaluation of `and` and `or` do not work.

For more information about QL' s evaluation:
* https://codeql.github.com/docs/ql-language-reference/evaluation-of-ql-programs/
* https://codeql.github.com/docs/ql-language-reference/ql-language-specification/#evaluation

The list of available compiler pragmas with short descriptions can be found at https://codeql.github.com/docs/ql-language-reference/annotations/#compiler-pragmas

**Comment by chmodxxx** [comment]
Thanks @aibaars  I understand that QL does a sort of bottom-up approach where in my example . I guess a rough flow will look like this : 
- Load all methods  (delegatedMethod) : r1 
- Evaluate the body of the three predicates on all methods : r2 (the result is going to be union of all the three)
-  join r1 , r2  where methods have similar signature

My question is, is there a better way to write this to make sure QL compiler does that in an optimal way ? There are a bunch of compiler pragmas that I am not sure which ones would be good for my case because I aint sure what codeQL is doing bottom up especially when you have complex queries.

**Comment by aibaars** [comment]
The QL compiler does a lot of clever things such selecting a good join order or pushing in relevant context to ensure intermediate results are smaller, etc. It is really hard to say how to write QL code in a way that the compiler makes the best of it. I would recommend writing QL code in the way that is most natural / understandable to you. If performance is not what you expect, first look for easy to make mistakes, such as accidental cross products due to unrestricted variables/parameters. The next step would be to run the query with performance logging enabled (`--evaluator-log`, `--tuple-counting` ) to see which predicates are slow (from experience it's often another one than you'd expect as first guess ;-)) . 

If you really want to know what the compiler did with your code, you could use the `codeql query decompile` command to view the `RA`( relational algebra) or `DIL` (datalog intermediate language) forms.

**Comment by chmodxxx** [comment]
Oh wow the decompile thingy is very cool, thank you so much.
