### ISSUE TITLE
C++: `cpp/ql/examples/snippets/addressof.ql` doesn't define an `@kind` property

### ISSUE THREAD

**Issue by ysuLihua** [github/codeql#17170]
**use cpp/ql/examples/snippets/addressof.ql analyze cpp_db failed**

Problem:
![image](https://github.com/user-attachments/assets/44b9baef-5c8f-41ca-9f62-dbbb5bd80cbf)

How to resolve the issue， Thanks!

**Comment by smowton** [comment]
This is because the `addressof.ql` snippet is not a "full" CodeQL query suitable for use with `database analyze` or `database interpret-results`. To use either of these commands, the query should define an `@kind` tag, typically `problem` (for a problem with a single location) or `path-problem` (for a problem with an associated flow path). The query also needs to produce the right "result pattern" -- for `@kind problem` that means returning at least two columns, a location and an alert message.

Therefore to use this query with `analyze` we need to make a couple of changes:

```
...
 * @description Finds address-of expressions (`&`) that take the address
 *              of a reference variable
 * @kind problem
 * @severity warning
...
```
and replace the `select` clause with
```
select addr, "Alert message"
```

Alternatively, "plain" queries that don't necessarily define a `@kind` and can have any form of output can be run in two ways: (1) the most common, [use the query with our VSCode CodeQL development environment](https://docs.github.com/en/code-security/codeql-for-vs-code), or (2) use `run-queries` instead of `analyze`, which just runs the query but doesn't try to export the results to SARIF, then use `codeql bqrs decode db/results/codeql/cpp-examples/snippets/addressof.bqrs` to view the results on the command-line.

Finally of course if you just want any query to test with, try using one of the other `.ql` files under `ql/src` -- but not the `examples` directory, which mostly contains snippets not suitable for SARIF export, and therefore for the `analyze` or `interpret-results` commands.

**Comment by ysuLihua** [comment]
The problem was solved after the modification according to your suggestion. Thanks!
