### ISSUE TITLE
Tuple Mismatching Results in all variables labelled as sensitive data

### ISSUE THREAD

**Issue by DefinetlyNotAI** [github/codeql#17255]
**Description of the false positive**

CodeQL keeps flagging tuples set as sensitive data IF the tuple contains a password, even after the tuple is diverged to other variables:
`password, username, message = example_tuple` it flags all the 3 variables as password (if we also say that example_tuple had 1 variable with password)

This generates many false-positive it becomes cluttered: as if i log or do anything as in store the username or message i get that err

**Code samples or links to source code**

PART 1
            debug = config["use_debug_(ONLY_IF_YOU_DEVELOPED_THIS!)"]
            api = config["api"]
            username = config["username"]
            password = config["password"]
            exclusion_titles = config["exclusion_titles"]
            return (
                    debug,
                    api,
                    username,
                    password,
                    exclusion_titles,
                )
PART 2
            config_data = self.__read_config()
            (
                DEBUG_DB,
                API,
                USERNAME,
                PASSWORD,
                EXCLUDE,
            ) = config_data

STEP 3
                log.info(
                    f"A request has been made to generate an exam by the user {USERNAME}"
                )
                
Step 3 is where it flagged it, log.info makes it log the thing in a .log file

**URL to the alert on GitHub code scanning (optional)**

https://github.com/DefinetlyNotAI/Test_generator/security/code-scanning/54
https://github.com/DefinetlyNotAI/Test_generator/security/code-scanning/53
https://github.com/DefinetlyNotAI/Test_generator/security/code-scanning/52
https://github.com/DefinetlyNotAI/Test_generator/security/code-scanning/51
https://github.com/DefinetlyNotAI/Test_generator/security/code-scanning/50

**Comment by aibaars** [comment]
Thank you for this false positive report. Resolving this issue is not a current product priority, but we acknowledge the report and will track it internally for future consideration.

This seems to have the same cause as https://github.com/github/codeql/issues/16976 and https://github.com/github/codeql/issues/17008

**Comment by aibaars** [comment]
Hopefully the following pull request will fix this problem: https://github.com/github/codeql/pull/17030

**Comment by DefinetlyNotAI** [comment]
oh yeah i did open that pr, but why isnt it top priority, its pretty common annoying and spawns too many errors

**Comment by aibaars** [comment]
> oh yeah i did open that pr, but why isnt it top priority, its pretty common annoying and spawns too many errors

False positives reports aren't top-priority. However, that doesn't mean we ignore them. If there are multiple reports with the same cause then that increases the priority. As you can see superfluous taint via tuples has been reported a couple of times and a fix is being worked on. Unfortunately, August tends to be a slow month due to holidays. Hopefully a fix will be released soon.

Thanks for your patience and for reporting the issue.
