### ISSUE TITLE
How to fix the ExternalAPIsUsedWithUntrustedData or ExternalAPIsUsedWithUntrustedData error ?

### ISSUE THREAD

**Issue by SSA2001** [github/codeql#17270]
When I scanning my code, it throw this error, and the example only has the bad like this:
```
express().get('/news', (req, res) => {
    let topic = req.query.topic;
    res.send(`<h1>${topic}</h1>`);
});
```
is there a good example?

**Comment by SSA2001** [comment]
```
if (ctx.query.access_token) {
    accessTKInfo = ctx.query.access_token;
    logger.info({ type:'不存在access_token' });
}
```
my code where have error like this

**Comment by aibaars** [comment]
I assume you are asking about results from the following queries:
* [UntrustedDataToExternalAPI.ql](https://github.com/github/codeql/blob/main/javascript/ql/src/Security/CWE-020/UntrustedDataToExternalAPI.ql)
* [ExternalAPIsUsedWithUntrustedData.ql](https://github.com/github/codeql/blob/main/javascript/ql/src/Security/CWE-020/ExternalAPIsUsedWithUntrustedData.ql)

Those queries are not run by default and have a very high false positive rate by design. They simple flag all places where untrusted data (for example remote user input) flows into an external library. Very often this is just fine, but it could point at a security risk. Those queries are intended to be used by security researchers performing manual code inspections to point them at potentially interesting places in the code. See also the documentation in the `qhelp` files next to the queries.
