### ISSUE TITLE
How to use ql to calculate N factorial by recursion function

### ISSUE THREAD

**Issue by ysuLihua** [github/codeql#17374]
The QL recursion is hard to understand.
This is my code, and the runtime is stuck in an infinite loop. How to Define the Exit Condition of a Recursive Function？

```
import cpp

int fact(int n){
    if n in [0..1]
    then result = 1
    else result = fact(n-1)*n
}


select fact(10)
```

**Comment by hvitved** [comment]
The QL evaluator does bottom-up evaluation, meaning that it attempts to compute the full `fact` relation (which is infinite). So you will need to restrict `n` inside the body of `fact` in order to prevent infinite recursion. See also https://codeql.github.com/docs/ql-language-reference/recursion/#recursion.

**Comment by ysuLihua** [comment]
@hvitved Thanks for your advice, I understand the use of it
