### ISSUE TITLE
False positive: Unread local variable used in Java assert

### ISSUE THREAD

**Issue by simonhir** [github/codeql#17531]
**Description of the false positive**

Variables that are only used in junit `assert` statements like `assertEquals` are marked as `Unread local variable`.

**Code samples or links to source code**

I.e. https://github.com/it-at-m/refarch/blob/e18859331d0f55b43aae3170f947b840df1fde9c/refarch-integrations/refarch-dms-integration/refarch-dms-integration-core/src/test/java/de/muenchen/refarch/integration/dms/adapter/out/fabasoft/FabasoftAdapterTest.java#L84-L86
where `procedureResponse` is marked as `Unread local variable`. This makes also no difference if Lombok `val` is used or the direct type.

Above code extracted for reference:
```
val procedureResponse = fabasoftAdapter.createFile(file, "user");
assertEquals(procedureResponse, "1234567890");
```

**URL to the alert on GitHub code scanning (optional)**

https://github.com/it-at-m/refarch/security/code-scanning/36
https://github.com/it-at-m/refarch/security/code-scanning/55 (same line but with direct type String)

**Comment by simonhir** [comment]
Could be a duplicate of https://github.com/github/codeql/issues/11989 but not really sure.

**Comment by smowton** [comment]
Looks like this is caused by use of the package `com.fabasoft.schemas.websvc.lhmbai_15_1700_giwsd`, which appears to be generated code. I recommend either generating Java source for that package (within the repository directory) prior to CodeQL extraction, or switching to build-mode `autobuild` or `manual` per https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages#codeql-build-modes in order to generate and analyse this code as part of your normal build process.

**Comment by simonhir** [comment]
@smowton thank you. Took some time to refactor on out side but now with `autobuild` the warnings are resolved.
