### ISSUE TITLE
[Java][QL] Need help improving the logic of this Java query 

### ISSUE THREAD

**Issue by chmodxxx** [github/codeql#17559]
Hello, we are currently trying to create a query that will detect if a service user token is being used before checking the authorization of the calling user ( this is a problem we have). 
Our endpoints definitions look like this : 

```java
@Override 
public void doStuff(AuthHeader authHeader, ParamType param) { 
    
    someClass.doThing();   
    checkUserAuth(authHeader);

}
```

And doThing Method is basically doing an operation using the service user token : 

```java 

public void doThing() {
    doPrivilegedOperation(serviceUserToken.getAuthHeader(), params);
}

note : The type of serviceUserToken is ClientUserTokenProvider. 

```

My query does something like : 

```codeql 

import java
import libs*

int getAuthHeaderLine(Method mm) {
  exists(MethodCall call |
    mm.getBody().getBasicBlock().getASuccessor*().(MethodCall) = call and
    call.getArgument(0).getType() instanceof AuthHeader and
    result = call.getLocation().getStartLine()
  )
}

int getStatementLine(Method mm, MethodCall mc) {
  mm.getBody().getBasicBlock().getASuccessor*().(MethodCall) = mc and
  result = mc.getLocation().getStartLine()
}

from MethodCall mc, Method endpoint, MethodCall usingServiceTokenCallable, Api wcApi
where
  endpoint = wcApi.getAMethod() and
  mc.getMethod().getName() = "getAuthHeader" and
  mc.getQualifier().getType() instanceof ClientUserTokenProvider and
  mc.getCaller() = usingServiceTokenCallable.getMethod() and
  endpoint.getBody().getBasicBlock().getASuccessor*().(MethodCall) = usingServiceTokenCallable and
  min(int i | i = getAuthHeaderLine(endpoint) | i) >
    min(int ii | ii = getStatementLine(endpoint, usingServiceTokenCallable) | ii)
select endpoint,
  "This API endpoint appears to be using a service user token before checking the user's authHeader "
    +
    "Please make sure that you check the user's privilege before using the service user token for operations",
  "signature", endpoint.getFile().getRelativePath().toString() + ":" + endpoint.getSignature()

```

I was wondering if you see any issues (performance or otherwise ) with this query, my logic is going backward from the serviceUserToken callable and then going forward from the Api method definition, and then grabbing the first line number of the serviceUser callsite and the line number of the (first) authHeader call (assumption is that the first use of the user authHeader will be enough condition). 

Can I achieve this with SSaVariables and without doing the line number logic ? Also I am not sure if my logic can flow through inter-procedural calls (if the serviceUser token use is more than one methodCall away).

**Comment by smowton** [comment]
Firstly note that `mm.getBody().getBasicBlock().getASuccessor*().(MethodCall) = call` can be replaced by `call.getEnclosingCallable() = m`. This is a synonym for `call.getCaller() = m`, so either can replace that more verbose and expensive traversal.

However, as you say, there are much more principled ways to achieve this than looking at source line numbers. Since we're dealing with a void-typed validation method here (i.e. the pattern is `validate(x); /* or presumably, throw or die or something*/ use(x)` not `if (isValid(x)) use(x)`, I recommend taking inspiration from https://github.com/github/codeql/blob/main/java/ql/lib/semmle/code/java/security/Validation.qll which is pursuing both cases. Note that code is specifically looking for use of `String.contains`, but it should be readily adaptable to your example.

Note that we have both the simple `if (isValid(...))` case, written `guardcall.(Guard).controls(va.getBasicBlock(), _)` (a `Guard` is a boolean-typed expression, like `isValid(...)` or `getStatus(...) == Status.VALID` or indeed `x < 0`), but then following we have control-flow dominance logic for the void-typed validation method case:

```ql
    exists(ControlFlowNode node |
      guardcall.getMethod().getReturnType() instanceof VoidType and
      guardcall.getControlFlowNode() = node
    |
      exists(BasicBlock succ |
        succ = node.getANormalSuccessor() and
        dominatingEdge(node.getBasicBlock(), succ) and
        succ.bbDominates(va.getBasicBlock())
      )
      or
      exists(BasicBlock bb, int i |
        bb.getNode(i) = node and
        bb.getNode(i + 1) = node.getANormalSuccessor()
      |
        bb.bbStrictlyDominates(va.getBasicBlock()) or
        bb.getNode(any(int j | j > i)) = va
      )
    )
```

This is the case I expect will apply to your example.
