### ISSUE TITLE
[Feature Request] Allow Field Constraints in Member Predicates for Enhanced Flexibility in Class Queries

### ISSUE THREAD

**Issue by cradiator** [github/codeql#17990]
# Feature Request
## Summary
Allow Field to be constrained within member predicates, not just in characteristic predicates within a class.

## Context
In writing a ControlFlowReach class that mimics the dataflow interface, I'd like to define a status field that can be calculated in subclasses according to the source node and then used across member predicates like isSource, isSink, and isBarrier. However, the current limitation requiring Field to be constrained only within characteristic predicates prevents this.

## Example Code
Here’s my ControlFlowReach class:

```
abstract class ControlFlowReach extends string {
  bindingset[this]
  ControlFlowReach() { any() }

  predicate reaches(ControlFlowNode src, ControlFlowNode snk) {
    isSource(src) and isSink(snk) and reach_internal(src, snk)
  }

  abstract predicate isSource(ControlFlowNode node);
  abstract predicate isSink(ControlFlowNode node);
  predicate isBarrier(ControlFlowNode node) { none() }

  private predicate reach_internal(ControlFlowNode current, ControlFlowNode sink) {
    not isBarrier(current) and
    (current = sink or reach_internal(current.getASuccessor(), sink))
  }
}
```
In the subclass SomeFlow, I define status to calculate a value based on the source node, which I then want to use in isSink and isBarrier.

```
class SomeFlow extends ControlFlowReach {
  Expr status;

  SomeFlow() {
    this = "SomeFlow"
  }

  predicate isSource(ControlFlowNode node) {
    // condition on node
    and status = <value_based_on_node>
  }

  predicate isSink(ControlFlowNode node) {
    // uses status
  }
}
```

## Issue
Based on the current design, even with ```isSource(src) and isSink(snk)``` in ```reaches()```, the status field in isSink and isSource seems to take different values. The documentation notes that fields must be constrained in characteristic predicates and not in member predicates, but it’s unclear why this limitation exists.

## Questions
1. Why must fields be constrained only in characteristic predicates and not in member predicates?
1. Why does status appear to have different values in isSink and isSource, even though they are called in ```reaches()``` under the condition ```isSource(src) and isSink(snk)```?
1. Could this feature be added in the future, allowing fields to be constrained in member predicates for greater flexibility?

Thank you for considering this request.

**Comment by smowton** [comment]
Could you give an example of how you use `SomeFlow`? Then I'll be able to suggest how you might structure this as CodeQL. Fundamentally fields can be constrained in any predicate, but the strong exhortation to constrain them mostly/entirely in the charpred stems from CodeQL classes with fields in essence representing multi-column tables:

For example if I have a class `class C extends Expr` and has a field `int x`, then that represents a table with two columns, `Expr this` and `int x`. This is similar to a plain old `predicate myRelation(Expr this, int x)`. If the charpred doesn't constrain `x` (here it _must_ because `int` is at least abstractly infinite otherwise), then that table would be a huge cartesian product of all Exprs and all field values -- clearly not a good thing.

However suppose I do constrain it with a silly restriction like `C() { x = this.toString().length() + [0, 1] }`

That means the table is of sensible size, specifically of twice the size of the number of Exprs, with a row setting `x` to either the length of the stringified Expr, or that length plus one, like

```
| myvar | 5 |
| myvar | 6 |
| some + composite + expr | 23 |
| some + composite + expr | 24 |
```

Then the member predicates are just queries against that table, which perhaps explains why you can see different values from them -- I could write `int getStringifiedLength() { result = x }`, and for that `Expr` `myvar` it would give back both `5` and `6`. If I use two references to that member predicate, or two different member predicates, it's like querying the table twice, getting both results back each time -- so if I wrote `e.getStringifiedLength() + e.getStringifiedLength()`, for `myvar` I'd get all of `[10, 11, 12]` because each usage of `getStringifiedLength` is an independent query, not `[10, 12]` as you might suppose if you thought the two had to yield the same field value.

Member predicates _can_ constrain however-- I could do something like

```
int getStringifiedLengthIfEven() { result = x and x % 2 = 0 }
```

That's now only defined for even numbers, so I've filtered out some rows from the table of `Expr`s and corresponding `int`s.

I hope this exposition is of some use-- but like I say, if you can give a bit of information about what you're trying to achieve, I can probably recommend an alternative approach.

**Comment by cradiator** [comment]
Thanks for the explanation—it’s starting to make more sense why this limitation exists.

To clarify, here’s an example I’m trying to resolve:

```
#include <stdlib.h>

struct link_list {};
void link(struct link_list *header, struct link_list *l);
void unlink(struct link_list *l);

struct link_list header;
int foo() {
  struct link_list *list_foo = malloc(sizeof(struct link_list));
  struct link_list *list_bar = malloc(sizeof(struct link_list));

  link(&header, list_foo);
  link(&header, list_bar);

  // free without unlink
  free(list_foo);
  return 0;
}
```

In this code, I want to detect the pattern of calling ```free``` without calling ```unlink```. My expectation is that the query would alert only ```list_foo``` as matching this pattern. However, it currently also flags ```list_bar```, which was not freed.

I think the issue lies in ```isSink```, the field ```list``` doesn’t appear to be correctly bound to the ```list``` in ```isSource```.

```

class Flow extends ControlFlowReach {
  Variable list;

  Flow() { this = "Flow" }

  override predicate isSource(ControlFlowNode node) {
    exists(FunctionCall fc |
      fc.getTarget().hasName("link") and
      fc = node and
      list = fc.getArgument(1).(VariableAccess).getTarget()
    )
  }

  override predicate isSink(ControlFlowNode node) {
    exists(FunctionCall fc |
      fc.getTarget().hasName("free") and
      fc.getArgument(0).(VariableAccess).getTarget() = list and
      node = fc
    )
  }

  override predicate isBarrier(ControlFlowNode node) {
    exists(FunctionCall fc |
      fc.getTarget().hasName("unlink") and
      fc.getArgument(0).(VariableAccess).getTarget() = list and
      node = fc
    )
  }
}

from ControlFlowNode src, ControlFlowNode sink, Flow flow
where flow.reaches(src, sink)
select src, sink
```

**Comment by smowton** [comment]
Your problem is that in the predicate
```ql
  predicate reaches(ControlFlowNode src, ControlFlowNode snk) {
    isSource(src) and isSink(snk) and reach_internal(src, snk)
  }
```
then while the `this` of `isSource(src)` and `isSink(snk)` must be the same, the `list` can differ. That means we might be talking about `list_bar` for the source, but `list_foo` for the sink.

This can be seen most clearly if we pull the field and `this` out and make the predicates fully explicit:

```ql
FlowCharPred(Flow this_, Variable list) { this_ = "Flow" and list = any(Variable v) }

predicate isSource(Flow this_, Variable list, ControlFlowNode node) {
  exists(FunctionCall fc |
    fc.getTarget().hasName("link") and
    fc = node and
    list = fc.getArgument(1).(VariableAccess).getTarget()
  )  
}

/* and similarly isSink */

predicate reaches(Flow this_, ControlFlowNode src, ControlFlowNode snk) {
  isSource(this_, _, src) and isSink(this_, _, snk) and reach_internal(this_, src, snk)
}
```

So you see that in not binding the value of `list` in `reaches` references to `isSource` and `isSink`, we allow them to differ. Actually we should remove the field and instead make this a column of the isSource and isSink relations:

```ql
  predicate isSource(ControlFlowNode node, Variable list) {
    exists(FunctionCall fc |
      fc.getTarget().hasName("link") and
      fc = node and
      list = fc.getArgument(1).(VariableAccess).getTarget()
    )
  }

  /* and similarly isSink */

  predicate reaches(ControlFlowNode src, ControlFlowNode snk) {
    exists(Variable list | 
      isSource(src, list) and isSink(snk, list) and reach_internal(src, snk)
    )
  }
```

You can see there we've bound `list` to be the same for isSource and isSink.

While I'm here, one other remark about the code: `reach_internal` is defined for all control-flow nodes, not just those paths relating to a source/sink. Remember this is bottom-up programming: the CodeQL compiler _might_ notice that it is only used in a context where the end node matches `isSink`, but this isn't guaranteed. It would be better to manually constrain that `reach_internal` by adding `...and isSink(sink)`.

**Comment by cradiator** [comment]
1. Thank you for the detailed explanation on the differing values of list in isSource and isSink. I followed your advice and adjusted the code to accept list as a parameter in isSource/isSink. However, I opted to use a signature module instead of a base class since I want users to specify the field type, rather than binding it directly to Variable.

2. Also, thanks for the suggestion about adding isSink(sink) in reach_internal. I just wanted to confirm – is this primarily for performance considerations?

**Comment by smowton** [comment]
Yes, it's for performance-- there's nothing wrong with computing all paths in the whole program then restricting which ones you're interested in later, but it's better when practical to make the restriction explicitly and at the lowest-level predicate possible.
