### ISSUE TITLE
LGTM.com - false positive - (C#) Dereferenced variable may be null

### ISSUE THREAD

**Issue by kwokkan** [github/codeql#2485]
**(C#) Dereferenced variable may be null**

The code is wrapped around an `if (variable.HasValue)` so that it can never be null.

e.g.
```
  if (myVar.HasValue)
  {
      var obj = list.Where(x => x.Id == myVar.Value);  // <-- on myVar.Value
  }
```

https://lgtm.com/projects/g/kwokkan/card-hero/snapshot/6f790cc36322c7da5fb958d9a81de7d8e5a059bc/files/src/CardHero.Core.SqlServer/Services/GameService.cs?sort=name&dir=ASC&mode=heatmap#xce7673d1638704f0:1

**Comment by hvitved** [comment]
Thank you for reporting this. I agree that this is a false positive, and we will work on a fix. While it may look trivial, it is in fact a bit involved:

In the link you post, `userId` is a local scope variable (parameter) captured by the lambda expression `x => x.UserId == userId.Value`, and it is correct that `userId.Value` is guarded by the `null` check, but only because `SingleOrDefault` evaluates the lambda expression immediately. Here is another example where you actually do get a `NullReferenceException` (because of the lazy evaluation strategy of LINQ):
```
object M(object? x, IEnumerable<objects> xs)
{
    if (x.HasValue)
    {
        xs = xs.Where(y => y == x.Value); // x is not null-guarded
    }
    x = null;
    return xs.First(); // NullReferenceException when xs is non-empty
}
```
