### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by pkriens** [github/codeql#2996]
**Description of the false positive**
Report of unsanitized usage of Zip entry.getName used in toString

     public String toString() {
        return ":" + zip.getName() + "(" + entry.getName() + "):";
        | Unsanitized archive entry, which may contain '..', is used in a file system operation.
     }

The warning is clearly not true. The entry.getName() should clearly not be sanitized because it is used in a toString operation. Sanitizing would make diagnosing harder. Secondly, the entry.getName() is used in string concatenations that modify the name already significantly. The result can no longer be used in IO operations.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/bndtools/bnd/snapshot/34125c8a02ac25b5c16b4aa2f70c1116461e3b81/files/biz.aQute.bndlib/src/aQute/bnd/osgi/ZipResource.java?sort=name&dir=ASC&mode=heatmap#L78

**Comment by aschackmull** [comment]
Thank you for reporting this FP.  It looks like the main cause of this FP is the spurious dispatch in `Attrs.java` from `Map::put` to `PersistentMap.java`, which cannot happen.  I'll look into improving our type inference to see if we can rule out this dispatch - it ought to be possible, since it looks like the maps just get assigned through `private` method calls originating from either `Collections.emptyMap()` or standard hashmaps.

**Comment by pkriens** [comment]
Deeply impressed :-)

**Comment by pkriens** [comment]
I tried to fix it by cleaning up the PersistentMap code when it calculates the File object. It then cleans up the key for any dirty stuff. However, this seems not to be picked up.

**Comment by aschackmull** [comment]
Detecting code patterns that are valid sanitizers is generally tricky, and it's important not to be too general when designing such checks as it may lead to unfortunate false positives.  The ZipSlip query contains a few sanitizer patterns that are common for the use case of unpacking zip files, which is the usual context for the results of this query.  However, in your case sanitizing keys in PersistentMap is not likely to look the same as a normal ZipSlip sanitizer as the needs are a bit different, so it makes sense that we don't pick up on such sanitizer.

**Comment by pkriens** [comment]
I guess the use of Pattern upsets. You, tip what I could add to make it recognize. Name?

BTW thanks for this kind of support 👍 greatly appreciated.

**Comment by aschackmull** [comment]
Unfortunately, I don't think there's a good way of changing the code to avoid the alert, since as long as the maps in `Attrs.java` can't be given a more specific type than `Map<X, Y>` then it's hard to rule out dispatch to `PersistentMap`, which is the root of the problem.  As I mentioned above, the real fix is to improve our type inference in the QL libraries, but that's a long term thing, so for now I think the best suggestion I can give is to suppress the alert with an alert suppression comment.
