### ISSUE TITLE
Java: VariableAssign (LocalVariableDeclExpr) is not an Assignment

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#3266]
The `Assignment` class is described as:
> A common super-class that represents all varieties of assignments.

However, it appears that where a `VariableAssign` is initializing a local variable (and therefore is an instance of `LocalVariableDeclExpr`), it is not considered an `Assignment`.

Sorry if I am understand something wrong here, but this appears to be pretty irritating.

**Comment by aschackmull** [comment]
You are correct that `Assignment` only includes `AssignExpr` (like `x = y`) and `AssignOp` (like `x += y`), but neither variable initializations (like `int x = y`) nor unary updates (like `x++`).  This is the reason why the classes `VariableAssign` and `VariableUpdate` also exists, so that you should be able to pick the one that covers the cases you're interested in.  And if the subset of operations you're interested in isn't exactly covered by one of these, it's also easy to make your own class (see e.g. the definitions of `VariableAssign` and `VariableUpdate`).

**Comment by Marcono1234** [comment]
Thank you for the clarification. Would it be possible to clarify that in the `Assignment` doc then and possibly link to `VariableUpdate`?

>neither variable initializations

Field initializations are `Assignment`s, though I guess you only meant local variable initializations?

**Comment by aschackmull** [comment]
Yes, the doc could be a bit clearer.  Yes, I was just referring to local variables, the reason for field initializations being `Assignment`s is that those initializations happen inside the special object initializer method (or static initializer method for static fields).
