### ISSUE TITLE
LGTM.com - false positive C# string.format arguments missing on result of string lookup

### ISSUE THREAD

**Issue by gfs** [github/codeql#3355]
**Description of the false positive**

1. This code is marked as "The `format string` ignores `this supplied value`".
```csharp
violations.Add(string.Format(CultureInfo.InvariantCulture,
  Strings.Get("Err_ClauseDuplicateName"), rule.Name, duplicateClause.Key)); 
```
However, the result of `Strings.Get("Err_ClauseDuplicateName")` in this case does return a string with the appropriate number of fields. LGTM of course has no way to knowing that, so this rule should just not trigger if you have `string.format(f(x),args)` because Semmle doesn't know if there will ultimately be enough spots for arguments.

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/microsoft/AttackSurfaceAnalyzer/snapshot/39c6dd21e4c4528d449c65c9ddf890cac749883f/files/Lib/Utils/Analyzer.cs?sort=name&dir=ASC&mode=heatmap#x53edbeb4d58111:1

**Comment by hvitved** [comment]
Hi

Thanks for reporting this.

This one is tricky; the value `"Err_ClauseUnbalancedParentheses"` can in fact flow through [Strings.Get](https://lgtm.com/projects/g/microsoft/AttackSurfaceAnalyzer/snapshot/39c6dd21e4c4528d449c65c9ddf890cac749883f/files/Lib/Utils/Strings.cs?sort=name&dir=ASC&mode=heatmap#L25) (when `"Err_ClauseUnbalancedParentheses"` is not a key in the `stringList` dictionary), so that is why the alert is reported.

One possibility is to restrict the data flow analysis from string literals to `string.format()` by excluding steps through join-like program points (for example, methods with multiple `return`s or variables that can be assigned multiple values), but I will have to think about that a bit more.

**Comment by gfs** [comment]
Thanks for the response.

I forgot about that short circuit when the item isn't in the strings table - so it is ultimately possible for this string format to lose its arguments here. Maybe the right solution is to have the arguments in the placeholder string as well...

-------- Original Message --------

**Comment by gfs** [comment]
I'm going to address this in our code by adding the arguments into the label strings so the shortcut still preserves the arguments. https://github.com/microsoft/AttackSurfaceAnalyzer/issues/405

Now that I've thought about it more I think ultimately this is a good detection, but it would be nice to have more detail in the error about where the value that is flowing through and doesn't have the arguments is coming from.

**Comment by hvitved** [comment]
> it would be nice to have more detail in the error about where the value that is flowing through and doesn't have the arguments is coming from.

Indeed, I also thought about this, and I will convert queries like this one to [path queries](https://help.semmle.com/QL/learn-ql/writing-queries/path-queries.html), in order to visualize the flow.
