### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by robinwatts** [github/codeql#3433]
vsnprintf can permissibly return -1.

Ghostscript builds on pretty much every platform conceivable, including MSVC. MSVC can return -1 from vsnprintf, so the warning given by lgtm in this case may be right for most platforms, but it's not correct for all of them.

https://lgtm.com/projects/g/ArtifexSoftware/ghostpdl/snapshot/96ae683c865a3d503b1b53b649083d6eff06d35a/files/base/gsmisc.c?sort=name&dir=ASC&mode=heatmap#x7c9329ad07ab8d92:1

**Comment by jbj** [comment]
I don't think it's because we're making any assumptions about `vsnprintf`. It's instead about the complex rules for integer conversion in C.

With the types involved here, `count >= sizeof(buf)` is equivalent to `(size_t)count >= sizeof(buf)`. If `x` is a small negative `int`, it becomes a large positive `size_t` because `size_t` is unsigned. Therefore the `>=` is true when `count` is -1. The check for `count < 0` is then always false because a negative `count` has already been ruled out.

This is one of those alerts that might be technically correct but is not very helpful. To silence the alert, you can swap the two checks so the first check no longer makes the second one redundant:
```c
if (count < 0 || count >= sizeof(buf))  { /* MSVC || C99 */
```

**Comment by jbj** [comment]
I'll close this issue. Feel free to reopen if my answer doesn't address the issue.
