### ISSUE TITLE
[Java] Question on Overrides of Generic Methods

### ISSUE THREAD

**Issue by intrigus-lgtm** [github/codeql#3490]
**Description of the issue**
https://help.semmle.com/QL/learn-ql/java/types-class-hierarchy.html says:
> ````codeql
> /** class representing java.util.Collection.toArray(T[]) */
>class CollectionToArray extends Method {
>    CollectionToArray() {
>        this.getDeclaringType().hasQualifiedName("java.util", "Collection") and
>        this.hasName("toArray") and
>        this.getNumberOfParameters() = 1
>    }
>}
>
>/** class representing calls to java.util.Collection.toArray(T[]) */
>class CollectionToArrayCall extends MethodAccess {
>    CollectionToArrayCall() {
>        exists(CollectionToArray m |
>            this.getMethod().getSourceDeclaration().overrides*(m)
>        )
>    }
>
>    /** the call's actual return type, as determined from its argument */
>    Array getActualReturnType() {
>        result = this.getArgument(0).getType()
>    }
>}
>````
> Notice the use of getSourceDeclaration and overrides in the constructor of CollectionToArrayCall: we want to find calls to Collection.toArray **and to any method that overrides it**, as well as any parameterized instances of these methods. In our example above, for instance, the call l.toArray resolves to method toArray in the raw class ArrayList.

Running this simple [query](https://lgtm.com/query/2244911191724217613/) has zero results.
If the query is [modified](https://lgtm.com/query/5248413727332277574/) to not require that the method is declared in a specific type,
it has exactly one result in [UniquePropertyMessageEvictionStrategy.java](https://lgtm.com/projects/g/apache/activemq/snapshot/3aa6b8ab980b25550d4c6e5a845650e13ca23e98/files/activemq-broker/src/main/java/org/apache/activemq/broker/region/policy/UniquePropertyMessageEvictionStrategy.java?sort=name&dir=ASC&mode=heatmap#L73)

**Question:**
Why does the query, that requires the method to be declared in a specific type, not work?
If I understand the documentation correctly, this should work.
Am I misunderstanding what " **and to any method that overrides it**" means?

**Comment by aschackmull** [comment]
Thank you for finding this bug in the tutorial.  We'll get that fixed.  The TLDR of this is that you can use either `.overridesOrInstantiates*(m)` or `.getASourceOverriddenMethod*() = m` in place of `.overrides*(m)` for this to work properly.
The longer explanation of what goes wrong is this:
Consider a class `MyListCollection<E> implements Collection<List<E>>`.  In this class the method `MyListCollection<E>::toArray` overrides `Collection<List<E>>::toArray`, which is is an instantiation of `Collection<T>::toArray` (modelled here as the QL class `CollectionToArray`), so if we only look for straight overrides we won't reach `CollectionToArray`.  This example highlights the issue, but the same thing happens for all other subtypes of `Collection`.  Take for instance `List<E> extends Collection<E>`; again `List<E>::toArray` overrides `Collection<E>::toArray`, which isn't the same method as `Collection<T>::toArray` since one type variable is the one from the definition of `List` and the other is the one from the definition of `Collection`.  I've used the names `E` and `T` here to highlight the difference, but they could equally well both be named `T` without changing the issue.  With all this in mind we could also use yet another (slightly more verbose fix):
```
   CollectionToArrayCall() {
       exists(CollectionToArray m, Method overridden |
           this.getMethod().getSourceDeclaration().overrides*(overridden) and
           overridden.getSourceDeclaration() = m
       )
   }
```
