### ISSUE TITLE
LGTM.com - false positive - number of arguments/conditional compilation

### ISSUE THREAD

**Issue by samth** [github/codeql#3535]
**Description of the false positive**

The report says `This call has fewer arguments than required by GC_get_memory_use.` (0 are provided) but if you click on the function name in the alert, the prototype is:

```
size_t GC_get_memory_use()
```

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/racket/racket/snapshot/1d47c7950864497cd230b7d4e83ed8d8087596af/files/racket/src/racket/src/thread.c?sort=name&dir=ASC&mode=heatmap#x93334485044ffc1d:1

I think the problem is that the build compiles that file twice, with different preprocessor settings, and in one of them an argument is required. But that line is only compiled under the other setting.

**Comment by jbj** [comment]
Thank you for the report, and thanks for investigating the underlying cause.

I've opened https://github.com/github/codeql/pull/3554 to fix the problem.

**Comment by jbj** [comment]
The fix, #3554, is merged and should get deployed to lgtm.com within three weeks.

With or without the fix, I always recommend writing a prototype for your functions with a definite number of parameters. If you replace `size_t GC_get_memory_use();` with `size_t GC_get_memory_use(void);`, then it's an error to pass an argument to the function; otherwise arguments are permitted but ignored. In C++, the parameter list `()` means "no parameters", but in C it means "some number of parameters", and you have to write `(void)` to say "no parameters".
