### ISSUE TITLE
Java: Add FieldWrite.getRHS()

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#3606]
**Description of the issue**
It appears there is no easy way to get the value which is assigned by a `FieldWrite`.
Would it be possible to add a `FieldWrite.getRHS()` similar to `LValue.getRHS()`?

Or name it `getRhs()` or `getSource()` similar to `Assignment`'s predicates.

**Comment by adamlaska** [comment]
Hello

**Comment by aschackmull** [comment]
Adding `FieldWrite.getRhs()` sounds like a good idea.

**Comment by intrigus-lgtm** [comment]
Is setting a `Field` via reflection also considered a `FieldWrite`?
Or would it be wrong to define a class that extends `FieldWrite` that considers this special case?

If reflectively writing a field is also a `FieldWrite`, `getRHS` would be a bad name because `value` is not a right-hand side IMHO.
`theReflectedField.set(object, value)`

**Comment by aschackmull** [comment]
No, a `FieldWrite` is a fairly syntactic identification of `f = ...` and `f++` (and the other `++` and `--` variations).
