### ISSUE TITLE
Java: Clarify CompileTimeConstantExpr.getIntValue documentation

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#3632]
**Description of the issue**
The documentation for `CompileTimeConstantExpr.getIntValue` currently says:
https://github.com/github/codeql/blob/69ab1589104198701ccd7dd1bbc4997034d0973c/java/ql/src/semmle/code/java/Expr.qll#L308-L310

Which is rather confusing because in Java the result of `((byte)127)+((byte)1)` is an `int` and therefore 128 as well.

Are there actually cases where `getIntValue()` reports a different value than the correct one used within Java?

**Comment by aschackmull** [comment]
Well spotted. This example is indeed wrong for the reason you stated. I think `getIntValue()` will mostly report the correct value, but there are a few corner-cases where this isn't necessarily true. E.g. casts to `char` are not currently handled, so `(int)(char)65536` will yield `65536` instead of `0`.
