### ISSUE TITLE
Query runs slower after recent updates

### ISSUE THREAD

**Issue by saikatG** [github/codeql#3677]
Hi,

I am trying to run [this](https://github.com/shuvendu-lahiri/ql/blob/msr-propgraph/javascript/ql/src/PropagationGraph.ql) query on the eclipse_orion database downloaded from [here](https://lgtm.com/projects/g/eclipse/orion.client/ci/). However, after I merged with the latest codeql master branch, the query now takes >20minutes, instead of 2-3 minutes previously. This happens for both vscode plugin and the cli version.

Any ideas why? Please let me know if you need other info.

**Environment**
Windows 10
Codeql cli 2.2.0

P.S. I have already placed the database folder under exclusions in windows defender.

**Comment by max-schaefer** [comment]
It turns out there were two problems. The first was fixed by reverting a recent overly aggressive change, I don't think it had anything to do with merging in master. The second problem was an optimisation change that may well have been caused by changes in master, which I fixed as well. If you merge in my branch, you should hopefully get better performance.
