### ISSUE TITLE
LGTM.com - false positive: cs/useless-assignment-to-local when variable is a Func that is called

### ISSUE THREAD

**Issue by Nateowami** [github/codeql#3747]
When a function is assigned to a local variable and then called, LGTM reports that the assignment is useless because the variable is never read.

For example, in the C# code below `getCollection` is assigned and then called, which should count as being "read."

``` csharp
Func<T, IEnumerable<TItem>> getCollection = field.Compile();
IEnumerable<TItem> collection = getCollection(_entity);
```

Example where this is happening:
https://lgtm.com/projects/g/sillsdev/web-xforge/snapshot/f3b0c76c3301061b4cd5e9ac97d8e8fb7ee07db5/files/src/SIL.XForge/DataAccess/MemoryUpdateBuilder.cs#xccaf3ec2e56ca355:1

**Comment by hvitved** [comment]
Hi @Nateowami 

I agree that this is a false positive. However, it is caused by the fact that the analysis is [run in buildless mode](https://github.com/sillsdev/web-xforge/blob/master/lgtm.yml#L4), which can sometimes lead to inaccurate results as in this case. Is it possible for you to configure the project to run in build-mode instead?

**Comment by Nateowami** [comment]
@hvitved Thanks for your response. At the time we set it up there was some difficulty that prevented us from using build-mode, but I think that has changed. I'm checking whether we can switch to build-mode and will report back here once I find out.
