### ISSUE TITLE
Unexpected duplicate method

### ISSUE THREAD

**Issue by intrigus-lgtm** [github/codeql#3772]
**Description of the issue**
Hi while doing the 4th Java CTF "CodeQL and Chill" I noticed that trying to find all `isValid` method in `javax.validation.ConstraintValidator` resulted in two results although I only expected [one](https://docs.oracle.com/javaee/7/api/javax/validation/ConstraintValidator.html#isValid-T-javax.validation.ConstraintValidatorContext-).
The results also seem to be exactly the same in both cases, same arguments types, return types, and qualified name.

Why are there two methods instead of only one expected?
Is this due to synthetic bridge methods for Generics?
Link to Query:
https://lgtm.com/query/104938350722906404/

**Comment by aschackmull** [comment]
Looks like there's only one method, but for some reason it has two locations.  Your intuition about testing the various properties of the method in your linked query was good, but sometimes those entities that you select can have identical toString representations, so to really find out which of them has multiple values you'll have to use `count`: https://lgtm.com/query/4560532179237112722/

Now the next question is of course: why does a single method have two locations?  It really shouldn't, but sometimes various corner-case problems during extraction can cause this to happen.

**Comment by aschackmull** [comment]
Note that `select`ing an entity implicitly joins it with its `toString` representation and its location, so if any of those have multiple results it will look like there are more actual entities even though there aren't.

**Comment by Marcono1234** [comment]
It appears that the locations differ because the absolute paths of the files differ:
- `/opt/work/.gradle/caches/modules-2/files-2.1/javax.validation/validation-api/1.1.0.Final/8613ae82954779d518631e05daa73a6a954817d5/validation-api-1.1.0.Final.jar/javax/validation/ConstraintValidator.class`
- `/opt/work/.gradle/caches/modules-2/files-2.1/jakarta.validation/jakarta.validation-api/2.0.2/5eacc6522521f7eacb081f95cee1e231648461e7/jakarta.validation-api-2.0.2.jar/javax/validation/ConstraintValidator.class`

**Comment by intrigus-lgtm** [comment]
I guess this can be closed then :)
