### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by flok99** [github/codeql#3816]
"Resource th is acquired by class cleaner but not released anywhere in this class."

The resource is acquired when main invokes start on the cleaner class. It is released when main invokes stop on it. It always do so (check src/main.cpp for main()). Note that the helper function join_thread is used for it which can be found in src/exec.cpp

https://lgtm.com/projects/g/flok99/constatus/snapshot/588bdaead6294fc99fc160d9f5ccfd829304696e/files/src/cleaner.cpp?sort=name&dir=ASC&mode=heatmap#L34

**Comment by geoffw0** [comment]
This query is based on _Resource Acquisition is Initialization_ (RAII) philosophy and assumes that any resource acquired by a class method should be released in either (a) the same method or (b) the destructor (there are a couple of other special cases that probably aren't relevant to this discussion).  At present flagging the above result is expected, since it's acquired by the `cleaner` class but only released in `cleaner::stop()` .  This is not necessarily an error, but might be considered fragile code.  The "recommendation" section in the [help for this query](https://lgtm.com/rules/2162200684/) suggests putting a call to `cleaner::stop()` in the destructor.

Alternatively, if you don't agree with the RAII philosophy, it's probably sensible to disable this query on your project.  Just be sure to always check for control flow paths where the `stop` method might not be called.
