### ISSUE TITLE
Storage of Snapshot database

### ISSUE THREAD

**Issue by RickGY** [github/codeql#3959]
Hi, this is a general question about how the snapshot databases are stored in LGTM.

As the code evolves and multiple snapshots for the same project are created, does LGTM just store all the snapshot databases separately and as-is? Or do you perform some sort of optimization? For example, the storage might be "incremental", that is, you somehow only store what's changed in the new snapshot?

Thanks.

**Comment by aibaars** [comment]
LGTM only stores the latest snapshot database for each project, older snapshots are garbage collected. LGTM does, however, store the results of all analysis runs ever performed. That's why you can browse the source code and results of old commits in the history view of a project. These results are stored in an incremental way to save space.

**Comment by RickGY** [comment]
Thanks a lot for the info!
