### ISSUE TITLE
keyword "result" in codeQL

### ISSUE THREAD

**Issue by xsser** [github/codeql#4040]
I wanna know what does "result" mean in codeQL predicate .
Example code:

`MethodAccess getMethodAccess() { unsafeDeserialization(result, this.getExpr()) }`

or 

`Person getAChildOf(Person p) { p = getAParentOf(result)
}`

This result isn't been assinged any value.
I cannot get it , anyone knows that?Thank you !

**Comment by geoffw0** [comment]
You can think of `result` like a return value in other languages:
```
int myPredicate() { result = 4 }

select myPredicate() // 4
```
But because this is CodeQL, `result` doesn't *need* to be bound by assignment.  It does need to be bound, but a wide variety of expressions can do this, for example:
```
int myPredicate() { 100 = 40 + result }

select myPredicate() // 60
```
In your examples above `result` is bound by `unsafeDeserialization` and `getAParentOf` respectively, because they constrain the values that `result` can take (depending on the values of other variables `this` and `p`).

Another detail to be aware of is that like other variables in CodeQL, `result` can take multiple values (or no values), for example:
```
int myPredicate() { result = 4 or result = 5}

select myPredicate() // 4, 5
```

I hope this helps to clear it up.  It does take a bit of getting used to.  Happy to answer questions or talk through an example in more detail.

**Comment by xsser** [comment]
Thanks a million！
