### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by andersc** [github/codeql#4085]
**Description of the false positive**

LGTM states a variable ->
int64_t lCval = (int64_t) lChangeValue;
Comparison is always false because lCval <= 32767.
in the if ->
if (lCval > (int64_t)INT16_MAX) {

<img width="790" alt="image" src="https://user-images.githubusercontent.com/14168229/90335548-02220200-dfd6-11ea-8e00-03f2403f4fa6.png">

It's not true and the unit tests confirm that.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/Unit-X/efp/alerts/?mode=list

**Comment by intrigus-lgtm** [comment]
`lChangeValue` is of type `int16_t`.
So its range is [-32768, 32767]
This is then assigned to `lCval`.
So its range is also [-32768, 32767].

Now in your if clause you check whether `lCval` is bigger than (`>`) 32767 (INT16_MAX).
This can never be true, because the biggest value `lCval` can hold is 32767.

**Comment by andersc** [comment]
Corect. My fult.

Tnx for helping.

/A
