### ISSUE TITLE
[General issue] DataFlow::BarrierGuard not work in `Codeql for Java`

### ISSUE THREAD

**Issue by tutorial0** [github/codeql#4198]
I'm learning to write codeql rules by modifying your original rule. But i found something wrong in the `CWE-022` https://github.com/github/codeql/blob/768e5190a1c9d40a4acc7143c461c3b114e7fd59/java/ql/src/Security/CWE/CWE-022/TaintedPath.ql .
The main code for testing is:
```java
    @GetMapping("/path_traversal/sec")
    public String getImageSec(@RequestParam String filepath) throws Exception {
        if(filepath.contains("..")) {
            return "";
        }
        return getImgBase64(filepath);
    }

    private String getImgBase64(String imgFile) throws IOException {

        logger.info("Working directory: " + System.getProperty("user.dir"));
        logger.info("File path: " + imgFile);

        File f = new File(imgFile);
        if (f.exists() && !f.isDirectory()) {
            byte[] data = Files.readAllBytes(f.toPath());
            return new String(Base64.encodeBase64(data));
        } else {
            return "File doesn't exist or is not a file.";
        }
    }
```
This method `getImageSec` should be considered as not vulnerable of `Path-Injection`, but it's not. 
And the `DataFlow::BarrierGuard` didn't look like worked, nothing changes even if i turned this line https://github.com/github/codeql/blob/768e5190a1c9d40a4acc7143c461c3b114e7fd59/java/ql/src/Security/CWE/CWE-022/TaintedPath.ql#L28 's false to true.

So it's because of the way i use it or this is a bug of Codeql?

**Comment by aschackmull** [comment]
The query as-is should not give any results on the code you show. It's hard for me to guess exactly what goes wrong here, but here are a few suggestions for debugging this:
1. Have you made any modifications to the query or library that could cause this? Try running the out-of-the-box query.
2. Are you certain that the alert you find uses the path you expect? Inspect the path and verify that it passes through the `filepath` argument in the call to `getImgBase64`.

**Comment by tdifg** [comment]
I updated all the files to latest including the Codeql cli tool and the ql rules, but nothing improved.

I uploaded my test project here: https://github.com/tdifg/test4codeql
As you can see the method `getImageSec` should considered as not vulnerable of path-injection, because of the `SecurityUtil.pathFilter` method here:
https://github.com/tdifg/test4codeql/blob/master/src/main/java/org/joychou/controller/PathTraversal.java#L31
And the static method `SecurityUtil.pathFilter` come from here:
https://github.com/tdifg/test4codeql/blob/master/src/main/java/org/joychou/security/SecurityUtil.java#L178
It used the `contains` method with `..` to determine wether the `filepath` is tainted, all seemed fine.
But in the result file, it's still considered as vulnerable.
https://github.com/tdifg/test4codeql/blob/master/res.json#L528

**Comment by tdifg** [comment]
Or maybe it should be a false positive issue?

**Comment by aschackmull** [comment]
Ah, now things make more sense! Figuring out that `pathFilter` effectively checks `filepath.contains("..")` when used like this `SecurityUtil.pathFilter(filepath) == null` is a lot harder to analyse than the code snippet you posted above, which directly checks `filepath.contains("..")`.  So the code you originally posted would not have any alert, whereas the more complicated code in https://github.com/tdifg/test4codeql/blob/master/src/main/java/org/joychou/controller/PathTraversal.java#L31 indeed suffers from a false positive.
So the `BarrierGuard` as-is works just fine - it's just simply not trying to model this more complex scenario.  It is of course possible to extend the query to catch more checks like this and avoid the FP, but unfortunately this isn't likely to be something we can prioritise in the near future.

**Comment by tdifg** [comment]
> So the `BarrierGuard` as-is works just fine - it's just simply not trying to model this more complex scenario. It is of course possible to extend the query to catch more checks like this and avoid the FP, but unfortunately this isn't likely to be something we can prioritise in the near future.

Could you please explain why the `BarrierGuard` is not working for this scenario?

**Comment by aschackmull** [comment]
The `BarrierGuard` is just a convenience wrapper that makes it easier to define barrier/sanitizer nodes, i.e. dataflow nodes that don't permit flow to pass through. In the code snippet
```
if(filepath.contains("..")) {
     return "";
}
return getImgBase64(filepath);
```
it marks the `filepath` variable access in `getImgBase64(filepath)` as a barrier, which means that this node isn't allowed to be a part of the dataflow graph, which effectively removes any possible flow path.
In the more complex case:
```
public String getImageSec(String filepath) throws IOException {
        if (SecurityUtil.pathFilter(filepath) == null) {
            logger.info("Illegal file path: " + filepath);
            return "Bad boy. Illegal file path.";
        }
        return getImgBase64(filepath);
    }
```
flow steps from the parameter `filepath` to the `filepath` variable access in `SecurityUtil.pathFilter(filepath)` to the `filepath` variable access in `getImgBase64(filepath)` completely unimpeded (and further into the `getImgBase64` method).  So in order to fix this FP we would need to identify `SecurityUtil.pathFilter(filepath) == null` as a `BarrierGuard`, which would cause the subsequent `filepath` variable access to become a barrier node, and thus block the flow. Doing this would involve a preliminary analysis to identify `pathFilter` as a method that performs such checks that allows us to conclude that the call to it acts as a suitable sanitizing check. An ad-hoc solution that could very well be good enough is to drop precise analysis of the conditions on the return value of `pathFilter` and identify it based on much looser checks like this:
```
predicate maybeSanitizer(Method m) {
  exists(MethodAccess ma |
    ma.getMethod().hasName("contains") and
    ma.getAnArgument().(StringLiteral).getValue() = ".." and
    ma.getEnclosingCallable() = m
  )
}

...

override predicate isSanitizer(DataFlow::Node n) {
  maybeSanitizer(n.asExpr().(Argument).getCall().getCallee())
}
```
