### ISSUE TITLE
Scala Compatibility

### ISSUE THREAD

**Issue by callicles** [github/codeql#4365]
Hi all!

Not sure how you are determining which language support gets built next, but I would love to see some scala / sbt support happen since this is what my organization is using in the backend.

Thank you!

**Comment by laughedelic** [comment]
@sj hi! Could you share any plans on the subject? Is Scala support anywhere on the roadmap?

Also, I don't know if this makes sense, but if CodeQL supports Java and Kotlin, does it mean that we could produce class files from Scala with some instrumentation and feed it to CodeQL?

**Comment by smowton** [comment]
Kotlin support doesn't help in this respect because we're analysing Kotlin via a source-level compiler plugin, not by analysing the class files it generates. IIRC there actually used to be Scala support, though I don't know exactly why it got dropped.

**Comment by sj** [comment]
At the moment, Scala support is indeed not on [the roadmap](https://github.com/orgs/github/projects/4247/views/1?filterQuery=label%3A%22github+advanced+security%22+label%3Acodeql). It's also not on the top-10 of [most popular languages](https://octoverse.github.com/#top-languages-over-the-years), nor is its use currently growing particularly rapidly relative to other languages. If/when that changes, we'll make sure to revisit/reopen this issue and provide a link to the roadmap item!

And indeed, like @smowton points out: CodeQL very much operates on abstractions of source code, rather than on bytecode.

**Comment by laughedelic** [comment]
This is sad news, but it's good to get an official response and clarity on the plans. Thanks!

**Comment by uri-peled-unit** [comment]
Any news about it ?
