### ISSUE TITLE
LGTM.com - false positive - js/xss-through-exception

### ISSUE THREAD

**Issue by Siilwyn** [github/codeql#4390]
An error message is being passed from a Node.js server and I get the error in LGTM that an exception text is reinterpreted as HTML without escaping meta-characters.

Since the error message doesn't come from the user but is just [a string in the server code](https://lgtm.com/projects/g/Siilwyn/cheers-receiver/snapshot/a764a4244b7e47b49b3ca8c750606c197e37a969/files/src/main.js#L19) there is no way this can be used for XSS.

https://lgtm.com/projects/g/Siilwyn/cheers-receiver/snapshot/a764a4244b7e47b49b3ca8c750606c197e37a969/files/src/server.js?sort=name&dir=ASC&mode=heatmap#x571102ff03d0109e:1

**Comment by erik-krogh** [comment]
I think the error message the query is worried about is an error message that could arise from [this call to `db.get(key)`](https://lgtm.com/projects/g/Siilwyn/cheers-receiver/snapshot/a764a4244b7e47b49b3ca8c750606c197e37a969/files/src/main.js?sort=name&dir=ASC&mode=heatmap#L24).

**Comment by Siilwyn** [comment]
Good catch, I feel like I'm missing something though... there is no way the use can influence this afaik? Looking at the LevelDB errors I am not sure though. Either way I've changed it for good measure.

**Comment by erik-krogh** [comment]
> Good catch, I feel like I'm missing something though... there is no way the use can influence this afaik? Looking at the LevelDB errors I am not sure though. Either way I've changed it for good measure.

You are not necessarily missing anything.   
The `js/xss-through-exception` query is not perfect - the query will often assume that a function could potentially throw an exception based on some parameter value, and sometimes that assumption is wrong.   
It is hard to do better - because we can't have perfect knowledge about every JavaScript library - so it will have to do.   
That imperfect knowledge is also a reason for the query producing `warnings` instead of `errors`. 

But I'm not sure that assumption is wrong in this case, because I think [`this throw statement`](https://lgtm.com/projects/g/Siilwyn/cheers-receiver/snapshot/a764a4244b7e47b49b3ca8c750606c197e37a969/files/src/main.js?sort=name&dir=ASC&mode=heatmap#L28) can throw to the relevant `catch`-statement, and I think it is reasonable to assume that the `error` thrown might contain `key`.
