### ISSUE TITLE
Error running query in CLI. Works in VSCode

### ISSUE THREAD

**Issue by marcinguy** [github/codeql#4454]
Have a query that works in VSCode, but when running from CLI errors out. Problem kind and metadata is there. Any ideas? Error "Shutting down query evaluator.
Interpreting results.
A fatal error occurred: Could not process query metadata.
Error was: Expected result pattern(s) are not present for query kind "Problem"(INVALID_RESULT_PATTERNS)."

**Comment by aibaars** [comment]
The `INVALID_RESULT_PATTERNS` error is because the query selects columns of the wrong type or because it select the wrong number of columns.

A query with `@kind` problem needs to select an alert location (e.g a program element) and an alert message (a string). 

If the alert message contains placeholders (`$@`) then the query should select additional pairs of values for each placeholder. Each pair is a link target (e.g another program element) and a link text (string).

**Comment by marcinguy** [comment]
@aibaars Thanks. Not at computer now. Tried to fix it adding program element and string. But no luck. 

Here is the query in question:

https://github.com/assafsion/DangerousMemcpy/blob/master/Dangerous_Memcopy/dangerousMemcpy.ql

How to fix it that it works in CLI then?

Thanks

**Comment by aibaars** [comment]
I put your query in the query console of LGTM.com: https://lgtm.com/query/3905475207061098524/ . Note that I concatenated all the QLL files because the LGTM query console only supports a single text box. I also added some basic metadata at the top.

As you can see LGTM has a warning on this line: 
```
select memcpy.getLocation(),  memcpy.getMemcpyLengthVars()
``` 
It complains that `memcpy.getMemcpyLengthVars()` is not a string. The second value should be a message, but `memcpy.getMemcpyLengthVars()` has type `VariableAccess` . Also note that you don't have to call `getLocation` , the first column can simply be `memcpy` which is a program element.

**Comment by marcinguy** [comment]
@aibaars wow great! Lgtm editor seems nice
So I will change to:

select memcpy.getLocation(), "bug" 

Or 

Select memcpy, "bug" 

And it should work

**Comment by aibaars** [comment]
Yes that's right. There is an issue to add the addional checks to vscode https://github.com/github/vscode-codeql/issues/397

**Comment by RasmusWL** [comment]
This seems to be solved, so closing down the issue :blush:
