### ISSUE TITLE
LGTM.com - false positive, rule 7900088

### ISSUE THREAD

**Issue by vladimiry** [github/codeql#4463]
**Description of the false positive**

https://lgtm.com/projects/g/vladimiry/ElectronMail/snapshot/4215136735547fdccfae85101a9557dbd96d4608/files/src/electron-main/storage-upgrade.ts?sort=name&dir=ASC&mode=heatmap#L519

The `exclusiveProp` value used for `typeof` purpose.

**Comment by erik-krogh** [comment]
The alert message isn't the best, but it does not look like a false positive to me. 

It looks to me like you are creating a value whose only purpose is to be used within a type.  
So the value of `exclusiveProp` is never used at runtime, and that is what the query is complaining about (even though the alert message isn't the best). 

You could avoid creating the value altogether if you keep `exclusiveProp` as a type instead of as a value. 

One way to do that is to change those two lines to: 

```TypeScript
type exclusiveProp = typeof folderPropsToRemove[2];
(folder as Mutable<Pick<typeof folder, "type">>).type = (folder as Pick<Partial<{[s: string]: NumericBoolean;}>, exclusiveProp>).exclusive === 1
```

[Here is a TypeScript playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBGBOD2YDOAVcElQLxQNoCIAzeefAGinwCMBDWcy2gL3wF0BuAKAgA8x5YwKKEhQAcgFcAthFgBLAMYAhEgBsINAHbYoABigAfKAEYunTgHoLUFAAtoAdxogoc4JgAm8TdAUTYsBCawKogAHRQnAreSEJwiABqNKoS0ABcMAjIaJBIuABMrDrUNCxcItAVAGIIUgAKWUkp0DgA3rjxYE2prAD8GZIy8spqGpoAvmZWUACSmrEaHhkAwjFyHrJQXnKaAOauQgBWErFQDm62wuhIGZwVmYg5LQ-Z1wUcd+hXkDXwUk8NRA6OqKADWAB46nRgHJkuD2jcoLF5HtWANpLJFCp4OotOxxgA+CidJ4E8yWawzXaaASVexICAUY6nYDwKBSGigum+ewKLmwKC2GhgMDhKIxITEVQbWCA7LwABKECk8AAbs8CFKZU8GPgOXJVFUcTKZh5dbwFCkkHJ1WwoDRMNF5sAuBtLXRoKq6FAtbIMloQK6IO7AlAvQKADIAQSUAFEIwB9FAATTqsag-s0gc+ogAshJgDQqOpwSgCToA2YKTZ7GdnAdPN5fP5AsFQhFOHJCFAABQAQmjccTKbTYQTYTkSCa626EB7vtgYQqAEpl1BWpwoFuoE7TharTaIHKMhV4N2F3LUIrlWqIO9ivuTof8Fxt72F-bMPnC8WIJCweCp7nsasgUPgFT4ASBLLkuXw4POIECg6654I+1rqnKfTokMWKjFoUDjDBaGHtgWA4MYm5vtuvRQIO8ZJqmsZhLmsYAMqsVGADisYJlUADyEYACKxgqlFURmtExvRI5MSx7FcTxdERlw4zmNMqwSNKUBUDyWi7BAHjCGywC2JORlbGybhQN4oRQE+ezfBgtxdr2A5ScOjFjhOU7JDOySpAh0qyLBkCruuYmOVAxEYVkOhAT6iGXig14quq7yvtugUyp+UDfkWJYgnygHoGeCVBbAYEQVBMH3PBH7IYVEJQoIsKqPCuCIsiOy7Gi4gYsM2K4po+JElFPCWk+MWINBYTRS0ZEmBFb40UpDGjnJHHcbxAnCaJ4lbhkq0ycxbGbYp7kqZwQA) where I played around with how to keep `exclusiveProp` as a type.

**Comment by vladimiry** [comment]
Correct, the `exclusiveProp` value is not used in runtime but only for typing purposes. I commuted out some code and missed simplifying the remaining things.

> (folder as Pick<Partial<{[s: string]: NumericBoolean;}>, exclusiveProp>)

I think I will just end up with `(folder as { exclusive?: NumericBoolean })`.
