### ISSUE TITLE
General issue - Entry point of Python pointer analysis

### ISSUE THREAD

**Issue by MugenU** [github/codeql#4572]
Hi! I just started to use codeql on some Python projects and I'm interested in the implementation of the pointer analysis. 

I want to know whether there is a way that I can specify the entry point of pointer analysis. And if no entry has been given, how does codeql decide the default entry, where will the analysis start? In my opinion, other programming languages such as Java or C always have a main entry. But for a Python project such as flask, where should be its entry?

I'm trying to read the source code but it's too difficult for me. Could you please give me an explanation, thanks!

**Comment by tausbn** [comment]
By default (and this is not really easily modifiable), the main entry for the analysis is the beginning of each given file. For non-modules (e.g. a script of some sort), this is the usual way execution works in Python, and we just follow this control flow for the points-to analysis.

For modules, it's exactly the same, although we do keep track of the fact that this "execution" is happening at import time, rather than at runtime. For each module that is included in the snapshot, we analyse it as if it was imported, again by following the control flow graph for the module. Whenever parts of the module are called, we will then potentially analyse the relevant bits again, but this time not in the import context (most likely in the context of a call to a specific function/class of the module).

So for the most part, it shouldn't be necessary to explicitly specify the entry point for a module. It'll just happen automatically if the module is imported. (Of course, the module has to be _extracted_ as well, otherwise there's no source code to analyse!)

**Comment by MugenU** [comment]
Thanks for your reply!
