### ISSUE TITLE
codeql for LGTM not reporting memory not free alerts?

### ISSUE THREAD

**Issue by tim-rj** [github/codeql#4625]
**Description of the issue**

I just do an experiment, remove free() from my code, but lgtm for pull do not report this alert at all, and i also directly run MemoryNeverFreed.ql, it does report, so my question is why lgtm suits do not include such an important query?
https://lgtm.com/projects/g/shaoshouping/ssh2com/rev/pr-9eb9ddd801f2684a551a08c58451814bcdfef1cf

**Comment by geoffw0** [comment]
Hi,

The MemoryNeverFreed.ql query uses MemoryFreed.qll which imports `semmle.code.cpp.pointsto.PointsTo`.  This is an old library that we're trying to phase out in favour of newer dataflow libraries (that are more flexible and often perform better).  I can't make a commitment but I hope we'll get around to modernizing this query soon, and then enable it by default.

In your case the results for MemoryNeverFreed.ql are not very useful because the main result is in `fxgl_session_malloc` itself, rather than at each call to that function.  I believe MemoryMayNotBeFreed.ql does a better job of recognizing these kinds of situation.
