### ISSUE TITLE
LGTM.com - false positive (existing alert for removed file)

### ISSUE THREAD

**Issue by zak-pawel** [github/codeql#4714]
**Description of the false positive**

Alert shows two problems with `scripts/build.py` file which was removed from repo over 4 months ago.
Commit with file removal: https://github.com/influxdata/telegraf/commit/b6560c8b01a79a5c16526db24e1ecd7f050ba289#diff-c786cc346fc8fdc17f1c85f11bc187c153a3511ae549390185c7c39343d2c95d
Here we can see that there is not `build.py` in `scripts` directory: https://github.com/influxdata/telegraf/tree/master/scripts

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/influxdata/telegraf/snapshot/5d72b98ccabaf56bbc133bdfb8414fa991810634/files/scripts/build.py?sort=name&dir=ASC&mode=list#x773c2da4e2ddc3c6:1

**Comment by tausbn** [comment]
My best guess here is that the build has been failing for Python for at least the past 4 months. One reason for this might be that there currently is _no_ Python code in the repository, as the extractor fails when there is no relevant code present. 

As there isn't any way to remove a language once it's been added, my best suggestion for how to remove the alerts would be to add an empty `scripts/build.py` to the repo, so that it can build successfully. The alerts should then disappear. 

(Afterwards you can remove the file again, which will cause the builds to fail again, but at least the alerts won't be shown any more.)

**Comment by zak-pawel** [comment]
@tausbn You are right, there is no Python code in the repository any more.

**Comment by ssoroka** [comment]
would be great if we could tell LGTM to ignore specific languages, folders, and/or files. to resolve this.

**Comment by zak-pawel** [comment]
Not valid anymore (lgtm.com deprecated).
