### ISSUE TITLE
codeql error occurred durint initializationtion of VM

### ISSUE THREAD

**Issue by madneal** [github/codeql#4826]
**Description of the issue**

The pc in windows 10. Afete extract the codeql-cli to codeql-home, and add codeql to path. It's impossible to execute codeql. The jdk of the PC is jdk 1.8. I'm not sure if it's related.

![image](https://user-images.githubusercontent.com/12164075/102178198-f7be3900-3edf-11eb-92da-4df50d8cd45f.png)

**Comment by aibaars** [comment]
Hi @madneal . Thanks for reporting this. CodeQL contains two small Java Runtime Environments. One for running CodeQL and one used by the Java extractor. It looks like both are failing in a similar way. The stack traces indicate that the JVM somehow fails to initialize its system properties (such as file.encoding which defines the default character encoding).

I'll pass your report on to the CodeQL team. If you have time it would be great if you could try out the following.

Could you try to download a JDK version > 11 and see if it runs on your machine? In the unlikely case that it doesn't, then there is something strange going on with your machine. If it works fine, then we probably missed out some component when creating the minimal JREs that are bundled with CodeQL.

If the JDK > 11 works on your machine you could try the following workarounds:
* Set the CODEQL_JAVA_HOME environment variable to the folder where you installed the JDK > 11. This environment variable tells CodeQL to use the specified JRE instead of the one in `codeql/tools/windows64/java` .
*  To analyse Java code you'd also need to copy the downloaded JDK to the `jdk-extractor-java` folder.

**Comment by madneal** [comment]
@aibaars  Thanks for your reply. But I'm confused why the JDK should be larger than 11. Because as I have see the jdk version of codeql which works fine in my mac is 1.8.

![image](https://user-images.githubusercontent.com/12164075/102192708-16c7c580-3ef6-11eb-8f69-347131e0fe8a.png)

And I will have a try of jdk > 11

**Comment by aibaars** [comment]
> @aibaars Thanks for your reply. But I'm confused why the JDK should be larger than 11. Because as I have see the jdk version of codeql which works fine in my mac is 1.8.
> 
> ![image](https://user-images.githubusercontent.com/12164075/102192708-16c7c580-3ef6-11eb-8f69-347131e0fe8a.png)
> 
> And I will have a try of jdk > 11

Note that on OSX you need to write `./java` to run the `java` binary found in the current directory.

**Comment by madneal** [comment]
@aibaars Get it. I will have a try.

**Comment by madneal** [comment]
@aibaars I have tried jdk14. It failed with the same message. Thanks for your reply. I would figure out why the PC cannot work lager version JDK.

**Comment by aibaars** [comment]
This seems related: https://stackoverflow.com/questions/61650372/jdk-14-0-1-error-occurred-during-initialization-of-vm-java-lang-nullpointerexcep

**Comment by madneal** [comment]
I have googled the same result. But it does not work for me. As the beta option is already unchecked.

**Comment by madneal** [comment]
@aibaars I fixed this issue. I try openjdk 14 instead of oracle jdk. It works.
