### ISSUE TITLE
Error: Could not resolve type CallAllocationExpr

### ISSUE THREAD

**Issue by Phantomn** [github/codeql#4836]
**Description of the issue**
Could not resolve type CallAllocationExpr

import cpp
import semmle.code.cpp.models.Allocation

from **CallAllocationExpr alloc**

This module exists but "CallAllocationExpr" is not loaded. how to solve it?

**Comment by MathiasVP** [comment]
Hi @Phantomn,

The `CallAllocationExpr` class is a private class found in `semmle.code.cpp.models.implementations.Allocation`. Hopefully, the public classes `AllocationExpr` and `AllocationFunction` from `semmle.code.cpp.models.interfaces.Allocation` will be useful to you, instead.

If you have a good use-case that requires a specific implementation class (in this case `CallAllocationExpr`) instead of the public classes found in `semmle.code.cpp.models.interfaces` we'd be really interested in hearing about it!

**Comment by Phantomn** [comment]
Thank you @MathiasVP but one more question.
**getAnArgument() of CallAllocation Expr** is not exist Allocation and AllocationFunction.
hot to use **getAnArgument()**?

**Comment by MathiasVP** [comment]
Looks like that article was written before a recent change in how we interact with modeled functions. This rewrite should preserve the intended behavior of the query from Figure 11.

```codeql
import cpp
import semmle.code.cpp.models.Models
import semmle.code.cpp.dataflow.TaintTracking

// AllocationExpr represent a call to malloc/calloc/realloc/etc./custom wrappers
from AllocationExpr alloc, Expr memcpy_dst, FunctionCall memcpy, Expr size
where
  // Setting memcpy, memcpy_dst
  memcpy.getTarget().hasName("memcpy") and
  memcpy_dst = memcpy.getArgument(0) and
  // Every allocation that flows to the 1st arguemnt in a memcpy call
  TaintTracking::localExprTaint(alloc, memcpy_dst) and
  // malloc(a * b) => size = a || size = b
  size = alloc.getSizeExpr().getAChild*() and
  // malloc(a * 5) => size = a || size = 5, the number 5 is not a variable!
  if exists(VariableAccess va | size = va)
  then isNumber(size.(VariableAccess).getTarget())
  else size = size
select memcpy.getLocation() as memcpy_location, alloc.getLocation() as allocation_location, size
```

I've kept as much of the original code as possible. The only real change is:
- Make `alloc` an instance of `AllocationExpr`
- Use the `getSizeExpr` member predicate of that class instead of `getAnArgument`.

Hope that helps!

**Comment by Phantomn** [comment]
Thank you Very Sooooooooooooooooooooo much!!!
