### ISSUE TITLE
False positive "Reflected cross-site scripting"

### ISSUE THREAD

**Issue by yurishkuro** [github/codeql#4853]
**Description of the false positive**

https://github.com/jaegertracing/jaeger/security/code-scanning/5?query=ref%3Arefs%2Fpull%2F2697%2Fmerge

![image](https://user-images.githubusercontent.com/3523016/102720013-90c5c900-42bf-11eb-95bc-a302faa32d51.png)

The `err` variable is not an input parameter. I've looked through a number of paths where it is generated, such as various Read() functions, and it never includes the portions of the input.

**Comment by smowton** [comment]
For the record, looks like this came from assuming that `json.Unmarshal` may quote parts of the input in an error report, which I think is wise even though it currently seems to only quote a single character. The project seems to have been modified since this report to cautiously sanitise the `err` value, which I think is also wise.
