### ISSUE TITLE
LGTM.com - false positive: loop variable claimed not in use

### ISSUE THREAD

**Issue by berland** [github/codeql#4876]
**LGTM claims a for-loop variable is not in use, when it is**

The loop variable `root` in the linked URL is claimed by LGTM to not be used, while it is in use.

https://lgtm.com/projects/g/equinor/ecl2df/snapshot/ad5967c89632324e25de2dc55795b1c7e6757c87/files/ecl2df/gruptree.py?sort=name&dir=ASC&mode=heatmap#x1aa01509fdceea25:1

**Comment by tausbn** [comment]
Thank you for your report!

I'm not convinced this is a false positive, since the two occurrences of `root` inside the loop are bound in the dictionary comprehension in which they occur. To translate into a self-contained example, consider the following piece of code (syntactically similar to the code you link to):
```py
stuff = []
strings = ["foo", "bar", "baz"]
for x in list(strings):
    stuff.append({x: x.upper() for x in strings})
print(stuff)
```
This prints
```py
[{'foo': 'FOO', 'bar': 'BAR', 'baz': 'BAZ'}, {'foo': 'FOO', 'bar': 'BAR', 'baz': 'BAZ'}, {'foo': 'FOO', 'bar': 'BAR', 'baz': 'BAZ'}]
```
but so does 
```py
stuff = []
strings = ["foo", "bar", "baz"]
for unused_var in list(strings):
    stuff.append({x: x.upper() for x in strings})
print(stuff)
```
which shows that the outer loop variable is indeed unused.

I hope this clears everything up! :slightly_smiling_face:

**Comment by berland** [comment]
Thanks for clearing it up, I see it now!
