### ISSUE TITLE
Queries and Code in the Same Repo

### ISSUE THREAD

**Issue by mrthankyou** [github/codeql#4908]
What are the team's reasons for having queries and the actual CodeQL code inside a single repo? A part of me wishes that they were separate repositories since one piece is the actual code-source and the second is implementations of the code-source.

I appreciate all the work you guys do and am excited about working on this project! 

PS: Didn't mean this to be a complaint, just curious as to why it was done this way.

**Comment by tausbn** [comment]
I'm not sure I entirely I understand your question, but I'll try to answer it anyway. :slightly_smiling_face: 

If you're asking why the queries and libraries are in the same repo, then this is simple: a change in a library might require simultaneous changes to one or more queries in order to ensure that everything continues to function as intended (and in particular to ensure that the tests still pass!). Having the queries separate from the libraries would make this awkward. 

(Also, I should add that the distinction between queries and libraries is fairly shallow. Queries permit a slightly more user-friendly syntax for specifying what results to select, but apart from that the language is exactly the same.)

If you're asking why the queries/libraries are in the same repo as (some of) the extractors (as is the case for, say, C# and JavaScript) then the answer is similar: on occasion it is necessary to change the representation used for the databases created during extraction. In this case, changes to the libraries are usually also needed, and it would again be awkward to _not_ be able to do this in a single operation.

If you're asking why the queries/libraries are in the same repo as the CodeQL _engine_, then... I'm afraid I can't answer this question, since this is not actually the case! The CodeQL engine is currently closed source, and lives in a separate repo.

I hope this answers your question. :slightly_smiling_face:

**Comment by mrthankyou** [comment]
Answered my question! Thanks for the detailed response. I learned something new today! I'm happy to close this issue if you are.
