### ISSUE TITLE
Issue with detecting Enclosing callable of java expressions

### ISSUE THREAD

**Issue by SaumoPal97** [github/codeql#4966]
Given the following code:

```
public EngagementDetails getGliaEngagementDetails(final String EngagementId, final String visitorId, final String operatorId, final String siteId) throws Exception {
    CompletableFuture<List<ChatTranscript>> engagementChatTranscriptResponse = CompletableFuture.supplyAsync(() -> 
    getEngagementChatTranscript(httpEntity, uriParams)).exceptionally(exception -> {
    bffAppMapMessage.put("GetEngagementChatTranscript.Exception", "CompletedExceptionally");
    log.error("Exception while GetChatTranscript: {}", bffAppMapMessage, exception);
    return Collections.EMPTY_LIST;
});
}
}
```

I am interested in finding out all enclosing callables of `getEngagementChatTranscript()` recursively by sending `getEnclosingCallable()` of the aforementioned function to the following CodeQL function:

```
Method recursion(Method M) {
    result = M.getAReference().getEnclosingCallable()
}
```
I am able to get the immediate enclosing callable of `getEngagementChatTranscript()` inside the Java Expression of the first line in the function, but for the Java expression `() -> ...`, I am unable to find its enclosing callable, which should ideally be `getGliaEngagementDetails()`. I wanted to know how I can find that using CodeQL, and also if there is any mistake in using the above recursive logic. Thank you!

**Comment by SaumoPal97** [comment]
I just found out that Java Expressions `() -> ...` or lambdas do not have a `getAReference()` so by using the following recursive function
```
Method recursion(Method M){
    result = M.getEnclosingCallable()
    or
    result = M.getAReference().getEnclosingCallable()
}
``` 
I do get the `getGliaEngagementDetails()` as one enclosing callable of the lambda function which calls the original `getEngagementChatTranscript()`, which I was looking for. Any reason why lambda functions don't have a `getAReference()`?

**Comment by aschackmull** [comment]
First, remember that any method call has two kinds of dispatch targets: the static target, aka compile-time dispatch target, which is what you can expect to jump to if you do something like jump-to-def in your favourite IDE. There's also the dynamic dispatch target(s), which are the actual methods that the call will reach when executed at runtime. As an example, a call on an interface type will have the interface-method as its static target and the implementing method in some class as its dynamic target.

The `Method.getAReference` gets you a call to the given method, i.e. a call where the static dispatch target is the given method. Lambdas don't have names so there's no way to write a call with a static target being a specific lambda, they are instead always called through some interface where the lambda will end up as the dynamic target (which lambda ends up being called at a specific call site might not be something that can be calculated up front). So this should hopefully answer your question.

Additionally, in your case you're not actually looking for the enclosing callable of some call to the lambda, but rather the enclosing callable of the lambda itself, which is why your QL has to be this way, since your Java code snippet doesn't actually contain any call that could even dynamically dispatch to the lambda (that call is hidden somewhere inside the machinery of `CompletableFuture`).

(Slight nitpick: I understand what you mean when you say that your QL predicate `Method recursion(Method M)` is recursive, but technically that's a wrong statement, as it doesn't actually reference itself. A QL predicate is recursive if it calls itself - either directly or through a sequence of other predicates).

**Comment by SaumoPal97** [comment]
Yes, that answers my question. Also you are correct about the recursion part, its used in the code recursively but the function itself isn't a recursion. Thanks for the pointer @aschackmull
