### ISSUE TITLE
LGTM.com - false positive - python unused local variable

### ISSUE THREAD

**Issue by LefterisJP** [github/codeql#4983]
**Description of the false positive**

https://lgtm.com/projects/g/rotki/rotki/snapshot/884280be7efa9e5da14a3607ef5f26297db5dd20/files/rotkehlchen/history/events.py?sort=name&dir=ASC&mode=heatmap#x360fd1298e981df3:1

The local variable is used, inside the self method

**Comment by tausbn** [comment]
Thank you for your report! 

The local variable that is being referred to is the one on the left hand side of the assignment, and as far as I can tell it is not referenced again in the remainder of the `get_history` method. As such, it is superfluous, and you could just as easily write
```py
self._increase_progress(step, total_steps)
```
instead of the current
```py
step = self._increase_progress(step, total_steps)
```
There should be no difference in behaviour.

**Comment by LefterisJP** [comment]
Hey @tausbn I think you may be right in this one. I will try to remove the ignore of the warning I added, apply your suggestion and see if LGTM complains again or not.

I made this issue with the assumption it was the right hand side. Apologies for this. If I can confirm my mistake I will close the issue.

**Comment by LefterisJP** [comment]
yeah that was it. Thank you.
