### ISSUE TITLE
Is there a way to process Lombok-ed source file in codeql

### ISSUE THREAD

**Issue by hatface** [github/codeql#4984]
**Description of the issue**

Is there a way to process Lombok-ed source file in codeql

I am trying to write a code analyzer with [codeql](https://securitylab.github.com/tools/codeql),but I account an error which is displayed as flollowing
```
[2021-01-20 15:56:59] [javac-extractor-4576] [WARN] Skipping Lombok-ed source file: 
```
so my lombok-ed source file is not include in codeql database

eg.my lombok-ed source file displayed as flollowing
```
public class Test1{
    public static String testOkHttpGet() {
        OkHttpClient okHttpClient = new OkHttpClient();

        HttpUrl httpUrl = HttpUrl.parse("http://localhost:8080/demo/list").newBuilder()
                .addQueryParameter("name", "HTTP").build();

        okhttp3.Request request = new okhttp3.Request.Builder().url(httpUrl.toString()).build();
        try (Response response = okHttpClient.newCall(request).execute()) {
            ResponseBody body = response.body();
            if (response.isSuccessful()) {
            } else {
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }

    @Data
    @AllArgsConstructor
    class Student{
        String name;
        String age;
    }

}
```
and the file is not include in [src.zip](https://i.stack.imgur.com/Vd8li.png)

**Comment by aibaars** [comment]
Unfortunately Lombok does not work with the CodeQL Java analyzer. The problem is that lombok files are incomplete Java files. The lombok annotation processor hooks into the Javac compiler are rewrites Javac's syntax trees on the fly to make them complete.

As a work-around you can "delombok" the source files before running CodeQL as follows:
```bash
# get a copy of lombok.jar
wget https://projectlombok.org/downloads/lombok.jar -O "lombok.jar"
# run "delombok" on the source files and write the generated files to a folder named "delombok"
java -jar "lombok.jar" delombok -n --onlyChanged . -d "delombok"
# remove "generated by" comments
find "delombok" -name '*.java' -exec sed '/Generated by delombok/d' -i '{}' ';'
# remove any left-over import statements
find "delombok" -name '*.java' -exec sed '/import lombok/d' -i '{}' ';'
# copy delombok'd files over the original ones
cp -r "delombok/." "./"
# remove the "delombok" folder
rm -rf "delombok"
```
If you're using Maven you could also try: http://anthonywhitford.com/lombok.maven/lombok-maven-plugin/faq.html#alt-src-setup

**Comment by hatface** [comment]
thx, @aibaars ,your solution solve my problem, issue closed

**Comment by umeshnebhani733** [comment]
Just curious, this work around is okay but its little overhead ( do it for all code, some files it doesnt work you fix it... n much more ) is codeql planning to fix it in near future?

**Comment by aibaars** [comment]
@umeshnebhani733 I heard about some ideas on how to fix this, but nothing on the plan yet as far as I know. 

> do it for all code, some files it doesnt work you fix it.

Out of curiosity, could you share examples of things that didn't work and needed additional fixing?

**Comment by dineshkumars0707** [comment]
@aibaars we are using CodeQL for static code analysis. We did manage to Delombok our Java codebase and run the queries to find violations. 

The problem is that the reported violations are pointing to line numbers that are not available in actual codebase. It is practically difficult to use the code analysis results to improve the quality of the code. It could also force us to move away from CodeQL, without a better workaround

Given that Lombok is one of the widely used libraries in Java projects, many other people might be affected with the same issue. Is there a better workaround for this?

**Comment by aibaars** [comment]
> The problem is that the reported violations are pointing to line numbers that are not available in actual codebase. It is practically difficult to use the code analysis results to improve the quality of the code. It could also force us to move away from CodeQL, without a better workaround

@dineshkumars0707 That's indeed a problem, when code is Delombok'ed the Lombok annotations get expanded into generated code causing line numbers to shift. 

One solution would be to compute a line mapping between the original and Delombok'ed source files and use this line map to adjust the line numbers in the SARIF file before uploading it. Any results in Lombok generated lines would get lost with this approach which may be fine. Instead of dropping such results you could try to map them to a matching Lombok annotation.

Another solution would be to push a copy of the analysed source code from the `codeql-database/src.zip` file  to a "shadow" branch in the repository (or a separate repo) and use the name of the shadow branch and the SHA of the commit as the `ref` and `sha` arguments of the upload step. This should display results correctly. However, the first approach probably provides a better user experience for developers of a repository.

**Comment by omokoh** [comment]
Great news. Lombok is now supported.[Code scanning with CodeQL improves support for Java codebases that use Project Lombok
]( https://github.blog/changelog/2023-09-01-code-scanning-with-codeql-improves-support-for-java-codebases-that-use-project-lombok/)
