### ISSUE TITLE
C: Path query with taint tracking for function pointer calling

### ISSUE THREAD

**Issue by quanahwu** [github/codeql#5122]
I am writing path queries with taint tracking.
Currently，I have a query that tracing data from user input to memory access，as following example：
```c
typedef struct buf_s {
    size_t len;
    char buf[0];
} buf_t;

buf_t *buf_create(char *buf, size_t len)
{
    buf_t *b;
    if (buf == NULL || len == 0) {
        return NULL;
    }
    b = (buf_t *)malloc(sizeof(buf_t) + len);
    if (b == NULL) {
        return NULL;
    }
    (void)memcpy(b->buf, buf, len);
    b->len = len;
    return b;
}

void buf_print(buf_t *b)
{
    printf("len(%u), buf(%s)\n", b->len, b->buf);
}

void call_buf_print(buf_t *b)
{
    buf_print(b);
}

int main(int argc, char *argv[])
{
    int r = EXIT_FAILURE;
    char *str1 = argv[1];
    buf_t *b;
    buf_op_t *op;

    b = buf_create(str1, strlen(str1));
    if (b == NULL) {
        printf("buf_t is NULL\n");
        goto err;
    }

    call_buf_print(b);
	...
```
The taint path is identified:
> argv[1] -> str1 -> buf_create -> b -> call_buf_print -> printf -> b->buf

However, to handle paths regard to function pointer calling,
I override "isAdditionalTaintStep", connecting "VariableCall" to "Function", for this situation:
```c
typedef struct buf_op_s {
    funcp_t op_buf_print;
} buf_op_t;

buf_op_t *buf_op_create()
{
    buf_op_t *op = (buf_op_t *)malloc(sizeof(buf_op_t));
    if (op == NULL) {
        return NULL;
    }
    op->op_buf_print = buf_print;
    return op;
}

void buf_op_buf_print(buf_op_t *op, buf_t *b)
{
    if (op == NULL || op->op_buf_print == NULL) {
        return;
    }
    op->op_buf_print(b);
}

	...
/* 	call_buf_print(b);
 */
	
    op = buf_op_create();
    if (op == NULL) {
        printf("buf_op_t is NULL\n");
        goto err1;
    }
    buf_op_buf_print(op, b);
	...
```
I hope to get the path below, and got no luck:
> buf_create -> b -> buf_op_buf_print -> op_buf_print -> buf_print -> printf -> b->buf

the shorter path is identified, as function pointer calling is handled correctly:
> buf_op_buf_print -> op_buf_print -> buf_print -> printf -> b->buf

Here is my query:
```ql
/**
 * @kind path-problem
 */
import cpp
import semmle.code.cpp.dataflow.TaintTracking
import DataFlow::PathGraph


predicate userInputFunction(Function f, int i) {
    f.hasGlobalOrStdName("buf_create") and i = 0
    // f.hasGlobalOrStdName("buf_op_buf_print") and i = 1
}
predicate memAccessFunction(Function f, int i) {
    f.hasGlobalOrStdName("printf") and i = 2
}
predicate isTaintExpr(Function f, int i, Expr expr) {
    exists (Call c |
        f = c.getTarget() and
        c.getArgument(i) = expr
    )
}
predicate isTaintPara(Function f, int i, Parameter para) {
        f.getParameter(i) = para
}
predicate isTaintNode(Function f, int i, DataFlow::Node node) {
    isTaintExpr(f, i, node.asDefiningArgument())
    or
    isTaintExpr(f, i, node.asExpr())
    or
    isTaintPara(f, i, node.asParameter())
    or
    isTaintExpr(f, i, node.asPartialDefinition())
}
class TbdConfig extends TaintTracking::Configuration {
    TbdConfig() {
        this = "TbdConfig"
    }
    override predicate isSource(DataFlow::Node source) {
        exists (Function f, int i |
            userInputFunction(f, i)
            and
            isTaintNode(f, i, source)
        )
    }
    override predicate isSink(DataFlow::Node sink) {
        exists (Function f, int i |
            memAccessFunction(f, i)
            and
            isTaintNode(f, i, sink)
        )
    }
    override predicate isAdditionalTaintStep(DataFlow::Node pred, DataFlow::Node succ) {
        TaintTracking::localTaintStep(pred, succ)
        or  // func_ptr(pred) -> func_target(succ)
        exists (VariableCall vc, Function f, int i |
            pred.asExpr() = vc.getArgument(i)
            and
            vc.getVariable().getAnAssignedValue().getAChild*().(FunctionAccess).getTarget() = f
            and
            f.getParameter(i) = succ.asParameter()
        )
        or  // succ.a_field = pred
        exists (Parameter struct, VariableAccess field |
            pred.asParameter() = struct
            and
            struct.getAnAccess() = field.getAChild()
            and
            field = succ.asExpr()
        )
    }
}
from TbdConfig cfg, DataFlow::PathNode source, DataFlow::PathNode sink
where cfg.hasFlowPath(source, sink)
select sink.getNode().getLocation(), source, sink, "Taint from " + source.getNode().getFunction().getFile().getBaseName() +
    " to " + sink.getNode().getFunction().getFile().getBaseName()
```

What am I missing, or I need to comprehend something else?
Looking forward to hearing from you.

All the example files can be found here:
https://github.com/quanahwu/ql_cpp_func

**Comment by geoffw0** [comment]
Hi quanahwu,

Please could you clarify, which taint step exactly is missing?

**Comment by quanahwu** [comment]
buf_create -> b -> buf_op_buf_print

**Comment by geoffw0** [comment]
I think it's the `(void)memcpy(b->buf, buf, len);` where we're losing taint (and we wouldn't be if it was `b->buf`).  I'm not sure what is wrong at this time.

@mathiasvp do you mind having a quick look at this one as well?

**Comment by MathiasVP** [comment]
> I think it's the `(void)memcpy(b->buf, buf, len);` where we're losing taint (and we wouldn't be if it was `b->buf`). I'm not sure what is wrong at this time.

As far as I can tell it looks like that taint step is working. Here's a screenshot from VSCode:

![Screenshot 2021-02-11 at 10 03 03](https://user-images.githubusercontent.com/4527323/107617852-e760db00-6c50-11eb-9c42-d99cd888f29c.png)
So we do follow the taint all the way to the expression that's an argument to the function pointer call. It looks like we're not able to resolve the call through the function pointer, though. You can verify this yourself by importing the internal library `semmle.code.cpp.dataflow.internal.DataFlowDispatch` and running the query:

```codeql
from ExprCall call
where not exists(viableCallable(call)) and call.getEnclosingFunction().hasName("buf_op_buf_print")
select call
```
Resolving calls through function pointers is something we're in the process of improving. We have a more sophisticated dataflow library that does _some_ of the necessary steps in order to track this flow (which you can try if you import `semmle.code.cpp.security.TaintTracking` instead of `semmle.code.cpp.dataflow.TaintTracking`), but it looks like we still don't catch it using that library.

**Comment by quanahwu** [comment]
> As far as I can tell it looks like that taint step is working. Here's a screenshot from VSCode:

I see, the screenshot indicates that the taint path ends at the function pointer call, "missing" last part. May I have a look at this full query?

I found another "partial" taint path starts from b(as buf_op_buf_print's 2nd parameter), to b->buf(as printf's 3rd argument), which miss the begining part:
![image](https://user-images.githubusercontent.com/59143225/108298404-d9bece80-71d7-11eb-97e7-e125bb0c41c2.png)
Here's my full query:
```codeql
/**
 * @kind path-problem
 */
import cpp
import semmle.code.cpp.dataflow.TaintTracking
import DataFlow::PathGraph


predicate userInputFunction(Function f, int i) {
    // f.hasGlobalOrStdName("buf_create") and i = 0
    f.hasGlobalOrStdName("buf_op_buf_print") and i = 1
}
predicate memAccessFunction(Function f, int i) {
    f.hasGlobalOrStdName("printf") and i = 2
}
predicate isTaintExpr(Function f, int i, Expr expr) {
    exists (Call c |
        f = c.getTarget() and
        c.getArgument(i) = expr
    )
}
predicate isTaintPara(Function f, int i, Parameter para) {
        f.getParameter(i) = para
}
predicate isTaintNode(Function f, int i, DataFlow::Node node) {
    isTaintExpr(f, i, node.asDefiningArgument())
    or
    isTaintExpr(f, i, node.asExpr())
    or
    isTaintPara(f, i, node.asParameter())
    or
    isTaintExpr(f, i, node.asPartialDefinition())
}
class TbdConfig extends TaintTracking::Configuration {
    TbdConfig() {
        this = "TbdConfig"
    }
    override predicate isSource(DataFlow::Node source) {
        exists (Function f, int i |
            userInputFunction(f, i)
            and
            isTaintNode(f, i, source)
        )
    }
    override predicate isSink(DataFlow::Node sink) {
        exists (Function f, int i |
            memAccessFunction(f, i)
            and
            isTaintNode(f, i, sink)
        )
    }
    override predicate isAdditionalTaintStep(DataFlow::Node pred, DataFlow::Node succ) {
        TaintTracking::localTaintStep(pred, succ)
        or  // func_ptr(pred) -> func_target(succ)
        exists (VariableCall vc, Function f, int i |
            pred.asExpr() = vc.getArgument(i)
            and
            vc.getVariable().getAnAssignedValue().getAChild*().(FunctionAccess).getTarget() = f
            and
            f.getParameter(i) = succ.asParameter()
        )
        or  // succ.a_field = pred
        exists (Parameter struct, VariableAccess field |
            pred.asParameter() = struct
            and
            struct.getAnAccess() = field.getAChild()
            and
            field = succ.asExpr()
        )
    }
}
from TbdConfig cfg, DataFlow::PathNode source, DataFlow::PathNode sink
where cfg.hasFlowPath(source, sink)
select sink.getNode().getLocation(), source, sink, "Taint from " + source.getNode().getFunction().getFile().getBaseName() +
    " to " + sink.getNode().getFunction().getFile().getBaseName()
```

These two "partial" path "interlace", I just want to connect them.
Could you share some debugging tips in your routine works, or recommend some books, so I can be of better help?

**Comment by MathiasVP** [comment]
> I see, the screenshot indicates that the taint path ends at the function pointer call, "missing" last part. May I have a look at this full query?

Sure. It should be the same one as yours, but modified to import `DataFlow::PartialPathGraph` instead of `DataFlow::PathGraph` to view partial dataflow paths:

```codeql
/**
 * @kind path-problem
 */

import cpp
import semmle.code.cpp.dataflow.TaintTracking
import DataFlow::PartialPathGraph

predicate userInputFunction(Function f, int i) {
  f.hasGlobalOrStdName("buf_create") and i = 0
  // f.hasGlobalOrStdName("buf_op_buf_print") and i = 1
}

predicate memAccessFunction(Function f, int i) { f.hasGlobalOrStdName("printf") and i = 2 }

predicate isTaintExpr(Function f, int i, Expr expr) {
  exists(Call c |
    f = c.getTarget() and
    c.getArgument(i) = expr
  )
}

predicate isTaintPara(Function f, int i, Parameter para) { f.getParameter(i) = para }

predicate isTaintNode(Function f, int i, DataFlow::Node node) {
  isTaintExpr(f, i, node.asDefiningArgument())
  or
  isTaintExpr(f, i, node.asExpr())
  or
  isTaintPara(f, i, node.asParameter())
  or
  isTaintExpr(f, i, node.asPartialDefinition())
}

class TbdConfig extends TaintTracking::Configuration {
  TbdConfig() { this = "TbdConfig" }

  override predicate isSource(DataFlow::Node source) {
    exists(Function f, int i |
      userInputFunction(f, i) and
      isTaintNode(f, i, source)
    )
  }

  override predicate isSink(DataFlow::Node sink) {
    exists(Function f, int i |
      memAccessFunction(f, i) and
      isTaintNode(f, i, sink)
    )
  }

  override predicate isAdditionalTaintStep(DataFlow::Node pred, DataFlow::Node succ) {
    TaintTracking::localTaintStep(pred, succ)
    or
    // func_ptr(pred) -> func_target(succ)
    exists(VariableCall vc, Function f, int i |
      pred.asExpr() = vc.getArgument(i) and
      vc.getVariable().getAnAssignedValue().getAChild*().(FunctionAccess).getTarget() = f and
      f.getParameter(i) = succ.asParameter()
    )
    or
    // succ.a_field = pred
    exists(Parameter struct, VariableAccess field |
      pred.asParameter() = struct and
      struct.getAnAccess() = field.getAChild() and
      field = succ.asExpr()
    )
  }

  override int explorationLimit() { result = 20 }
}

from TbdConfig cfg, DataFlow::PathNode source, DataFlow::PathNode sink
where cfg.hasFlowPath(source, sink)
select sink.getNode().getLocation(), source, sink,
  "Taint from " + source.getNode().getFunction().getFile().getBaseName() + " to " +
    sink.getNode().getFunction().getFile().getBaseName()
```

Note that, to use `DataFlow::PartialPathGraph` you also need to implement `Configuration.explorationLimit`. Thie predicate upper-bounds the length of the partial path. 20 should be more than enough for this small example.

> These two "partial" path "interlace", I just want to connect them.

Yeah, I think I see the problem now. This gets a bit into the nitty-gritty details of how we do dataflow/taintflow:

When taint reaches a field such as `b->buf` we record this as saying that "`b` is tainted, but in order to get to the tainted value you _must_ access the `buf` field". This is what the `[buf]` annotation in your path explanations mean.

Now, for various reasons, when we're in a situation in which taint can only be accessed by going through a specific list of fields (like the 1 element list `[buf]` in your case), we don't follow the taint steps given to us by the configuration's `isAdditionalTaintStep`. This means that when taint reaches `b->buf` in this line:

```c
(void)memcpy(b->buf, buf, len);
```
we taint `b` and remember that `buf` _must_ be accessed to get to the taint. But now we're in the situation I described above, and we don't use your `func_ptr(pred) -> func_target(succ)` custom taint rule to transfer flow to the target function.

A fix to this is to provide another custom taint rule in `isAdditionalTaintStep` that taints `b` when `b->buf` is an argument to `memcpy`. Then we get a path without using our internal mechanism for handling fields, and thus your configuration's custom taint rules will fire. One way of specifying this additional taint rule case could be:

```codeql
  override predicate isAdditionalTaintStep(DataFlow::Node pred, DataFlow::Node succ) {
    // ... the other rules you have ...
    or
    exists(FunctionCall memcpy, FieldAccess fa |
      memcpy.getTarget().hasName("memcpy") and
      pred.asExpr() = memcpy.getArgument(1) and
      memcpy.getArgument(0) = fa and
      succ.asPartialDefinition() = fa.getQualifier()
    )
  }
```

Note however, that there's a reason we don't do taintflow through fields like this :) It has potential for false positive results since the combination of these two rules:

```
  pred.asParameter() = struct and
      struct.getAnAccess() = field.getAChild() and
      field = succ.asExpr()
    )
```
and
```
    exists(FunctionCall memcpy, FieldAccess fa |
      memcpy.getTarget().hasName("memcpy") and
      pred.asExpr() = memcpy.getArgument(1) and
      memcpy.getArgument(0) = fa and
      succ.asPartialDefinition() = fa.getQualifier()
    )
```
can result in taintflow from one field of an object to a different field of the same object.

> Could you share some debugging tips in your routine works, or recommend some books, so I can be of better help?

I don't think I can offer many tips other than "Keep using CodeQL! I can't imagine a better a better way to learn the necessary debugging tips than getting your hands dirty and trying out our libraries (for instance `DataFlow::PartialPathGraph`)".

**Comment by quanahwu** [comment]
> I hope this helps!
Thank you for the explaination and advice, very specific and clear.
