### ISSUE TITLE
LGTM.com - false positive in py/reflective-xss

### ISSUE THREAD

**Issue by gavinl** [github/codeql#5129]
A user has reported a possible code scanning FP

Ticket: [ZD#1008824](https://github.zendesk.com/agent/tickets/1008824)

Source code link: https://github.com/MirahezeBots/mirahezebots.org/blob/dev/app.py#L61

Alert rule: py/reflective-xss

**Comment by RasmusWL** [comment]
Thanks for the report :+1: I agree that in this instance, it's a FP.

I found the alert on [this commit](https://github.com/MirahezeBots/mirahezebots.org/commit/c2c7ee653a6472d1196121f4eb24afab5ba2950e). Looking at the code, I assume we consider [these lines](https://github.com/MirahezeBots/mirahezebots.org/blob/c2c7ee653a6472d1196121f4eb24afab5ba2950e/app.py#L39-L43) to make the output of `display_content` user-controlled. In reality, since [`path` is used to index](https://github.com/MirahezeBots/mirahezebots.org/blob/c2c7ee653a6472d1196121f4eb24afab5ba2950e/app.py#L11) the static configuration (and it is checked that the key is available before `display_content` is called), it really can't be any user-controlled.

**Comment by gavinl** [comment]
Thanks @RasmusWL for the response and for the explanation!
