### ISSUE TITLE
false positive (static function is, in fact, reachable)

### ISSUE THREAD

**Issue by Habbie** [github/codeql#5138]
In a C++ source file (https://github.com/PowerDNS/pdns/pull/9819/files#diff-55e4bf282f3f031a5dac97147dcebf8e1aa86833e578ae97e5b9256d1f0c979eR95), we have the following code:

```
static map<uint16_t, const string> swapElements(const map<const string, uint16_t>& names) {
  map<uint16_t, const string> ret;

  for (const auto& n : names) {
    ret.insert(make_pair(n.second, n.first));
  }
  return ret;
}

const map<uint16_t, const string> QType::numbers = swapElements(names);
```

CodeQL reports  'Unused static function - Static function swapElements is unreachable' via rule ID `cpp/unused-static-function`.

However, clearly the function is reachable, and used. Just to be sure, I removed the function and the compiler reported an error at the call site.

The report is at https://github.com/PowerDNS/pdns/security/code-scanning/759?query=ref%3Arefs%2Fpull%2F9819%2Fmerge but I don't know if you can view that.

**Comment by criemen** [comment]
Indeed, this looks like a false positive. Thank you for reporting it!

Our current focus is on improving our security analysis. Because your report does not relate to a security query, we will put this on our backlog and prioritize it if we get enough reports of the same underlying issue in other projects. If you think that your report is related to our security analysis, please clarify that in a comment. Either way, we'll let you know here as soon as it's fixed!

As you might know, all of our queries are open source. If you do have an idea for a code change, we encourage you to open a pull request. GitHub Code Scanning and lgtm.com have facilities for suppressing individual alerts or disabling a query.

**Comment by Habbie** [comment]
Thanks Cornelius!
