### ISSUE TITLE
LGTM.com - false positive | django templating inside javascript

### ISSUE THREAD

**Issue by artoonie** [github/codeql#5224]
**Description of the false positive**

Django template insertion in Javascript/HTML shows issues.
1. Javascript insertion via the templating system shows up as "This expression has no effect." In the example below, some javascript is passed directly from a Django view into the javascript.
2. Django conditionals show up as "This attribute is duplicated"

**URL to the alert on the project page on LGTM.com**

1. JS insertion: {{ somePrecomputedJs }}
https://lgtm.com/projects/g/artoonie/rcvis/snapshot/9f12a919a9ceb928bcda0d9f2cda9d7d6077a4e4/files/templates/bargraph/barchart-fixed-nonblocking.html#x92662c1d6139e57e:1

2. HTML conditional: {% if something %}
https://lgtm.com/projects/g/artoonie/rcvis/snapshot/9f12a919a9ceb928bcda0d9f2cda9d7d6077a4e4/files/templates/tabular/tabular-candidate-by-round.html?sort=name&dir=ASC&mode=heatmap#x40ac9d9f3eb492b7:1

**Comment by asgerf** [comment]
Hi @artoonie,

Thanks for reporting these. The second issue, regarding HTML attributes, should be fixed by https://github.com/github/codeql/pull/5236. Those FPs should go away next time LGTM updates (most likely next week or the week after).

We've discussed how to tackle the first issue, which is tricky since it happens to be valid JS syntax. The best option is probably to classify those files as templates in your `lgtm.yml` file:
```yml
path_classifiers:
  templates:
    - "templates/*"
  ```

**Comment by artoonie** [comment]
Thank you for making the fix in the PR! I'll add the templates `path_classifier` and hopefully, finally, my code will LGTyou.

Closing this ticket as #5236 is merged.
