### ISSUE TITLE
DataFlow::PathNode

### ISSUE THREAD

**Issue by fxzyyy** [github/codeql#5229]
**DataFlow::PathNode usage problem**

```sql
import java
import DataFlow
import semmle.code.java.dataflow.FlowSources
import DataFlow::PathGraph

class TestConfig extends TaintTracking::Configuration {
  TestConfig () { this = "TestConfig" }

  override predicate isSource(DataFlow::Node source) { source.asExpr() instanceof AddExpr }

  override predicate isSink(DataFlow::Node sink) { sink.asExpr() instanceof AddExpr }
}


class Test extends Method {

  predicate flowsTo(PathNode pn, Node node) { pn.getNode() = node }

  predicate hasFlowPath(PathNode pn) { flowsTo(pn, _) }
}

from DataFlow::PathNode pn, Test t
where
  t.hasFlowPath(pn)
select pn
```

java source:

```java
public String test(HttpServletRequest request) {
        String resultStr = "(" + request.getParameter("test")+ ")";
        return resultStr;
}
```

Why did I not call TestConfig class, but the result of the query is based on the predicate isSource and the predicate isSink of TestConfig.Does the predicate edges of DataFlow::PathGraph make the call when it runs?

**Comment by hmakholm** [comment]
The taint analysis will call the overrides of _all_ instances of the abstract class `Configuration`. Since you provided such a subclass, your predicates in it will be called. This is a common idiom in QL for letting library code depend on predicates supplied by the query.

To understand how this works, even though `TestConfig () { this = "TestConfig" }` _looks_ a bit like a constructor in an ordinary object-oriented language, it doesn't really tell how to "construct" an instance of your class. What it instead does is to declare that the _already existing_ string `"TestConfig"` will be an instance of the class -- and therefore, because `Configuration` is an abstract class, an instance of `Configuration` too.

QL makes it easy for code in the library to get at the set of all instances of `Configuration` -- in fact, at least conceptually that is what it happens every time you declare a variable with a type in QL: it will attempt to take on all possible values of the type unless you provide conditions that exclude some of them. (How it's actually evaluated is more efficient than that, when the QL compiler can find a way, but that's merely an implementation detail). In that way the library gets to use the `Configuration` persona you have bestowed upon the `"TestConfig"` string. It doesn't need to know explicitly that your class exist.

-----

By the way, and unrelated to that question, your `Test` class is a bit spurious -- neither of the member predicates you write even refer to `this`, so (a) every `Method` whatsoever becomes an instance of `Test` too, and (b) it will never matter _which_ of those instances you call your `.hasFlowPath()` on. But QL will try to evaluate it for each `Method` in the database, just in case some would give different results. This sort of thing could make your query very slow on large databases.

(For this particular query, the compiler is actually smart enough to figure out that it doesn't matter which method it is, so it _doesn't_ end up scanning through all possible combinations of `t` and `pn` -- it just checks once and for all there there exists at least one `Method` in the database, and therefore a `Test` instance you can call `hasFlowPath()` on).

Instead of having a `Test` class you could declare `flowsTo` and `hasFlowPath()` _outside any class_ and call them without a qualifier from the `select` clause.

----

Finally, note that your `flowsTo` predicate doesn't really give you any _flow_; it just gives you two ways of referring to the _same_ node in the flow graph. (I suspect that might be a remnant of a more meaningful predicate that you've reduced down to minimize the example, though).

**Comment by fxzyyy** [comment]
```ql
import java
import DataFlow
import semmle.code.java.dataflow.FlowSources

class TestConfig extends TaintTracking::Configuration {
  TestConfig () { this = "TestConfig" }

  override predicate isSource(DataFlow::Node source) { source instanceof RemoteFlowSource }

  override predicate isSink(DataFlow::Node sink) { sink.asExpr() instanceof AddExpr }
}

from DataFlow::PathNode pn
select pn
```

```java
public String test(HttpServletRequest request) {
        String test = request.getParameter("test");
        String addStr = "(" + test + ")";
        return addStr;
}
```


@hmakholm Thanks for the answer. In addition, I have tested ql, The result of the above code is ```request.getParameter("test")``` and ```"(" + test + ")"```

```java
public String test(HttpServletRequest request) {
        String test = request.getParameter("test");
        String str = "xxx";
        String addStr = "(" + str + ")";
        return addStr;
}
```
The above code will not have any results.

```java
public String test(HttpServletRequest request) {
        return request.getParameter("test");
}
```
The result of the above code is ```request.getParameter("test")```


My conclusion is: when using ```DataFlow::PathNode```, the ```TestConfig``` class is still called, and taint analysis is performed. This is the working principle of ```DataFlow::PathNode``` .

***

In addition, many ql statements have ```import DataFlow::PathGraph```, I don't know what is the effect of introducing it. If it is not introduced, will it have any impact on taint analysis?

**Comment by alexet** [comment]
Your conclusion about `DataFlow::PathNode` is mostly correct. `DataFlow::PathNode` are nodes created for explaining the result. So they are created if there is flow in any configuration. They have a bit of extra contextual call data so we can show contextual paths through calls but they are created on demand as there would be a lot of them if we created all of them. So a `DataFlow::PathNode` node is a node along some tainted path.

On the other hand `DataFlow::Node` always exist but are local to an individual function. These are used to compute whether there is flow.

`DataFlow::PathGraph` defines the graph of flow between source and sink. By importing it additional results are selected which will allow codeql to give results with path in them. However it shouldn't affect the dataflow analysis in any way. There is more documentation on path queries here: https://codeql.github.com/docs/writing-codeql-queries/creating-path-queries/#creating-path-queries.

In general to make a taint query with results that include taint paths you would want to write the following.

```
import java
import DataFlow
import DataFlow::PathGraph
import semmle.code.java.dataflow.FlowSources

class TestConfig extends TaintTracking::Configuration {
  TestConfig () { this = "TestConfig" }

  override predicate isSource(DataFlow::Node source) { source instanceof RemoteFlowSource }

  override predicate isSink(DataFlow::Node sink) { sink.asExpr() instanceof AddExpr }
}

from TestConfig config, DataFlow::PathNode source, DataFlow::PathNode sink
where config.hasFlowPath(source, sink)
select sink.getNode(), source, sink, "<message>"
```

Then the paths between remote flow sources and `AddExpr` should be should be shown in the result.

**Comment by fxzyyy** [comment]
Thanks @alexet @hmakholm , My problem is solved
