### ISSUE TITLE
Java: Allow queries to read ServiceLoader provider-configuration files

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#5231]
Could the extractor please be enhanced to be able to read ServiceLoader provider-configuration files under `META-INF/services/` (see [documentation](https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/util/ServiceLoader.html), section "Deploying service providers on the class path").

There are a few things you can get wrong with provider-configuration files (which as far as I know do not cause compilation or packaging errors):
- Cases listed under "Errors" section of documentation
- Provider-configuration file referencing class which does not exist
- Provider-configuration file referencing same class twice
- Provider-configuration file being created for a class which does not exist (e.g. `META-INF/services/does.not.exist`)

**Comment by alexet** [comment]
Our current focus is on improving our security analysis. Because your report does not relate to a security query, we will put this on our backlog and prioritize it if we get enough reports of the same underlying issue in other projects. If you think that your report is related to our security analysis, please clarify that in a comment.
