### ISSUE TITLE
C/C++: fromSource predicate matching BuiltinFunctions and (at least some) closed source library calls

### ISSUE THREAD

**Issue by adriaanjacobs** [github/codeql#5306]
[C/C++]

For the cpp QL library, [the documentation states](https://codeql.github.com/codeql-standard-libraries/cpp/semmle/code/cpp/Element.qll/predicate.Element$Element$fromSource.0.html) that the fromSource() predicate will always be true, "as all files are considered to be 'from source'". 

However, when running the following query on a C++ codebase:
```
from Function f
where not f.fromSource()
select f
```

both a list of `__builtin_X` as well as `operator delete[]` and `operator=` are reported. Has the implementation of fromSource() been updated since writing the documentation? Or is this predicate still unreliable to detect external calls in CodeQL?

**Comment by aeisenberg** [comment]
Hmm...that documentation seems a little bit misleading. Here's the documentation from the `File::fromSource()`, which is called by `Element::fromSource()` you can see if you hover over `File::fromSource()` in vscode:

> Holds if this file may be from source. This predicate holds for all files except the dummy file, whose name is the empty string, which contains declarations that are built into the compiler.

**Comment by aeisenberg** [comment]
@github/codeql-c Should we update the documentation for `Element::fromSource()` to be consistent with `File::fromSource()`?

**Comment by adriaanjacobs** [comment]
Does this mean that using Function::fromSource is not the recommended way to detect if a FunctionCall (via `getTarget()`) is a call into an external library? What would be recommended for that?

**Comment by adriaanjacobs** [comment]
But if I'm calling into an external (precompiled) library, won't `getFile()` reference the header file from the include directory in which the function is declared? Wouldn't those also be considered project files?

**Comment by rdmarsh2** [comment]
For the original question, that documentation is out of date. `__builtin_X` and some instances of `operator delete[]` and `operator=` are compiler-provided and can't be mapped to any real location at all, which is why `fromSource` doesn't hold.

The difference between the C++ handling of precompiled libraries with associated header files and the handling of precompiled libraries in languages like Java or C# is that other than compiler builtins, every function we represent in the C++ database has an associated location in some form of source code, whether that's in a source or header file. For other languages, we also represent functions/methods from various intermediate formats (`.class` files, .NET DLLs), and `fromSource` won't hold for those.

To recognize functions from a precompiled library, we usually use `hasDefinition()` to identify functions that are declared but not defined in the source we have access to.

**Comment by geoffw0** [comment]
Note that `hasDefinition()` will hold for some library functions, where they have a definition in the header files visible during compilation.  Another option is `exists(f.getDefinition().getFile().getRelativePath())` which checks that there is a definition and it's inside the source directory.

**Comment by adriaanjacobs** [comment]
@geoffw0  I see, thank you. For my purposes, I meant "call for which no source code is available" as external call. It's good to know that this nuance ("call into function that is not from the source directory") can be achieved using different queries though.
