### ISSUE TITLE
How to build a database for the tomcat project

### ISSUE THREAD

**Issue by fxzyyy** [github/codeql#5355]
**How to build a database for the tomcat project?**

Tomcat project uses ```sh startup.sh`'' to build the database and reports an error.

Error content:

```error
No source code was seen during the build.
This can occur if the specified build commands failed to compile or process any code.
 - Confirm that there is some source code for the specified language in the project.
 - For codebases written in Go, JavaScript, TypeScript, and Python, do not specify 
   an explicit --command.
 - For other languages, the --command must specify a "clean" build which compiles 
   all the source code files without reusing existing build artefacts.
```

**Comment by fxzyyy** [comment]
@aschackmull @Marcono1234 @smowton Can you help me?

**Comment by aibaars** [comment]
Tomcat can be built with the default maven command used by the codeql autobuilder. You can also download a database from https://lgtm.com/projects/g/apache/tomcat/ci/#ql

**Comment by fxzyyy** [comment]
@aibaars Thanks,What if the project is a java web project (not a maven java web project)?

**Comment by aibaars** [comment]
@fxzyyy You'd need to run whatever command is needed to *build* the java web project from its source code. Typically this is `ant`, `gradle` or `mvn`. The `startup.sh` script is for running the compiled code. If your code is for example an Eclipse Web project without build script, then you could have Eclipse generate an `ant` script and run that.

**Comment by fxzyyy** [comment]
@aibaars Thank you, I successfully built the database through `maven`.

**Comment by fxzyyy** [comment]
@aibaars CodeQL seems to have libraries for parsing `build.xml` and `pom.xml`, but not libraries for parsing `build.gradle`?

**Comment by aibaars** [comment]
> @aibaars CodeQL seems to have libraries for parsing `build.xml` and `pom.xml`, but not libraries for parsing `build.gradle`?

That's right. CodeQL has support for including arbitrary XML files in its databases. The libraries for "parsing" `build.xml` and `pom.xml` are just thin wrappers around the generic XML classes for entities and attributes. A `build.gradle` file contains Groovy or Kotlin code which CodeQL does not support at the moment. 

I'm closing this issue because the question related to `build.gradle` is unrelated to the original topic of this issue. It's better to start a new feature request or question issue. The team actively monitors new issues, so a question in a new issue is more likely to be answered quickly than a question in a comment.

**Comment by fxzyyy** [comment]
@aibaars Thanks,Regarding `build.gradle` I will create a new question.
