### ISSUE TITLE
Java: FloatingPointLiteral.getValue() has precision loss

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#5418]
It appears `FloatingPointLiteral.getValue()` has precision loss. This is probably an extractor issue because:
- `toString()` is not affected (but its result is an implementation detail, so relying on it is error-prone)
- `DoubleLiteral.getValue()` does not appear to have precision loss

Example query demonstrating the issue:
```ql
import java

from Literal l, string value
where
  value = l.getValue()
  and value.regexpMatch(".*E\\d+")
  and l.toString().toFloat() != value.toFloat()
select l, value
```
[Query Console link](https://lgtm.com/query/1245251324580825089/)

**Comment by intrigus-lgtm** [comment]
I don't think this really is an issue, more of a "gotcha".

The problem is "simple", for example, let's look at [this result](https://github.com/neo4j/neo4j/blob/7b76b124e749766679673a67ae87fd185063fccd/community/kernel/src/test/java/org/neo4j/kernel/impl/index/schema/RawBitsTest.java#L71) from `neo4j`.
The value `33554433F` is not representable as a 32-bit IEEE float! So Java will have to use the closest possible value, which is `3.3554432E7` (Try it in `jshell`: 
```java
Float.parseFloat("33554433F")
$1 ==> 3.3554432E7
```
).

So we have a literal  `33554433F` but it's *real float value* is `3.3554432E7`.
Now the question is: 
Why is `literal.toString().toFloat()` (literal.toString() = "33554433F") not returning the same float value?
And here is the "gotcha"! CodeQL does not use "Java" floats (that is, 32-bit IEEE floating-point values), but 64-bit IEEE floating-point values!
So `literal.toString().toFloat()` (literal.toString() = "33554433F") would be equivalent to 
```java
Double.parseDouble("33554433F")
$1 ==> 3.3554433E7
```. And `3.3554433E7` is obviously not the same as `3.3554432E7`.

You also have this problem with representation when using doubles:
```java
Double.parseDouble("9007199254740993")
$1 ==> 9.007199254740992E15
```
But in this case it's not a problem because you now use doubles in both cases (`Double.parseDouble("9007199254740993") == Double.parseDouble("9007199254740993")`) and don't mix "Java" floats and doubles as before.

**Comment by Marcono1234** [comment]
Ah, sorry and thanks for the great explanation! This is issue is invalid then.
I confused myself when I was testing a query for down casting literals. The Java code used `2147483647f` (`Integer.MAX_VALUE` as float), but the query used CodeQL's 64-bit float to provide the maximum value for a number type.
Therefore due to precision loss of 32-bit `float` the value actually is greater than the `Integer.MAX_VALUE` 64-bit float used in the test.
