### ISSUE TITLE
Question regarding  Github Code Scan / LGTM

### ISSUE THREAD

**Issue by LordAmit** [github/codeql#5536]
Hi,

My team is conducting academic research on Java Cryptography API based misuse using your codeQL and the default rule-sets of LGTM/Github Code Scan. 

We are trying to understand how Java Crypto API related Github Code Scan Rule-Set are created/accepted from contributors _by design, and why_. Particularly, this requires us to know a little more about the assumed threat model, i.e., do you anticipate only a _fully-cooperative/benign developer,_ or also an _evasive developer_ who simply wants to pass tests and move on, and will tweak code until they do? The latter case is quite common, especially in large code bases with contributions from third-party contractors who do not have much ownership over the product, and also when markets use security tools to analyze third-party apps (e.g., Google Play’s analysis of SSL/TLS use).

I am including the following example(s) to give you more insight into what we are thinking:

To illustrate, the following can be considered as _common crypto API misuse_ (i.e., something anyone would do): 

```java
Cipher.getInstance("DES"); //o1
```

Whereas the following can be considered _uncommon misuse patterns_ (i.e., seemingly evasive).

```java
Cipher.getInstance("AES".replace("A", "D")); //p1

Cipher.getInstance("des".toUpperCase()); //p2

Cipher.getInstance("DE$S".replace("$", "")); // p3

Cipher.getInstance("AES/GCM/NoPadding".replace("AES/GCM/NoPadding", "DES")); //p4
```

Considering these examples, we had the following questions:

1. What is your threat model for the Crypto API related rule set, i.e., does the existence of _evasive_ developers influence the design decisions behind the rulesets created/accepted as CodeQL's default?
2. Do these _uncommon misuse patterns_ seem evasive, i.e., would you consider them within scope if they were given to you as unit tests for GitHub Code Scan to enhance the tool/default ruleset?
3. If the _uncommon misuse patterns_ are seen in _benign_ software (i.e., no evidence of evasive motives), would these be within the scope of correct implementation checking tools such as Github Code Scan's default rule set?

Please let us know what you think. Thanks again for your very valuable insight.

**Comment by dbartol** [comment]
Thanks for the interesting questions!

The "threat model" for most of our CodeQL security rules, including the Crypto API rules you mention, is primarily focused on finding vulnerabilities due to one of the following:
1. Honest mistakes ("I meant to type 'AES', but I accidentally typed 'DES'.")
2. Lack of domain knowledge ("I didn't know DES was considered insecure.")
3. Carelessness ("I cut and pasted some code from Stack Overflow without bothering to understand it.")

Most developers make mistakes for all three of the above reasons, without any malicious intent. Our default queries tend to be pretty good at finding vulnerabilities in these situations. So, if you assume that the contributor of the code _wants_ the code to be secure, but sometimes doesn't get it right, our default queries can help those contributors do the right thing.

For reviewing code written by a developer whom you do not trust (for example, a PR to an open-source project from a stranger on the Internet), manual review of the diffs by a trusted developer is still the most effective tool. CodeQL can spot mistakes, but human eyes should look for "suspicious" code. For typical PRs, this is manageable. If you have to review an entire codebase at once, manual review can be difficult.

Every static analysis tool attempts to maximize the number of true vulnerabilities reported while minimizing the number of false positives, but since these two goals interfere with one another, each tool makes its own choice about the right balance. The default CodeQL rules are generally tuned to report very few false positives, at the expense of occasionally missing real vulnerabilities. We think this is the right balance for most of our customers, to let them fix real vulnerabilities without wasting time investigating hundreds or thousands of alerts that turn out to be false positives.

The above tradeoff does mean that a CodeQL scan that results in zero alerts for, say, the weak crypto algorithm query, means only that CodeQL did  not find any such vulnerabilities; it does not mean that CodeQL _proved_ that there are no such vulnerabilities in the code. This means that "evasive" developers explicitly trying to get away insecure coding practices by "tricking" the analysis into not reporting a violation is outside of our threat model. The same applies for malicious developers, who are actively trying to subvert the security of the code.

If we attempted to improve our analysis to, for example, determine that `"AES".replace("A", "D")` was equivalent to `"DES"`, then an evasive or malicious developer could just take the obfuscation another step farther. Then we would do more work to make the analysis understand that new pattern, forcing the evasive developer to come up with yet another convoluted approach to confuse the analysis, and so forth.

For some types of vulnerability, it might be reasonable to write a more aggressive rule that reports an alert whenever the code cannot be proven secure, rather than our usual approach of reporting an alert only when we're fairly certain that the code is insecure. The weak crypto algorithm rule is actually a good example here. I believe the existing rule looks for calls to `Cipher.getInstance()`, and examines the argument to that method. There are four possible cases to handle:

| Code | Argument | Alert? |
| --- | --- | --- |
| `Cipher.getInstance("AES")` | constant string, strong algorithm | No alert |
| `Cipher.getInstance("DES")` | constant string, weak algorithm | Alert |
| `Cipher.getInstance("YYZ")` | constant string, unknown algorithm | No alert |
| `Cipher.getInstance("AES".replace("A", "D"))` | not a constant string | No alert |

A more aggressive version of the same rule would report an alert on all but the first case in the above table. Thus, if the algorithm ID is computed via complex code like `"AES".replace("A", "D")`, this new rule would report an alert, and whoever is investigating the alert could see the evasive or malicious code.

This disadvantage of this approach is that it can produce more false positives. For example, `Cipher.getInstance("DES".replace("D", "A")` would be flagged, even though it really uses "AES", because the analysis can't determine the actual ID being used. However, you would expect most code to just pass a string literal with the right algorithm ID, so hopefully these sorts of false positives are rare. Even if it turns out to be common for developers to compute the ID using something beyond a string literal, you can fix these false positives by extending the analysis to handle more complex patterns _that are actually used by developers to do the right thing_. It is much easier to keep the rule up to date with the relatively few patterns that are useful, compared to having to keep the original rule's analysis up to date with whatever the evasive or malicious developers keep dreaming up to keep avoiding the alert.

I will note that CodeQL has been used to search for malicious code. Microsoft's security team [wrote some CodeQL queries](https://www.microsoft.com/security/blog/2021/02/25/microsoft-open-sources-codeql-queries-used-to-hunt-for-solorigate-activity/) to look for the specific patterns used in the recent SolarWinds attack. Note that these queries were looking for specific known malicious patterns, though, so they are not attempting to detect malicious code in the general case.

With all that said, I'll attempt to directly answer your original questions:
> What is your threat model for the Crypto API related rule set, i.e., does the existence of evasive developers influence the design decisions behind the rulesets created/accepted as CodeQL's default?

The current threat model for most of our rules, Crypto API included, does not consider evasive or malicious developers.
 
> Do these uncommon misuse patterns seem evasive, i.e., would you consider them within scope if they were given to you as unit tests for GitHub Code Scan to enhance the tool/default ruleset?

I would consider all of the examples you gave as evasive, or at least suspicious. I just don't see why a developer would write those specific code patterns rather than just using a string literal. However, I can imagine that there are some patterns that aren't currently supported by the rule, but aren't obviously evasive.

If we decided that evasive developers were in scope, we would probably see these as interesting unit tests. However, since we would probably take an approach similar to what I outlined above, we would not need very many unit tests of intentionally evasive patterns. Instead, we'd just have one or two patterns representing "complicated" code, and ensure that our rule reported an alert on it. If we took this "warn on anything complicated" approach, we'd be more interested in unit tests of ways that non-evasive developers do compute the algorithm ID with code more complicated than a simple string constant.

> If the uncommon misuse patterns are seen in benign software (i.e., no evidence of evasive motives), would these be within the scope of correct implementation checking tools such as Github Code Scan's default rule set?

Yes, if a misuse pattern appeared to be non-evasive, we'd certainly consider it for our default rule set. The more instances of a given misuse pattern that can be found in real software (especially on the projects covered by lgtm.com), the more likely we are to change our analysis to handle that pattern.

Thanks again for the interesting questions!

**Comment by LordAmit** [comment]
I can understand the threat model of CodeQL better through your answer. Thank you!
