### ISSUE TITLE
Dereferenced value may be null + Java index may be out of bounds potential false positive

### ISSUE THREAD

**Issue by eevanwong** [github/codeql#5610]
Hey! I'm currently working on adding LGTM alerts to Apache Drill, and I've come across these particular alert in the codebase. 

These 2 alerts are for Dereferenced-value-may-be-null. My issue is that there is already a guard (if document == null break) before it so it would not reach that particular part of code if it was null. 

Now, the only way to deal with these alerts would be to initialize document as something else; however, there are many other alerts like this one in apache drill, where you can't initialize it so any other arbitrary value other than null (e.g a file var, where I would need to have some arbitrary file in order for it to be initialized).

https://lgtm.com/projects/g/apache/drill/snapshot/e2a0925dd18aacf3a5657acd738f89a63a3b8576/files/contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/json/MaprDBJsonRecordReader.java#xcaa46baefc92faf7:1 

I would just like to see if there are any potential solutions to this. If it has to be suppressed so be it.

**Comment by aeisenberg** [comment]
This may be a false positive in your case, but from the analysis perspective, there's no way to know that the `UserException` didn't come from the line above `document = nextDocument();`.

If you move the `document = nextDocument();` outside of the try block, the error will go away. Of course, this may not be correct either since `nextDocument()` _may_ throw a `UserException` that needs to be caught (I am not familiar with this code, so this is something you need to determine).

**Comment by aibaars** [comment]
Looking at the code it seems that `nextDocument` can throw a `UserException`. If that happens then the `catch` block is evaluated while `document` is `null`.

**Comment by eevanwong** [comment]
Yes the nextDocument() might throw an error that needs to be caught. So putting it outside of try block may not work. 

My bad though, I had actually missed the document = nextDocument() completely b/c I was so focused on what the LGTM was pointing towards. 

Is there a reason why it points to the null value and the null guard so far back despite the fact that `document = nextDocument()` is right there?

**Comment by aibaars** [comment]
The CodeQL query that performs this analysis uses the `null` assignment and `null` check as "evidence" that the variable may be `null`.  Without such "evidence" the query won't report anything; this is to avoid false positives.

For example the query does not complain about the following code:
```
public void run(Runnable r) { 
  r.run()
}
```
but it does complain about
```
public void run(Runnable r) { 
  if (r == null) System.out.println("warning");
  r.run()
}
```
Both methods would throw a `NullPointerException` when called with a `null`. The first variant is simply not meant to be called with `null` values. In the second variant, however, looks like the programmer intended for the method to be callable with `null` values, but unfortunately made a mistake in the handling of such values.

The reason the analysis points at the `null` check/assignment earlier, is because the `null` check right after the call to `nextDocument` is too "late". The analysis is complaining about the case where `nextDocument` throws an exception and the code would enter the `catch` block.

**Comment by eevanwong** [comment]
Thank you for all of your responses, I really appreciate it. 

If that's the case, I suppose it would be best to just suppress the alert?

**Comment by aibaars** [comment]
@eevanwong I think the best solution would be to modify the `catch` clause and make it check that `document` is not `null` . Perhaps modify:
```
table.getPath(),
  document.asReader() == null ? ...
```
to
```
table.getPath(),
  document == null || document.asReader() == null ? ...
```

Without the `null` check you run the risk that the `catch` clause throw a `NullPointerException`.

**Comment by eevanwong** [comment]
Thank you! I'll definitely try that out!

I do have a few other qs about some other alerts that aren't really related to this one though. Should I be making a new issue or could I put them here?

**Comment by aeisenberg** [comment]
I have a slight preference for opening a new issue, just because it will be easier for others to search for answers if they have similar questions.

**Comment by eevanwong** [comment]
I see. I shall close this one and open a new on in that case.
