### ISSUE TITLE
LGTM.com - false positive: React context value always evaluate to true

### ISSUE THREAD

**Issue by jtaylorchang** [github/codeql#5729]
**Description of the false positive**

This value is set based on a media query inside of a context provider. LGTM claims that the variable always evaluates to true when this is not the case as it is dependent on the user's page width.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/actually-colab/www/snapshot/7f636e6a93fbd7008429098124cc1b7668bb624e/files/src/components/Header.tsx?sort=name&dir=ASC&mode=heatmap#xda8b8788ea49f7bf:2

**Comment by tausbn** [comment]
I have no idea how React works, but it looks to me as if the occurrence of `isMobile` that the alert is attached to is inside the "then" branch of a ternary operator that starts on line 113. The boolean value tested by that ternary operator is _also_ `isMobile`, which is why the alert says that this value can be assumed to be true on line 120. If `isMobile` was false, line 120 would never get executed.
(This assumes `isMobile` isn't changed somewhere along the way, which for all I know might be the case.)

**Comment by jtaylorchang** [comment]
Can't believe I didn't notice that, that's what I get for looking at the few line preview. Thanks for the fresh set of eyes @tausbn
