### ISSUE TITLE
Build Error with C# Unity3D Project

### ISSUE THREAD

**Issue by ekolve** [github/codeql#5753]
I get the following error when lgtm.com attempts to build the C# code in this project: https://github.com/allenai/ai2thor 

The C# code resides under the path `unity/` and it can only be built with the Unity Editor, so I don't believe its an option to get the build to succeed.  Is it possible to still receive analysis of C# project if it can't be built?

[build.log](https://storage.googleapis.com/semmle-oss-live-job-results/jobs/attempt-build/1619132330542/github_apps/allenai/ai2thor/csharp:attempt-builds:3382069452652775475/build.log?GoogleAccessId=semmle-oss-live%40appspot.gserviceaccount.com&Expires=1619220906&Signature=PveRql4DCnUURD1pIBk3ZebgJweahglFbYvo%2FzpALge8RffikL73gfCx2UxMIAkkI%2B4BG6yZ0h%2FonTO%2BMbg3UBLQi%2BQ0r5Ihwzax4Eea%2Bepx6zD04U0qqFNAVudAazRzByycoyAjDhXzmaoja3c7bmyfazN4oOrEcMBUk6Mox0n3xeTc%2BfhFSAYlsgFOaESvxbo8d0QPcLjB%2BbDOmMmExBjSA40wUrwyRDhqjiT442lDTtH4ZjAgLr%2FnkdegJ7D8XP4lQkacTYwxcN4WtEn%2Bd9Ovrqx1FjCfE5B8G7feaJUSdlZLEcr2%2FGuFroqOwvJw1fhhG7tK7ekcThFc8FCDrw%3D%3D&response-content-disposition=attachment%3B+filename%3D%22549df058d4511d86dd5741b00770b0a34b3d8d4e_build.log%22)

**Comment by hmakholm** [comment]
(Note for future readers: the C# autobuilder complains that it cannot auto-detect a suitable build method).

**Comment by hmakholm** [comment]
Unfortunately it looks like you're out of luck, unless you can find a way to compile your `.cs` files with a command-line invocation that CodeQL can snoop on.

I'm assuming that Unity provides some class libraries that your source compiles _against_, such that it won't work simply to write (or generate) a script that invokes `csc` on the input files.

The underlying problem is that CodeQL needs to know at least the signatures of any libraries you _use_, such that it can at least typecheck your C# source; otherwise analysis will be impossible. So if those libraries will only be provided by a tool that cannot run unattended as part of a build process, there's not really a way forward.

**Comment by ekolve** [comment]
I am able to get a SemanticModel of the project using Roslyn with code that resembles the following:

https://github.com/neuecc/MessagePack-CSharp/blob/b652df89bae5e707b7a5184e5464cd2fb2a2d06c/src/MessagePack.Generator/MessagepackCompiler.cs#L86

This has a few dependencies from nuget, but it should be possible to run on Linux.  This would require writing C# code that would then traverse the semantic model to extract method calls.

**Comment by hvitved** [comment]
We do, in fact, use Roslyn for our extractor as well. The issue is that in order to get an accurate CodeQL database, one needs to perform a build of the codebase. During the build, we will detect all calls to the C# compiler (`csc.exe/dll`), and populate the database with only those files/assemblies (including e.g. generated files) passed to compiler calls.

However, from what I can tell, it sounds like building Unity projects requires proprietary tooling that we do not have access to on the LGTM workers. Therefore, you _could_ try out our [buildless extraction](https://lgtm.com/help/lgtm/csharp-extraction#csharp-examples-buildless) mode instead, which simply creates a database by simulating one giant call to the C# compiler with all `.cs` files in the repo. But do note that buildless mode can be much less accurate.

**Comment by ekolve** [comment]
Thank you! That is working for me.
