### ISSUE TITLE
How to improve perfomance of creating database?

### ISSUE THREAD

**Issue by DoonkyDuk** [github/codeql#5761]
I try to create a database for a fairly large project by command: 
  "codeql database create JSDB --language=javascript --threads=16 -v --verbosity=progress++".
But the command didn`t complete in 6 hours and resource monitor shows me that CodeQl.exe has only one active thread.

Is it possible to speed up a creating of database? And do I understand the meaning of the parametr "--threads" correctly?

**Comment by RasmusWL** [comment]
That does sound a bit odd @DoonkyDuk. Is this analyzing an open source project, such that we can try to replicate the behavior? 

otherwise, can you many share what a "fairly large project" means, is it 100k lines, 10 million lines, or 1.000 million lines of JS? and tell us whehter this is a JS or TS project?

And just to double check, what is the output from `codeql --version`? :blush: 

> And do I understand the meaning of the parametr "--threads" correctly?

yes that seems correct to me
