### ISSUE TITLE
DataFlow::CallCfgNode not found in Python documentation index page

### ISSUE THREAD

**Issue by mrthankyou** [github/codeql#5855]
`DataFlow::CallCfgNode` is not found in the Python documentation index page [here](https://codeql.github.com/codeql-standard-libraries/python/). It should be there.

**Comment by hvitved** [comment]
The reason that is does not show up is because the file in which `DataFlow::CallCfgNode` is defined is not visible from `python.qll`, which determines what is shown on the index page. However, you can still find the documentation (https://codeql.github.com/codeql-standard-libraries/python/semmle/python/dataflow/new/internal/DataFlowPublic.qll/type.DataFlowPublic$CallCfgNode.html), just not from the index page.

**Comment by mrthankyou** [comment]
Got it. I'm ok with closing this if you are.
