### ISSUE TITLE
May be a dataflow bug in the catch stmt 

### ISSUE THREAD

**Issue by kingkaki** [github/codeql#5919]
Hey, I wrote a simple null ptr detection, and set `==`  `!=` as barrier, but it seems that when the null literal is in the catch stmt, the node can‘t be properly prohibited.

my code
```java
    private static InetAddress inetAddress;

    public static String getHostName() {
        try {
            if (inetAddress == null) {
                inetAddress = InetAddress.getLocalHost();
            }
        } catch (Exception e) {
            inetAddress = null;
        }

        if (inetAddress != null) {
            return inetAddress.getHostName();
        } else {
            return "localhost";
        }
    }
```

codeql query
```codeql
/**
 * @kind path-problem
 */

import java
import semmle.code.java.dataflow.TaintTracking
import DataFlow::PathGraph

class NullConfiguration extends DataFlow::Configuration {
  NullConfiguration() { this = "config" }

  override predicate isSink(DataFlow::Node sink) {
    any(MethodAccess ma).getQualifier() = sink.asExpr()
  }

  override predicate isSource(DataFlow::Node source) { source.asExpr() instanceof NullLiteral }

  override predicate isBarrier(DataFlow::Node node) {
    exists(EqualityTest eqtest | eqtest.hasOperands(node.asExpr(), any(NullLiteral n)))
  }
}

from DataFlow::PathNode source, DataFlow::PathNode sink, NullConfiguration config
where config.hasFlowPath(source, sink)
select source.getNode(), source, sink, "nullness"
```

It will still be considered a possible null pointer
![image](https://user-images.githubusercontent.com/30930379/118625890-fd0c1080-b7fc-11eb-88c3-cc63462c4adb.png)

**Comment by aschackmull** [comment]
What you see is the combination of a couple of things (and not related to catch statements).
Firstly, because you're using a field rather than a local variable, data flow is allowed to jump more freely from assignments to use, thus skipping your barrier (it is a hard problem to fully correlate field data flow with control-flow in general as we have to account for methods like this being called multiple times and the write-to-read flow may span multiple such calls in general). If you used a local variable, I believe this would have worked.
Second, your barrier can be improved. Currently, you don't distinguish the true-branch from the false-branch. The `Guards` library exists to help with this. There's also a convenience wrapper for the `Guards` library to use in barrier definitions called `BarrierGuard` (see https://github.com/github/codeql/blob/main/java/ql/src/Security/CWE/CWE-022/TaintedPath.ql#L21 for an example).

**Comment by MathiasVP** [comment]
> Second, your barrier can be improved. Currently, you don't distinguish the true-branch from the false-branch. The `Guards` library exists to help with this. There's also a convenience wrapper for the `Guards` library to use in barrier definitions called `BarrierGuard` (see https://github.com/github/codeql/blob/main/java/ql/src/Security/CWE/CWE-022/TaintedPath.ql#L21 for an example).

I was just trying this out myself. The following definition of `isBarrier` works well for me:
```codeql
override predicate isBarrier(DataFlow::Node node) {
  exists(SsaVariable v, Guard guard, boolean isEq |
    v.getAUse() = node.asExpr() and
    guard.isEquality(v.getAUse(), any(NullLiteral n), isEq) and
    guard.controls(v.getAUse().getBasicBlock(), isEq.booleanNot())
  )
}
```

note that you need to import these libraries for this to compile:
```codeql
import semmle.code.java.controlflow.Guards
import semmle.code.java.dataflow.SSA
```

**Comment by aschackmull** [comment]
That barrier also has a slight bug, here's a fixed version:
```
override predicate isBarrier(DataFlow::Node node) {
  exists(SsaVariable v, Expr use, Guard guard, boolean isEq |
    v.getAUse() = use and
    use = node.asExpr() and
    guard.isEquality(v.getAUse(), any(NullLiteral n), isEq) and
    guard.controls(use.getBasicBlock(), isEq.booleanNot())
  )
}
```

**Comment by kingkaki** [comment]
Anyway, this issue seems to be solved, thank you!
