### ISSUE TITLE
Support for Flow type-checking? :)

### ISSUE THREAD

**Issue by chrisbobbe** [github/codeql#6016]
How easy would it be to support [Flow](https://flow.org/) in JavaScript? 🙂 Currently I'm getting some syntax errors flagged:

https://lgtm.com/projects/g/zulip/zulip-mobile/snapshot/929aa1172864708f4cb7de6ea54df84b3235035d/files/src/common/Icons.js?sort=name&dir=ASC&mode=heatmap#xbe98651ddf509ad2:1

**Comment by rdmarsh2** [comment]
Hi Chris,

We do already support Flow, but this looks like a bug in our parser's handling of nested generics. @esbena, have you seen this before?

**Comment by esbena** [comment]
This is a known limitation of our parser's handling of flow generic syntax. 

There is an inherent syntactic ambiguity between JSX syntax and Flow syntax that we do not disambiguate since it generally requires unbounded lookahead. We are aware that other parsers handles the ambiguity by explicitly preferring one syntax over the other. We are not currently planning to fix this parser limitation.

---

IIRC, the ambiguity only occurs for type-parameterized lambdas, and the recommended fix is a syntactic rewrite using function types instead.
