### ISSUE TITLE
Serializing/deserializing C++ functions

### ISSUE THREAD

**Issue by automatedbugreportingfacility** [github/codeql#6019]
I have a chain of C++ queries that look for `Functions`. Each subsequent query depends on the results of all of the queries already resolved. Therefore, I'm looking for an efficient way to store the results (i.e. Functions) to reference in future queries.

I used to treat the output of `Function.getQualifiedName()` as an identification key for a `Function`, but that was both:

1) Slow: calling `getQualifiedName()` takes time;
2) Not 100% accurate: occasionally, the analysis may encounter a function whose qualified name does not uniquely identify it. For example, there might be another function with the same qualified name, but different parameters. Of course, there's `getIdentityString()`, but using that would be **SUPER**-slow.

I've glanced through the database schema and found this:

```
functions(
    unique int id: @function,
    string name: string ref,
    int kind: int ref
);
```

Referencing a Function with a unique id should fix both problems outlined above: it'd be really fast and 100% accurate. Is there any way in QL to derive the id from a `@function` (to serialize a Function), and the `@function` from an id (to deserialize it)? If that's impossible to do in QL, is there any recommended way to interface directly with the database to work with it? I think I could extract the necessary information with bare SQL.

In case you're wondering about the use case for all of this: due to the sheer size of the code database, it's way too computationally intensive to derive the expected results in one go -- the results must be stored externally in an incremental manner to allow stopping and resuming the analysis at any given moment, without the need to restart from scratch. Additionally, queries are modified and adjusted as the available result set grows in size.

**Comment by rdmarsh2** [comment]
There's no way to interact directly with those IDs - from the QL language's view, they're opaque identifiers and can't be serialized or deserialized, and the database uses a custom format.

However, there are better approaches to solving performance problems than serializing and deserializing. The CodeQL engine maintains a working cache of evaluated predicates in the database directory, and predicates marked with the `cached` annotation will be kept in the cache even when they'd normally be cleared. Additionally, if you need to reduce the size of the database, the cache can be cleared of all predicates that aren't explicitly marked by using the `codeql database cleanup` command. You might need to refactor some of your existing queries so that the most relevant computations can be the results of cached predicates rather than select clauses.

As a side note, the `getQualifiedName()` predicate performs poorly when used in this direction. We recommend the three-argument form of `hasQualifiedName()`, which doesn't need to construct nearly as many intermediate strings.

**Comment by automatedbugreportingfacility** [comment]
Thank you for the answer and the performance tips. I think some analysis scenarios would greatly benefit from exposing IDs (especially when the expected result of the analysis does not correspond to any of the formats that QL natively supports), but I also understand if it goes against some of the basic principles and goals that your project aims to follow.
