### ISSUE TITLE
Issue with getting callee recursively from method

### ISSUE THREAD

**Issue by navyasri1** [github/codeql#6060]
I am trying to get all the methods from a method recursively by calling `getACallee*()` but the results stop at `.execute` in the below code and does not go into it and give `apply` and `test1` in the output. I am interested to know if there's any way to get these. 

```
public void Test(Group ptGroup) throws CommonFrameworkException, SQLException {
       final Class1 input =new Class1();
       input.setV1(v1);
  Dispatcher.execute(input,
               new CheckedFunction<Class1,
                       Void, CommonFrameworkException, SQLException>() {
           @Override
           public Void apply(Class1 daoInput) throws CommonFrameworkException, SQLException {
               test1(daoInput);
               return null;
           }
       }, Void.class);
```

**Comment by intrigus-lgtm** [comment]
(It might be good if you could share the context in which you need this, if there is one)

To answer your question, let's first rewrite your code example:
```java

private static final CheckedFunction function = new CheckedFunction<Class1,
                       Void, CommonFrameworkException, SQLException>() {
           @Override
           public Void apply(Class1 daoInput) throws CommonFrameworkException, SQLException {
               test1(daoInput);
               return null;
           }
       };
public void Test(Group ptGroup) throws CommonFrameworkException, SQLException {
       final Class1 input =new Class1();
       input.setV1(v1);
       Dispatcher.execute(input, function , Void.class);
```

Maybe the problem is more clear now:
The only functions that can be **directly** called inside of function `Test` are `setV1` and `execute`.
The method call stack `apply` -> `test1` is hidden inside `function`!
So `Test` -> `execute` only **indirectly** calls `apply` -> `test1`, because inside of `execute` `function.apply` is called.

If the source code of `Dispatcher` is available an analysis could *maybe* automatically determine that `Dispatcher.execucte` always executes its second (one-based) parameter and therefore conclude that `Test` -> `execute` -> `apply` -> `test1` is a valid call stack.
But I don't think that this is possible in the general case, `Dispatcher.execute` could for example also simply throw away the `function` it gets passed.

You could of course manually specify the behavior of `Dispatcher.execute` and similar functions.

**Comment by ngoclong19121990** [comment]
Ok

0921757857

Vào 08:47 AM, T.5, 8 Th7, 2021 github-actions[bot] ***@***.***>
đã viết:
