### ISSUE TITLE
LGTM.com - Python false positive

### ISSUE THREAD

**Issue by noonchen** [github/codeql#6065]
**Description of the false positive**

Illegal class 'NoneType' raised; will result in a TypeError being raised instead.

A if statement is used for preventing None being raised.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/noonchen/STDF-Viewer/snapshot/cd9ec300e3b310d1bbbedb9f4713352055e91553/files/deps/stdfOffsetRetriever.py?sort=name&dir=ASC&mode=heatmap#x7d17443ffab930e9:1

**Comment by tausbn** [comment]
Thank you for your report! I'm not entirely convinced that this is a false positive.

While you are correct that you're guarding against raising `None`, what the alert is actually saying is that you might raise `NoneType` (that is, the class you get from e.g. `type(None)`). It's not immediately clear to me where this `NoneType` may be coming from, but either way it would not be guarded against by a check on `None`.

I'm also not entirely sure what the code is actually supposed to do. I tried recreating it with a small example, and what ends up in `self.error` looks surprising to me. Consider the following snippet of code
```python
import sys

class MyClass():
    def __init__(self):
        self.error = None
        sys.excepthook = self.onException
    def onException(self, eT, eV, tb):
        self.error = eT(eV)
    def explode(self):
        raise Exception("Argh")
```
If I now do `a = MyClass()` followed by `a.explode()`, I end up with `a.error` having the value `Exception(Exception('Argh'))`. The inner exception becomes wrapped in another instance of that exception type. Is this intended? 
It seems to me like you might want to do `self.error = eV` instead of adding the extra layer by doing `eT(eV)`, but I haven't looked at the greater context of this piece of code.

I haven't been able to recreate it, but I _think_ this is how our analysis thinks `NoneType` can creep in.

**Comment by noonchen** [comment]
Hi @tausbn,

> I'm also not entirely sure what the code is actually supposed to do. I tried recreating it with a small example, and what ends up in `self.error` looks surprising to me. Consider the following snippet of code
> 
> ```python
> import sys
> 
> class MyClass():
>     def __init__(self):
>         self.error = None
>         sys.excepthook = self.onException
>     def onException(self, eT, eV, tb):
>         self.error = eT(eV)
>     def explode(self):
>         raise Exception("Argh")
> ```

This piece of code is used for catching exceptions on threads & processes and `raise` them on the main thread for error handling. Your example code might help me to locate a bug! (although I avoided it by using `cython` 😊).

As for the possible false positive.
```
threading.excepthook = self.onThreadException

def __init__(self):
    self.error = None
    ....

def onThreadException(self, hookArgs):
    eT = hookArgs.exc_type
    eV = hookArgs.exc_value
    self.error = eT(eV)

def checkError(self, process_task):
    if self.useThread:
        if not self.error is None:
            raise self.error
```
The code above is the simplified version of the original code. If there is an exception on threads, `self.error` will be assigned to `exc_type(exc_value)`, otherwise `self.error` is `None` and it will not be `raise` due to the if clause. I don't see why a NoneType might be raised.

**Comment by tausbn** [comment]
So I tried downloading your code to run an analysis, and to my surprise the alert is no longer there! I see that you changed it a while ago to not use this construction. (Thanks for raising this issue anyway, though.)

Incidentally, it looks to me like the simplified version above still would result in "doubled" exceptions (e.g. `Exception(Exception("Argh"))`). I'm not sure why it doesn't just say `self.error = eV`.

Anyway, as this is not an issue that is actively affecting you, we will be adding it to our backlog and revisit it at a future date.

**Comment by noonchen** [comment]
> Incidentally, it looks to me like the simplified version above still would result in "doubled" exceptions (e.g. `Exception(Exception("Argh"))`). I'm not sure why it doesn't just say `self.error = eV`.
> 

The double exception will not be occurred in the simplified version, because `sys.excepthook` is not used.

`threading.excepthook` can only catch unhandled exceptions in python threads, main thread error will not active the `onThreadException` callback function :).
