### ISSUE TITLE
General issue: Error was: Unknown kind "Diagnostic" when converting to analysis model. [UNSUPPORTED_KIND]

### ISSUE THREAD

**Issue by huornlmj** [github/codeql#6093]
**Description of the issue**

I scanned a Go repo with go-lgtm-full.qls and obtained a sarif report.  I then tried another suite (go-code-scanning.qls) on the same repo and got this error:

```
A fatal error occurred: Could not process query metadata for /home/user/codeql-home/codeql-go/ql/src/Diagnostics/SuccessfullyExtractedFiles.ql.
Error was: Unknown kind "Diagnostic" when converting to analysis model. [UNSUPPORTED_KIND]
```

**Comment by tausbn** [comment]
Thank you for your report!

This is caused by the presence of queries in the current `main` branch of `github/codeql` that are incompatible with version 2.5.5 and below of the CodeQL CLI. These will be supported in version 2.5.6 which should be released soon.

In the meantime, you can use the queries in [the tag `codeql-cli/v2.5.5`](https://github.com/github/codeql/releases/tag/codeql-cli%2Fv2.5.5), as these are guaranteed to be compatible with version 2.5.5.
