### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by IlmastroStefanuzzo** [github/codeql#6281]
**Used import marked as unused**

The import "maps" is being used, but lgtm doesn't detect that because it's being used inside of an exec()

https://lgtm.com/projects/g/IlmastroStefanuzzo/py_cli_snake/snapshot/92b54564a95d46b35bc6b9cfe910b7061cb1e717/files/main.py?sort=name&dir=ASC&mode=heatmap#xd1a82bfc7e7c2ff1:1

**Comment by tausbn** [comment]
Thank you for your report! We don't currently support inspecting the strings passed to `exec` and `eval` to see whether the code contained therein mentions things like modules that are otherwise unmentioned.

However, in this case it seems to me that `exec` is a pretty big hammer to apply to this problem, and that an easier solution may be possible. Something like
```python
while running:
    try:
        map = getattr(maps, f"map{count}")
        output.append(f"{count}) {map[0]}")
        count += 1
    except (AttributeError, IndexError):
        running = False
```
should probably do the trick.

**Comment by IlmastroStefanuzzo** [comment]
Alright
```python
    while running:
        try:
            output.append(f"{count}) " + getattr(maps, f"map{count}")[0])
            count += 1
        except AttributeError:
            running = False
```
Thanks.
