### ISSUE TITLE
Detecting SQL injection in MongoDB

### ISSUE THREAD

**Issue by doug-papenthien-by** [github/codeql#6328]
Is CodeQL able to find code vulnerable to SQL injection when using MongoDB?  I found #3542 where some sinks were added to detect this sort of thing.  However, I'm very new to CodeQL.  Based upon my limited understanding, it looks this change will only flag code that uses specific MongoDB objects / functions - specifically `com.mongodb.util.JSON`.

The reason I ask is that `com.mongodb.util.JSON` is deprecated and was removed from the driver as of version 4.0.

**Comment by MathiasVP** [comment]
Hi @doug-papenthien-by,

As far as I know, the short answer to:
> Is CodeQL able to find code vulnerable to SQL injection when using MongoDB?

is yes. The slightly longer answer is that, CodeQL is able to (at least) find code vulnerable to SQL injections when your program looks like:

```java
import com.mongodb.MongoClient;
import com.mongodb.DBObject;
import com.mongodb.util.*;
import com.mongodb.ServerAddress;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.*;

public class Mongo {
    public static void main(String[] args) {
        MongoClient mongoClient = new MongoClient(new ServerAddress("localhost", 27017));
        DB db = mongoClient.getDB("mydb");
        DBCollection collection = db.getCollection("test");

        String name = args[1];
        String stringQuery = "{ 'name' : '" + name + "'}";
        DBObject databaseQuery = (DBObject) JSON.parse(stringQuery);
        DBCursor result = collection.find(databaseQuery);

        String json = args[1];
        BasicDBObject bdb = BasicDBObject.parse(json);
        DBCursor result2 = collection.find(bdb);

    }
}
```
which is the testcase that was added in https://github.com/github/codeql/pull/3542. In this case, CodeQL finds two injection vulnerabilities:
```
| Mongo.java:17:45:17:67 | parse(...) | Mongo.java:10:29:10:41 | args : String[] | Mongo.java:17:45:17:67 | parse(...) | Query might include code from $@. | Mongo.java:10:29:10:41 | args | this user input |
| Mongo.java:21:49:21:52 | json | Mongo.java:10:29:10:41 | args : String[] | Mongo.java:21:49:21:52 | json | Query might include code from $@. | Mongo.java:10:29:10:41 | args | this user input |
```

> Based upon my limited understanding, it looks this change will only flag code that uses specific MongoDB objects / functions - specifically com.mongodb.util.JSON.
>
> The reason I ask is that com.mongodb.util.JSON is deprecated and was removed from the driver as of version 4.0.

That specific PR added an additional taint step through `com.mongodb.util.JSON`, yes. This is why we get flow from `stringQuery` to `databaseQuery` in this line:
```java
DBObject databaseQuery = (DBObject) JSON.parse(stringQuery);
```
If you do find a case where we don't find the SQL injection vulnerability because we fail to track the flow through specific MongoDB objects and methods, feel free to open an issue (or even create a PR with a fix!)

Does this answer your question(s)?

**Comment by smowton** [comment]
Regarding JSON.parse, note that the second result shows detection of `BasicDBObject.parse`, which is the suggested replacement for JSON.parse.

**Comment by doug-papenthien-by** [comment]
Thanks for the detailed response.  It was very helpful.  I can confirm that when intentionally adding code to our repo for `BasicDBObject.parse`, it is flagged by CodeQL.

One issue we were having was that CodeQL wasn't annotating our pull requests due to a GitHub Action issue.  So it wasn't clear whether or not CodeQL was working properly until we worked that out.
