### ISSUE TITLE
LGTM.com - false positive Sensitive data (id)

### ISSUE THREAD

**Issue by Jonasslv** [github/codeql#6363]
**Description of the false positive**

It's not personal information, it's just a log of various public transactions from a blockchain.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/rotki/rotki/snapshot/dd27a3a5063f6829d378143cfcbad687572b8ddd/files/rotkehlchen/externalapis/covalent.py?sort=name&dir=ASC&mode=heatmap#x172e47359ff05f39:1

**Comment by yoff** [comment]
Hi @Jonasslv, thank you for the report. It looks like you are correct and this is a false positive caused by our heuristic for identifying sensitive sources (the argument to `get_transactions` is called `account`). I am not sure how we could identify sensitive information in a robust way without user annotation, so we are using variable names as a kind of user annotation here. If you can rename the argument to `get_transactions`, say to `checksum`, the alert should go away.
