### ISSUE TITLE
LGTM.com - false positive Class may not be initialized properly

### ISSUE THREAD

**Issue by BoYanZh** [github/codeql#6381]
**Description of the false positive**

`super().__init__` is called in `BaseError.__init__`

**URL to the alert on the project page on LGTM.com**

<https://lgtm.com/projects/g/joint-online-judge/horse/snapshot/556f8f0d38df6e88a1eac9dccde5d9c9daf85825/files/joj/horse/utils/errors.py?sort=name&dir=ASC&mode=heatmap#x2a5cec943c74c9ef:1>

**Comment by aeisenberg** [comment]
Thank you for your issue. It does appear to be a false positive.

Our current focus is on improving our security analysis. Because your report does not relate to a security query, we will put this on our backlog and prioritize it if we get enough reports of the same underlying issue in other projects. If you think that your report is related to our security analysis, please clarify that in a comment. Either way, we'll let you know here as soon as it's fixed!

If this query is bothering you too much, LGTM.com have facilities for suppressing individual alerts or disabling a query.
