### ISSUE TITLE
regexpMatch()

### ISSUE THREAD

**Issue by xiaoxinz-cisco** [github/codeql#6479]
Hi,

I'm using `regexpMatch()` while analyzing C code, but there's no matched result even the pattern is correct.

For example, in my C code:
```
 MY_FUNC(ARG0, ARG1, NULL,
 "\n%sDoor %s is open", arg4, arg5->arg6); 
```

The query I created is:
```
import cpp
from FunctionCall fc, int i
where
    fc.getArgument(i).getValue().regexpMatch("\n%sDoor %s is open")
select fc, "Function: "+fc.getTarget().getName()+" Log: "+fc.getArgument(i).getValue()
```
when I test on LGTM, `"\n%sDoor %s is open"` shows 'invalid', the errors are 
```
missing ')' at '%'
missing 'select' at 'sis'
```
it's hard to tell how to fix the pattern. 

I test the pattern on regex101.com, which has no issue.

So what regex language does codeql use? and how to write the correct query in this case.

Thanks in advance!

**Comment by Marcono1234** [comment]
> when I test on LGTM, `"\n%sDoor %s is open"` shows 'invalid', the errors are

Cannot reproduce; [this query](https://lgtm.com/query/8974950676812199031/) compiled without any issues. Do you maybe copied by accident some invisible characters which could be causing the errors?

CodeQL uses Java's [`Pattern`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html) syntax; regex101 also supports that since a few months.
The regex pattern you wrote looks fine to me, though it appears that it does not use any regex functionality, the `\n` is already converted to a LF by the CodeQL string literal (see [language specification](https://codeql.github.com/docs/ql-language-reference/ql-language-specification/#string-literals-string)). So instead of using `regexpMatch("...")` you could just compare the string directly: `= "..."`

Maybe the maintainers have an idea what could be causing this issue.

**Comment by xiaoxinz-cisco** [comment]
Thanks, let me give you more details.

There's a line of code in sample project 'fish-shell/fish-shell': `b.append_format(_(L"(Type 'help %ls' for related documentation)\n"), cmd);`

How to write a regex to match string `"(Type 'help %ls' for related documentation)\n"`?

In regex101, `\(Type.*` matches, but it doesn't work in codeql

fish-shell/fish-shell: https://lgtm.com/projects/g/fish-shell/fish-shell/?mode=list

**Comment by RasmusWL** [comment]
Hi @xiaoxinz-cisco, you should use `\\(` instead of `\(` since the fact that this string is sent to Java requires an other layer of regex-escaping.

For example, to reproduce the Python regex [`'<(?:(?P<converter>[^>:]+):)?(?P<parameter>\w+)>'`](https://github.com/django/django/blob/7d1bf29977bb368d7c28e7c6eb146db3b3009ae7/django/urls/resolvers.py#L199) we had to write [`"<(?:(?<converter>[^>:]+):)?(?<parameter>\\w+)>"`](https://github.com/github/codeql/blob/55d822cc56ac6c9cba2614636320e52c9daeac86/python/ql/src/semmle/python/frameworks/Django.qll#L1700)

**Comment by xiaoxinz-cisco** [comment]
Thanks @RasmusWL , what are the reasons the below patterns failed?
```
"\\(Type \\'.*"
```
```
"\\(Type\\s\\'.*"
```
```
"\\(Type '.*"
```

**Comment by Marcono1234** [comment]
Note that with Java's `Pattern` `.` by default does not match line terminators. Because the string you want to match contains a LF (`\n`) it will therefore not match.
You have to prefix the pattern with [`(?s)`](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/util/regex/Pattern.html#DOTALL) to make `.` match line terminators as well:
```ql
regexpMatch("(?s)\\(Type.*")
```
([Query console link](https://lgtm.com/query/5394887911646647527/))

However, if you only check for a prefix you could use CodeQL's [`indexOf`](https://codeql.github.com/codeql-standard-libraries/cpp/predicate.string$indexOf.1.html) (or [`matches`](https://codeql.github.com/codeql-standard-libraries/cpp/predicate.string$matches.1.html)) predicate as well:
```ql
indexOf("(Type") = 0
```
([Query console link](https://lgtm.com/query/7714314031675857594/))

**Comment by RasmusWL** [comment]
Thanks @Marcono1234 for highlighting that part about Java's pattern and line terminators :+1: 

I would strongly recommend you use `matches("<...>%")` instead of `indexOf("<...>") = 0`, since it's a bit faster to evaluate the `matches`.

**Comment by xiaoxinz-cisco** [comment]
Thanks @RasmusWL @Marcono1234 , is the regex rules in codeql documented somewhere? such as the specific Java pattern and line terminators rule.

**Comment by Marcono1234** [comment]
If I understand it correctly, CodeQL is _exactly_ using Java's [`java.util.regex.Pattern`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html), so everything described in its documentation applies to CodeQL as well.
The CodeQL predicate documentations (for example for [`regexpMatch`](https://codeql.github.com/codeql-standard-libraries/cpp/predicate.string$regexpMatch.1.html)) and the CodeQL [language specification](https://codeql.github.com/docs/ql-language-reference/ql-language-specification/#built-ins-for-string) also refer to Java's `Pattern`, and this applies regardless of scanned programming language.

**Comment by RasmusWL** [comment]
Yep, at the bottom of the table [here](https://codeql.github.com/docs/ql-language-reference/ql-language-specification/#built-ins-for-string), it says:

> Regular expressions are as defined by java.util.regex.Pattern in Java. For more information, see the Java API Documentation.
