### ISSUE TITLE
Java: More details about nested arrays

### ISSUE THREAD

**Issue by artem-smotrakov** [github/codeql#6552]
Given a multi-dimensional array, the extractor doesn't seem to provide enough information about nested sub-arrays.

For example:

```java
public class Test {

    void test() {
        byte[][] array = new byte[][] {
            new byte[] { 1, 2 },
            new byte[] { 3, 4 ,5 }
        };
    }
}
```

The following query shows only `IntegerLiteral` and `TypeAccess` for the nested arrays:

```ql
import java

from ArrayCreationExpr array
select array.getInit().getAnInit().getAChildExpr().getAPrimaryQlClass()
```

Instead, `ArrayCreationExpr` should be used to represent the nested arrays, shouldn't it?

This issue was found [here](https://github.com/github/codeql/pull/6357#discussion_r688717982).

**Comment by smowton** [comment]
Fixed in the next release: for the best backward compatibility, the representation will be somewhat irregular:

| Syntax | Nested context (e.g. `{ { 1, 2 } }`) | Non-nested context (e.g. `byte[] bs = new byte[10]`) |
| `new byte[10]` | `ArrayCreationExpr` | `ArrayCreationExpr` |
| `new byte[] { 1 }` | `ArrayInit` | `ArrayCreationExpr` (with a `getInit`) |
| `{ 1, 2, 3 }` | `ArrayInit` | `ArrayCreationExpr` (with a `getInit`) |
