### ISSUE TITLE
Add support for jdk17

### ISSUE THREAD

**Issue by aromanet42** [github/codeql#6719]
**Description of the issue**

JDK 17 just got out, and we are trying it in some of our projects.

When running codeql, we have an issue

```
ERROR: Exception while processing java/lang/Shutdown: java.lang.IllegalArgumentException: Unsupported class file major version 61
java.lang.IllegalArgumentException: Unsupported class file major version 61
	at com.semmle.org.objectweb.asm.ClassReader.<init>(ClassReader.java:189)
	at com.semmle.org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
	at com.semmle.org.objectweb.asm.ClassReader.<init>(ClassReader.java:156)
	at com.semmle.extractor.java.InterceptingAgent.transform(InterceptingAgent.java:271)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
```

Would it be possible to have an estimated date for java 17 compatibility?

Thanks

**Comment by aromanet42** [comment]
@aibaars thanks for the quick response!

I indeed use an outdated version (2021 march). According to your documentation, jdk 17 is not supported: https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/

I will try using the most recent version.

**Comment by aibaars** [comment]
> I indeed use an outdated version (2021 march). 

That's too old. Let us know if the latest version (2.6.1) works, that version should have basic support for building databases using the JDK 17 compiler. 

> According to your documentation, jdk 17 is not supported: https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/

You're right that the documentation does not yet mention Java 17 as supported language. This is likely because we haven't updated the CodeQL queries and libraries yet to cover the new language features offered by Java 17. This is generally fine (perhaps an occasional bad or missing result) unless your code uses the new language features extensively. Full support should be released in the near future, but I don't know a date.

**Comment by aromanet42** [comment]
@aibaars it works with the latest version. I should have tested before opening an issue, sorry.

I think this issue can be closed, although it would be a good idea to update the documentation :)

Thanks again

**Comment by aibaars** [comment]
No problem! Glad it works now. Let us know if you run into any issues.
