### ISSUE TITLE
Question about `regexpMatch` predicate

### ISSUE THREAD

**Issue by ananya-cisco** [github/codeql#6742]
**Regular Expression doesn't provide expected output for a Macro Invocation Argument**

I am running the following query to filter out arguments of a Macro Invocation containing `0x%x`. The output is empty, even when the substring is present in the macro invocation argument. Can you please provide guidance to achieve this goal?

```
from MacroInvocation mi, int i
where mi.getUnexpandedArgument(i).regexpMatch("0x%x")
select  mi, mi.getUnexpandedArgument(i)
```

Example of Macro and its invocation in code - 
```
#define DEBUG_LOG(msg, args...)
DEBUG_LOG("\n%s: failed to register callback for "
                         "function %s rc:0x%x", __FUNCTION__,
                         ERROR_NOTIF, rc);
```

Example of unexpanded argument without regexpMatch -
`\"\\n%s: failed to register callback for \" \"function %s rc:0x%x\"\n__FUNCTION__, ERROR_NOTIF, rc\n&debug_flags`

**Comment by alexet** [comment]
`regexpMatch` matches the regexp against the whole string rather than looking for a match as a substring. You can either transform your regexp to `".*0x%x.*"` to allow any prefix or suffix or use a different predicate that looks for substrings that match (e.g `exists(mi.getUnexpandedArgument(i).regexpFind("0x%x", _, _))`)

**Comment by ananya-cisco** [comment]
Thank you @alexet . Using `",*0x%x.*"` works.
