### ISSUE TITLE
CWE number mistake

### ISSUE THREAD

**Issue by tszdanger** [github/codeql#6805]
**Description of the issue**

In[CWE570]( https://github.com/github/codeql/tree/main/cpp/ql/src/Security/CWE/CWE-570), we can find that it's for Incorrect All ocation Error Handling.

However, I think the CWE-570 is for the question  **Expression is always False**, which can be found on [CWE WEB](https://cwe.mitre.org/data/definitions/570.html)

**Comment by MathiasVP** [comment]
Hi @tszdanger,

Thanks for reporting this. The query in question actually _does_ find expressions that are always false. Consider this example, which is flagged by the query:

```cpp
void do_allocation() {
  int* p = new int;
  if(!p) { /* handle allocation error */ }
}
```

The expression that guards `/* handle allocation error */` is actually always false, since `p` is guaranteed to be non-null unless the `std::nothrow` variant of `operator new` is used.

So I think `CWE-570` is appropriate for the query. However, I think we should be able to find a couple more appropriate CWEs for this query. I'll discuss this with the rest of the team and let you know once we've decided on which CWEs we should add to the query :)

**Comment by MathiasVP** [comment]
https://github.com/github/codeql/pull/6808 adds tags for [CWE-252: Unchecked Return Value](https://cwe.mitre.org/data/definitions/252.html) and [CWE-755: Improper Handling of Exceptional Conditions](https://cwe.mitre.org/data/definitions/755.html).
