### ISSUE TITLE
C/C++: LGTM.com run failed on PR but CI succeeds after changes to CMakeLists.txt

### ISSUE THREAD

**Issue by VolkerEnderlein** [github/codeql#7055]
After changes to a CMakeLists.txt an LGTM.com run on the PR failed, but all other GitHub CI runs succeeded. 

The `execute_process` commands are needed to query qmake for `QT_INSTALL_PREFIX` and `QT_INSTALL_PLUGINS` but they do not populate the CMake variables. The build log at line 577 shows that.

See [here](https://lgtm.com/projects/g/coin3d/quarter/rev/pr-d2109b1696bfd43eadfea16e9a63fa04055d56ac) for additional information (build logs etc.).

**Comment by adityasharad** [comment]
Thanks for the report and the investigation you've carried out already. From a brief look it does indeed look like our `qmake-wrapper` is redirecting stdout from `qmake` to its own stderr instead of stdout. I've mentioned this to our CodeQL C/C++ team, will report back next week once we have an idea of what we can change here.

**Comment by podsvirov** [comment]
Three week later...

Hello to all! Any news there?

**Comment by VolkerEnderlein** [comment]
@adityasharad Any news on the issue?

**Comment by adityasharad** [comment]
The `qmake-wrapper` used in the container images on LGTM.com has been updated to fix this problem. Thanks for your patience. Please reopen this and let us know if you continue to see the problem!

**Comment by podsvirov** [comment]
Good news, will check at new case!

**Comment by VolkerEnderlein** [comment]
Thanks @adityasharad we'll try the updated version.
