### ISSUE TITLE
General issue - [JavaScript] Incomplete string escaping or encoding

### ISSUE THREAD

**Issue by a-tarasyuk** [github/codeql#7079]
**Description of the issue**

The following case raises an error 
```shell
Incomplete string escaping or encoding
This does not escape backslash characters in the input
```

```ts
text.replace(/\$/gm, "\\$");
```

`text` can contain `$`  that should be replaced by `\$`.

```ts
Input: `"string $ $"`
Outptut: `"string \$ \$"`
````

I think the following rule handles this case
https://github.com/github/codeql/blob/90bebaa5a9a34265ccdf25d3003eaf0f23d2f1a7/javascript/ql/src/Security/CWE-116/IncompleteSanitization.ql#L54-L64

Is there any "safe" way to use `$` in replace?

**Comment by tausbn** [comment]
Thank you for your question!

I'm a bit unsure what it is you're asking here. Are you asking why it flags up that particular piece of code as unsafe, or are you asking how to write such a string escaping in a safe manner?

If it's the first question, then my understanding is that simply turning `$` into `\$` is insufficient because there may already be a `\` in front of the `$`. If we only do this single escape, then `\$` is turned into `\\$`, i.e. an escaped backslash followed by an _unescaped_ `$`, which is bad.

If you're asking how to do this safely, then our best suggestion is to use an external, well-tested library for string escaping, as the corresponding [documentation](https://codeql.github.com/codeql-query-help/javascript/js-incomplete-sanitization/) for this query also states.

**Comment by a-tarasyuk** [comment]
@tausbn Thanks for the explanation. I would say - both questions :). 

> If it's the first question, then my understanding is that simply turning $ into \$ is insufficient because there may already be a \ in front of the $. If we only do this single escape, then \$ is turned into \\$, i.e. an escaped backslash followed by an unescaped $, which is bad.

Is it ok to use `\b` to match only `$`? It is safe?

**Comment by tausbn** [comment]
> Is it ok to use `\b` to match only `$`? It is safe?

I am not familiar enough with JavaScript to give you an answer for this, I'm afraid. My best suggestion would be to use a library for all your string-escaping needs, rather than attempt to roll your own solution.
