### ISSUE TITLE
[JavaScript] Another limited case for tainting objects with methods

### ISSUE THREAD

**Issue by xiaofen9** [github/codeql#7106]
Hi,

I would like to report another taint tracking false negative in JavaScript.
Similar to https://github.com/github/codeql/pull/7083, it also relates to objects with methods. However, it is not the same bug (the patch cannot resolve this case). 

CodeQL ***can*** find the sink in `objectA`, which is expected. However, it ***cannot*** identify the same sink if I put the object into a function (i.e., `objectB` in `factory()`).

buggy.js (assuming `console.log` is the sink)
```
var objectA = function(){
    return {};
}

objectA.set = function (obj){
    console.log(obj);
};



function factory() {
    var objectB = function(){
        return {};
    }


    objectB.set = function (obj){
        console.log(obj);
    };
    return objectB;
}


objectA.set(source);

b = factory();
b.set(source)
```

**Comment by esbena** [comment]
The described pattern is related to the limitations mentioned in #7083. 
Fundamentally, the core analysis is neither sound or complete, so it is not surprising that corner cases can be found where improvements are desirable. As such, we do not consider this a "bug", but rather a pragmatic limitation.

With that said, the described pattern seems reasonable to add support for since it is both relatively simple and likely to be common in practice.
If you are up for it, we would welcome a QL query that finds the factory pattern in some large projects (preferably just a link to the query console on LGTM.com), as that would give us a better idea of how important this is to add support for.

**Comment by xiaofen9** [comment]
Hi, the factory pattern is quite common. For example, [object-path](https://www.npmjs.com/package/object-path) (weekly downloads 3million+) uses [`factory()`](https://github.com/mariocasciaro/object-path/blob/e6bb638ffdd431176701b3e9024f80050d0ef0a6/index.js#L316) to produce a configured object with function members. 

As described in the issue, CodeQL cannot perform taint-tracking in such libraries (I've run taint-tracking on object-path). 
Please consider fix such cases. Thanks! @esbena

**Comment by xiaofen9** [comment]
Any updates on this issue? thanks

**Comment by asgerf** [comment]
It is being worked on; we're in the process of testing on a large number of projects and will move ahead if the results look good.

**Comment by asgerf** [comment]
Sorry for the wait, PR is open now https://github.com/github/codeql/pull/7409
