### ISSUE TITLE
Any way to debug with codeql

### ISSUE THREAD

**Issue by SZFsir** [github/codeql#7153]
Hi, these days I use codeql to test some large javascript projects.  These programs are not always elegantly written, so codeql sometimes could not handle some strange source code. 

In this situation, We are hard to figure out where codeql lost the data flow or the call graph in a large codebase. so I want to ask if there exists a proper way to debug with codeql to let us get more data through the query execution. 
Thanks.

**Comment by hvitved** [comment]
Hi

CodeQl does not have a debugger, but typically what you can do is write temporary debug predicates (or use existing predicates) and then quick-eval those in VS Code (put the curser on the predicate name and run the command `CodeQL: Quick Evaluation`).

For data-flow specifically, you can either
```ql
import semmle.javascript.explore.ForwardDataFlow
```
or
```ql
import semmle.javascript.explore.BackwardDataFlow
```
into a data flow query in order to perform either forwards (or backwards) flow exploration. The documentation inside those library contains more details.

**Comment by SZFsir** [comment]
Thank you for your answer, It helps a lot!
