### ISSUE TITLE
[JavaScript] Repeated invocations leads to type tracking false negatives

### ISSUE THREAD

**Issue by xiaofen9** [github/codeql#7261]
Hi,

I would like to report a weird false-negative case in JavaScript type tracking. 
As shown in the following PoC, CodeQL can correctly report `cb()` as a source node with a summary of `type tracker without call steps`. Hence, it can detect the data flow into sink `readFile`.
However, if the last line is uncommented (the same invocation), `cb()` will no longer be reported, and thus no sink is detected.

According to my understanding, type tracking performs certain intersection operations internally when deciding whether a source node has a certain type. Could you help me confirm whether my understanding is correct or not and explain why the repeated invocations lead to the false negative?
If possible, could you also give me some code pointers for the internal implementation of type tracking behind [TypeTracking.qll](https://github.com/github/codeql/blob/main/javascript/ql/lib/semmle/javascript/dataflow/TypeTracking.qll)?  I am very interested in learning more about CodeQL. Thanks a lot!

``` 
import myapi from "@test/easysource";
import fs from 'fs';

function foo(cb){
    fs.readFile(cb());
}


let source = new myapi();
foo(function() { return source });
// foo(function() { return source }); 
```
Below is the query I used.
```
import javascript

query DataFlow::SourceNode easySourceTracker(DataFlow::TypeTracker t) {
    t.start() and
    result = DataFlow::moduleImport("@test/easysource").getAnInstantiation()
    or
    exists(DataFlow::TypeTracker t2 | 
      result = easySourceTracker(t2).track(t2, t))
  }
  
 DataFlow::SourceNode easySourceTracker() { result = easySourceTracker(DataFlow::TypeTracker::end()) }
```

**Comment by aeisenberg** [comment]
Thank you for your question. I asked our JavaScript team to take a look and someone will respond to you shortly.

**Comment by erik-krogh** [comment]
The reason for the difference is that we only do type-inference for functions that are only used exactly once. 
The callgraph uses type-inference, and type-tracking uses the callgraph. 
The relevant class in type-inference is called [LocalFunction.](https://github.com/github/codeql/blob/b40c77d4195cf87cb957c7841d919c48d1c183bf/javascript/ql/lib/semmle/javascript/dataflow/internal/InterProceduralTypeInference.qll#L194).  
I've outlined the path from TypeTracking to LocalFunction further down. 

[Here is the PR that introduced the LocalFunction class](https://github.com/github/codeql/pull/68). 

The reason for doing it like that is that we need to cut corners somewhere. 
[It is impossible to make an analysis that is sound and complete (and always terminates)](https://en.wikipedia.org/wiki/Rice%27s_theorem).     
Our design choice is to sacrifice some soundness and some completeness in order to get an analysis that gives good results in a reasonable time. 

Notes: 
- Sound static analysis: an analysis that models all possible executions of a program. 
- Complete static analysis: an analysis that never reports something that can't happen. 

We can always model more in our analysis, and we are constantly looking for ways to make our analysis better.   
But our analysis needs to be very precise and run within a reasonable amount of time, which somewhat limits what we can do.  

--- 

The path I had to follow in the code to figure that out was quite complicated, I've tried to outline it below. 

- [StepSummary::step(pred, succ, summary)](https://github.com/github/codeql/blob/b40c77d4195cf87cb957c7841d919c48d1c183bf/javascript/ql/lib/semmle/javascript/dataflow/TypeTracking.qll#L134)
- [StepSummary::smallstep(mid, succ, summary)](https://github.com/github/codeql/blob/b40c77d4195cf87cb957c7841d919c48d1c183bf/javascript/ql/lib/semmle/javascript/dataflow/internal/StepSummary.qll)
- [returnStep(pred, succ)](https://github.com/github/codeql/blob/b40c77d4195cf87cb957c7841d919c48d1c183bf/javascript/ql/lib/semmle/javascript/dataflow/internal/StepSummary.qll#L77) 
- [calls(succ, f)](https://github.com/github/codeql/blob/b40c77d4195cf87cb957c7841d919c48d1c183bf/javascript/ql/lib/semmle/javascript/dataflow/internal/FlowSteps.qll#L282)
- [f = invk.(DataFlow::InvokeNode).getACallee(0)](https://github.com/github/codeql/blob/b40c77d4195cf87cb957c7841d919c48d1c183bf/javascript/ql/lib/semmle/javascript/dataflow/internal/FlowSteps.qll#L282) 
- [CallGraph::getACallee(this, imprecision)](https://github.com/github/codeql/blob/b40c77d4195cf87cb957c7841d919c48d1c183bf/javascript/ql/lib/semmle/javascript/dataflow/Nodes.qll#L202) 
- [getAFunctionReference(result, imprecision)](https://github.com/github/codeql/blob/b40c77d4195cf87cb957c7841d919c48d1c183bf/javascript/ql/lib/semmle/javascript/dataflow/internal/CallGraphs.qll#L159)
- [fun = getAFunctionValue(result)](https://github.com/github/codeql/blob/b40c77d4195cf87cb957c7841d919c48d1c183bf/javascript/ql/lib/semmle/javascript/dataflow/internal/CallGraphs.qll#L36) 
- [node.getAValue()](https://github.com/github/codeql/blob/b40c77d4195cf87cb957c7841d919c48d1c183bf/javascript/ql/lib/semmle/javascript/dataflow/internal/CallGraphs.qll#L14) 
- [getALocalValue()](https://github.com/github/codeql/blob/b40c77d4195cf87cb957c7841d919c48d1c183bf/javascript/ql/lib/semmle/javascript/dataflow/TypeInference.qll#L60) 
- [getFunction().argumentPassing(astNode, pred.asExpr())](https://github.com/github/codeql/blob/b40c77d4195cf87cb957c7841d919c48d1c183bf/javascript/ql/lib/semmle/javascript/dataflow/internal/AnalyzedParameters.qll#L27) 
- [invk = getAnInvocation()](https://github.com/github/codeql/blob/b40c77d4195cf87cb957c7841d919c48d1c183bf/javascript/ql/lib/semmle/javascript/dataflow/internal/VariableTypeInference.qll#L673) 
- [local.getAnInvocation()](https://github.com/github/codeql/blob/b40c77d4195cf87cb957c7841d919c48d1c183bf/javascript/ql/lib/semmle/javascript/dataflow/internal/VariableTypeInference.qll#L726)
- [DataFlow::InvokeNode getAnInvocation() { result = invk }](https://github.com/github/codeql/blob/b40c77d4195cf87cb957c7841d919c48d1c183bf/javascript/ql/lib/semmle/javascript/dataflow/internal/InterProceduralTypeInference.qll#L209)

**Comment by xiaofen9** [comment]
Thanks for the detailed answer. It really helps!
