### ISSUE TITLE
False Negative in Reflected XSS in Javascript

### ISSUE THREAD

**Issue by Naman-ntc** [github/codeql#7276]
**Reflected XSS query fails on examples in "Incomplete HTML attribute sanitization"**

According to the incomplete attribute sanitization query following piece of code is unsafe. 
```
var app = require('express')();
app.get('/user/:id', function(req, res) {
	let id = req.params.id;
	id = id.replace(/<|>/g, ""); // BAD
	let userHtml = `<div data-id="${id}">${getUserName(id) || "Unknown name"}</div>`;
	// ...
	res.send(prefix + userHtml + suffix);
});
```
From what I understand this instance is an example of reflected xss but the reflected xss query marks it as safe and thus making it false negative. I checked and  `id.replace(/<|>/g, "")` passes the `isSantizer` check implemented in configuration. The sanitizer implementation should be refined to be similar to what is present in incomplete HTML sanitization query and this case could be removed?

**Comment by asgerf** [comment]
Hi @Naman-ntc,

The example is flagged by the Incomplete HTML attribute sanitization query, which you mentioned yourself. So we are generally OK with the reflected XSS query not flagging that example, because it's covered by another query, whose description states that this can lead to XSS.


Our queries are sometimes complementary in that way, in that a query is designed on the assumption that the user will see results from other queries as well. This especially happens with sanitization logic. There are many types of logical blunders and oversights that make a sanitizer ineffective, and it generally works better for us if those errors are caught by individual queries, rather than each data-flow query knowing how to validate each kind of sanitizer.

**Comment by Naman-ntc** [comment]
Hi, Thanks I understand that this strategy will make queries simpler. I have been working on using CodeQL to detect sanitizer instances and using the standard library `isSanitizer` predicates. 

Because of this implementation strategy, it detects the bad sanitizer as well. I believe the solution for my problem should be to not rely on the standard library predicates but write new things?

**Comment by max-schaefer** [comment]
> I believe the solution for my problem should be to not rely on the standard library predicates but write new things?

As discussed offline, I think in this case you may want to use both the `isSanitizer` predicate as well as some logic from `IncompleteHtmlAttributeSanitization` to ensure that you only find sanitisers that are not broken.

**Comment by Naman-ntc** [comment]
Yes right, that is what I intended to say - "should not rely **alone** on the standard library". Thanks, @asgerf and @max-schaefer! 
Also, the reason "people rejecting bad sanitizers vulnerability alerts as false positives" is actually very interesting and the strategy of separate alert is very nice!.
