### ISSUE TITLE
Understanding the difference between DataFlow::Node and DataFlow::PathNode while selecting nodes

### ISSUE THREAD

**Issue by DhvanilSanghvi** [github/codeql#7387]
Hey,
I have been trying to print the information about nodes that can act as sources for the JavaScript vulnerability- [_IncompleteHtmlAttributeSanitization_](https://codeql.github.com/codeql-query-help/javascript/js-incomplete-html-attribute-sanitization/). I implemented two version of queries to do this.

1. [**Based on DataFlow::PathNode**](https://lgtm.com/query/4397879329300282725/)
2. [**Based on DataFlow::Node**](https://lgtm.com/query/4355145987392043926/)

The results differ because of this small change. The code stub of the [good sanitizer](https://lgtm.com/projects/g/github/codeql/snapshot/51cbb8d72045960732a139fb5ef0c4f7ae40f274/files/javascript/ql/src/Security/CWE-116/examples/IncompleteHtmlAttributeSanitizationGood.js?sort=name&dir=ASC&mode=heatmap#L5) also gets marked as a source for the second query. 

1. Is this expected?
2. Can someone please explain why this is happening?

**Comment by asgerf** [comment]
Hi @DhvanilSanghvi 👋 

Yes, this is expected.

`DataFlow::PathNode` represents a node on a path from a source to a sink, and only exists for nodes that are part of such a path. This means there is no `PathNode` in the "good sanitizer" test case, because the source never reaches a sink. 

Internally, the `DataFlow::PathNode` type depends on which `DataFlow::Configuration` classes have been defined, and may thus have different values in different queries. It's best not to use the class for anything other than generating path explanations.

`DataFlow::Node` is independent of `DataFlow::Configuration` and is just derived from the program itself.

**Comment by DhvanilSanghvi** [comment]
Hey Asger,
Thank you for the clarification. I appreciate it!
