### ISSUE TITLE
how parse lib/*.jar to java database

### ISSUE THREAD

**Issue by hktalent** [github/codeql#7462]
how parse lib/*.jar to java database

Thanks

**Comment by adityasharad** [comment]
Hello. It sounds like you are interested in including the contents of JAR files in the CodeQL database for a Java project.

For compiled languages, CodeQL generally operates by observing the source code that is compiled during the build, and extracting that code into the database.

If those JARs are part of your source code, you need to start with the source code, and pass CodeQL the build command used to build the JARs from source. See https://codeql.github.com/docs/codeql-cli/creating-codeql-databases/#creating-databases-for-compiled-languages for more information.

If those JARs are libraries that your source code depends on and is compiled against, their API surface (class and method signatures) will usually be included in the CodeQL database without any further action from you, but their source code implementation will not be present in the database since CodeQL does not currently support Java bytecode analysis.

**Comment by hktalent** [comment]
@adityasharad  I want to analyze jars for some commercial software. Unfortunately, I don't have source code, so I need to analyze jars. Usually, there are many errors in the code after reverse engineering

**Comment by adityasharad** [comment]
CodeQL (and its Java analysis in particular) is designed to operate on source code, so it may not be the best tool for your purpose in this case.

Please also refer to the [GitHub CodeQL Terms and Conditions](https://github.com/github/codeql-cli-binaries/blob/main/LICENSE.md) and make sure whether your use is covered by the license.
