### ISSUE TITLE
Broken link to query in documentation

### ISSUE THREAD

**Issue by Naman-ntc** [github/codeql#7484]
The `Click to see the query in the CodeQL repository` link on the [Use of a broken or weak cryptographic algorithm](https://codeql.github.com/codeql-query-help/javascript/js-weak-cryptographic-algorithm) javascript query renders incorrectly.

**Comment by edoardopirovano** [comment]
Greetings, thanks for spotting this and bringing it to our attention! This is due to a bug in our internal CI workflow that generates those files. I have now fixed it, and expect the fix to reach the website within the next few weeks when we next do an update of those web pages.

**Comment by Naman-ntc** [comment]
Happy holidays and welcome! I tried to see if I can locate what might be causing the issue in the repo but wasn't able to find anything.

**Comment by edoardopirovano** [comment]
> Happy holidays and welcome! I tried to see if I can locate what might be causing the issue in the repo but wasn't able to find anything.

Thanks for looking! Indeed, this is not a problem you could have located or fixed, as the code that generates those help files is not public. If you're interested - the issue was that we were searching for the string `go` in the query path to determine whether the query was for Go since those queries are in a [different repo](https://github.com/github/codeql-go). We were then applying some different logic for working out the target of the link if we thought the query was a Go query. However, this is broken for the query BrokenCryptoAl**go**rithm.ql because that contains the string `go`.

**Comment by Naman-ntc** [comment]
Oh, thanks for explaining! I was actually quite curious as to how this vulnerability got singled out
