### ISSUE TITLE
LGTM.com - false positive - cpp/ambiguously-signed-bit-field with glib

### ISSUE THREAD

**Issue by MrAnno** [github/codeql#7491]
GLib's `gboolean` is just a typedef to `gint`, but it is meant to represent a simple true/false value.

An exception for WIndows BOOLs has already been added to the mentioned query.
I was wondering if you would be interested in adding one for GLib (a frequently used C library) too.

For example:
https://github.com/syslog-ng/syslog-ng/blob/c533d1d1983b9f6840e96353f1588b2d1596613b/.lgtm/cpp-queries/ambiguously-signed-bit-field.ql#L31

**URL to the alert on the project page on LGTM.com**
- https://lgtm.com/projects/g/syslog-ng/syslog-ng?mode=tree&ruleFocus=1506024027114
- https://lgtm.com/projects/g/syslog-ng/syslog-ng/snapshot/41fe7434c6759b8b4c89ee7d0bb21298588defa7/files/lib/logwriter.c?sort=name&dir=ASC&mode=heatmap#xc9d81cfcc4deee15:1

**Comment by edoardopirovano** [comment]
Hello, many thanks for pointing this out. This sounds like a reasonable enhancement to this query. If you'd like to open a pull request with this please do feel free to do so and we should be able to review that for you once more of the team is back from the holidays.

**Comment by MrAnno** [comment]
Yay, thank you.

I'm opening a PR.

**Comment by MrAnno** [comment]
@edoardopirovano I just noticed that LGTM v1.29.0 was released a few days ago, but the mentioned false positives still seem to be reported for this specific data type on LGTM.com.

https://lgtm.com/projects/g/syslog-ng/syslog-ng/alerts/

Can I do anything (bump version in lgtm config, update something, etc.) to make those disappear?

**Comment by edoardopirovano** [comment]
Note the 1.29 version you are describing is of LGTM Enterprise, which is what some of our customers who have their own instance of LGTM use. These releases lag a fair bit behind CodeQL ones in order to ensure they get the most stable version possible (in particular, LGTM 1.29 corresponds to CodeQL 2.6.3, released in October). On the other hand, LGTM.com is kept up to date with the latest CodeQL version (currently 2.7.6, released a few days ago). Unfortunately, 2.7.6 did not yet include your change. The first version that will include your PR is 2.8.0 which is due to be released in a couple of weeks.

Apologies it's taking so long to ship your change - normally we get everything released within a few weeks, but we were preparing a stable version of CodeQL to include GitHub Enterprise 3.4 so in the last release we only included a few critical bug fixes. If you sit tight for another couple of weeks you should see those alerts disappear though!

**Comment by MrAnno** [comment]
No problem at all, I was just unsure whether it is something I missed or forgot to do.
Thank you very much for the explanation.
