### ISSUE TITLE
java/dereferenced-value-may-be-null - false positive

### ISSUE THREAD

**Issue by pivotal-jbarrett** [github/codeql#7538]
java/dereferenced-value-may-be-null falsely detects `null` reference in complex loop with `null` check. The code it is struggling with is not the most rational and readable code but it does not have a `null` reference issue. I will likely be refactoring this code to make cleaner and avoid this confusion but thought it worth reporting this oddity.

> Variable `keyToRemove` may be null here as suggested by this null guard.

https://lgtm.com/projects/g/apache/geode/snapshot/984d32fd85b8d794a18b7c52e528efe2c70c83a5/files/geode-core/src/main/java/org/apache/geode/cache/query/internal/index/RangeIndex.java?sort=name&dir=ASC&mode=heatmap#xb97893fef66b5d82:2

If you look closely at the `keyToRemove` and how it is paired with `foundKeyToRemove` you will notice there is no instance where we can enter the loop with `keyToRemove` set to `null` and `foundKeyToRemove` set to `false`. Furthermore, once set to `true` there is no way for `foundKeyToRemove` to ever be `false` again.

**Comment by smowton** [comment]
Hi, thanks for the report -- as you say it's the code complexity that generates the false positive here. Because recognising this false positive scenario accurately would require reasonably deep analysis to recognise a scenario that we expect to be fairly rare, we choose not to fix this at this time.
