### ISSUE TITLE
java/non-null-boxed-variable - false positive

### ISSUE THREAD

**Issue by pivotal-jbarrett** [github/codeql#7539]
While java/non-null-boxed-variable correctly indicates that a non-null is boxed it should ignore this case where the boxed version is used in more than one method call that requires a boxed type to avoid repeatedly auto-boxing the value.

> The variable 'bucketId' is only assigned values of primitive type and is never 'null', but it is declared with the boxed type 'Integer'.

https://lgtm.com/projects/g/apache/geode/snapshot/984d32fd85b8d794a18b7c52e528efe2c70c83a5/files/geode-core/src/main/java/org/apache/geode/internal/cache/PartitionedRegionDataStore.java?sort=name&dir=ASC&mode=heatmap#L1387

Notice that the value is used as a key to both `get` and `remove` values from `localBucket2RegionMap`. If the value was of type `int` the effective result would potentially be multiple invocations to `Integer.valueOf(int)`. In the case where `bucketId` is greater than the max `Integer` box cache this would result in transient duplicate allocations of the boxed `Integer` type.

**Comment by smowton** [comment]
Seems sensible to me, I'll make a PR later this week

**Comment by smowton** [comment]
Turns out the query already excludes cases where all the users take the boxed type: this case got flagged because `getBucketAdvisor` takes an `int`, so the choice about whether it's better to store it boxed and unbox as needed or vice versa is unclear. In that situation it's probably best for it to raise an alert which you can dismiss in the event you're convinced that storing the value boxed is the best course of action.
