### ISSUE TITLE
JS: Can codeQL support Spread syntax or ASTNode get left and right node

### ISSUE THREAD

**Issue by T1m0n0** [github/codeql#7623]
Spread syntax (...)：https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

Now I can get statements like "{ ...a, ...b }".
Or Can codeql support ASTNode get left and right node?
thank

**Comment by KeuntaeShin** [comment]
getAST() canbe used.

**Comment by tausbn** [comment]
You may be interested in the `SpreadElement` [class](https://codeql.github.com/codeql-standard-libraries/javascript/semmle/javascript/Expr.qll/type.Expr$SpreadProperty.html).

To find `{ ...a, ...b }`, it should be enough to look for two such `SpreadElement`s, checking that they have the same `getParent` and that they are not equal (since otherwise you would also match objects with only one spread, like `{ ...a }`).

**Comment by T1m0n0** [comment]
code：
```javascript
const a = 1;
const b = {a: 2, b:3}
console.log({ a, ...b})
```
output：
```text
{a: 2, b: 3}
```
Variable a is covered by b in the situation,so how do I connect both nodes in the function isAdditionalTaintStep?
