### ISSUE TITLE
VariableCall as a sink

### ISSUE THREAD

**Issue by KeuntaeShin** [github/codeql#7716]
With DataFlow::Configuration, how to find all paths that impact to arguments of specific VariableCalls? Is it possible?

A below query is not working:
```
override predicate isSource(DataFlow::Node node) {  
    node.asExpr() = any(ExprCall call).getExpr()
}

override predicate isSink(DataFlow::Node node) {       
    exists(VariableCall vc | 
        node.asExpr() = vc  and
        node.asExpr().(VariableCall).getExpr().toString().matches("copy_from%")
    )
}
```

**Comment by smowton** [comment]
Could you give an example of a result you'd like to see? At the moment that source is searching for anything that is called like a function pointer, and the sink is looking for results of specifically calls of the form `copy_fromxyz(arg0, arg1, ...);`

There are two issues that probably need fixing:

1. You say you're looking for flow to an **argument** to a `VariableCall`, but `node.asExpr() = vc` means the result of the call. You may want `node.asExpr() = vc.getAnArgument()` instead.
2. Your source currently asks for any expression `e` occurring in the context `e(arg0, arg1, ...);`, but because `e` is **read** in that context it will not flow to anywhere else. Similarly, in the context `int x = a; int y = a;`, the two reads of `a` do not flow to one another (but anything written to `a` flows to both reads). If you wanted to look for the **result** of an `ExprCall` then you want `node.asExpr() instanceof ExprCall`.

Here is a working example that looks for results of calls that flow to arguments to `mb_char2bytes`, which I tested against the `vim/vim` database from lgtm.com (https://lgtm.com/projects/g/vim/vim/ci/#ql):

```ql
/**
 * @kind path-problem
 */

import cpp
import semmle.code.cpp.dataflow.DataFlow
import DataFlow::PathGraph

class MyConfig extends DataFlow::Configuration {

  MyConfig() { this = "MyConfig" }

  override predicate isSource(DataFlow::Node node) {
    node.asExpr() instanceof Call
  }

  override predicate isSink(DataFlow::Node node) {
    exists(VariableCall vc |
        node.asExpr() = vc.getAnArgument() and
        vc.getExpr().toString() = "mb_char2bytes"
    )
  }

}

from DataFlow::PathNode source, DataFlow::PathNode sink
where any(MyConfig c).hasFlowPath(source, sink)
select source, source, sink, "Message"
```

**Comment by KeuntaeShin** [comment]
> Could you give an example of a result you'd like to see? At the moment that source is searching for anything that is called like a function pointer, and the sink is looking for results of specifically calls of the form `copy_fromxyz(arg0, arg1, ...);`
> 
> There are two issues that probably need fixing:
> 
> 1. You say you're looking for flow to an **argument** to a `VariableCall`, but `node.asExpr() = vc` means the result of the call. You may want `node.asExpr() = vc.getAnArgument()` instead.
> 2. Your source currently asks for any expression `e` occurring in the context `e(arg0, arg1, ...);`, but because `e` is **read** in that context it will not flow to anywhere else. Similarly, in the context `int x = a; int y = a;`, the two reads of `a` do not flow to one another (but anything written to `a` flows to both reads). If you wanted to look for the **result** of an `ExprCall` then you want `node.asExpr() instanceof ExprCall`.
> 
> Here is a working example that looks for results of calls that flow to arguments to `mb_char2bytes`, which I tested against the `vim/vim` database from lgtm.com (https://lgtm.com/projects/g/vim/vim/ci/#ql):
> 
> ```ql
> /**
>  * @kind path-problem
>  */
> 
> import cpp
> import semmle.code.cpp.dataflow.DataFlow
> import DataFlow::PathGraph
> 
> class MyConfig extends DataFlow::Configuration {
> 
>   MyConfig() { this = "MyConfig" }
> 
>   override predicate isSource(DataFlow::Node node) {
>     node.asExpr() instanceof Call
>   }
> 
>   override predicate isSink(DataFlow::Node node) {
>     exists(VariableCall vc |
>         node.asExpr() = vc.getAnArgument() and
>         vc.getExpr().toString() = "mb_char2bytes"
>     )
>   }
> 
> }
> 
> from DataFlow::PathNode source, DataFlow::PathNode sink
> where any(MyConfig c).hasFlowPath(source, sink)
> select source, source, sink, "Message"
> ```

Hello @smowton,

Thanks for your advice, it's fit what i expected.

Thanks,
Keuntae Shin
