### ISSUE TITLE
Dataflow from VariableCall to specific functions

### ISSUE THREAD

**Issue by KeuntaeShin** [github/codeql#7765]
I'm considering to find paths from VariableCall to specific functions. The target source code:

```
#include <string.h>

struct a {
    void(*copy)(char *_dst, char *_src, int _sz);
};

void real_copy(char *_dst, char *_src, int _sz){
    if(_sz > 20) {
        _sz = 20;
    }
    memcpy(_dst, _src, _sz);
}

int main(){
    char dst[20] = {0,};
    char src[20] = "Hello CodeQL";
    int sz = 20;

    struct a b = {.copy = real_copy};
    
    b.copy(dst, src, sz);

    printf("The dst: %s\n", dst);
}
```
And the path i expect like below:
> char dst[20] = {0,};
> b.copy(dst, src, sz);
> void real_copy(char *_dst, char *_src, int _sz){
> memcpy(_dst, _src, _sz);
> 
Or:
> b.copy(dst, src, sz);
> void real_copy(char *_dst, char *_src, int _sz){
> memcpy(_dst, _src, _sz);

I'm using below sink and source, and there is no path found:
```
override predicate isSource(DataFlow::Node node) {       
    exists(VariableCall vc |      
        node.asExpr() =vc.getAnArgument()
    )
}
override predicate isSink(DataFlow::Node node) {       
    exists(FunctionCall fc |
        fc.getTarget().toString().matches("memcpy") and        
        node.asExpr() =fc.getAnArgument()
    )
}
```

**Comment by smowton** [comment]
Per default the C/C++ data flow library does not attempt to resolve function pointer targets.

You can (partly) work around this by using `isAdditionalFlowStep` to connect call arguments and function parameters together using some approximation to the called function, however:

```ql
/**
 * @kind path-problem
 */

import cpp

import semmle.code.cpp.dataflow.TaintTracking
import DataFlow::PathGraph

FunctionAccess getACallee(ExprCall ec) {
  DataFlow::localExprFlow(result, ec.getExpr())
}

class MyConfig extends TaintTracking::Configuration {

  MyConfig() { this = "MyConfig" }

  override predicate isSource(DataFlow::Node node) {
    exists(VariableCall vc |
        node.asExpr() = vc.getAnArgument()
    )
  }

  override predicate isSink(DataFlow::Node node) {
    exists(FunctionCall fc |
        fc.getTarget().getName() = "__builtin___memcpy_chk" and
        node.asExpr() = fc.getAnArgument()
    )
  }

  override predicate isAdditionalTaintStep(DataFlow::Node fromNode, DataFlow::Node toNode) {
    exists(Function callee, ExprCall call, int argIdx |
      callee = getACallee(call).getTarget() and
      fromNode.asExpr() = call.getArgument(argIdx) and
      toNode.asParameter() = callee.getParameter(argIdx)
    )
  }

}

from MyConfig c, DataFlow::PathNode src, DataFlow::PathNode sink
where c.hasFlowPath(src, sink)
select src, src, sink, "message"
```

Notes:

1. I had to change `fc.getTarget().toString().matches("memcpy")` to `fc.getTarget().getName() = "__builtin___memcpy_chk"` because (a) `memcpy` is a macro on my system, and we see the code post macro expansion (try using the VSCode "AST Viewer" feature in the CodeQL database selection pane to see what syntax tree we saw post macro expansion), (b) `getName()` is better than `toString()` which is a user-facing pretty representation that may change from time to time, and (c) `matches` is for wildcard matching using `_` and `%` wildcards; for exact equality `=` is better.
2. I've used `DataFlow::localExprFlow` since in this case the callee is easy to resolve, but a "proper" solution should also check if the function and callee signatures are compatible, and/or could use a `DataFlow2::Configuration` (not a `DataFlow2::Configuration` since configurations aren't allowed to depend on one another) to follow function references to function pointer call-sites inter-procedurally
3. Using `isAdditionalFlowStep` like this loses a bit of fidelity compared to a direct function call: normally the CodeQL dataflow library tracks the call stack, so we know that a return from the callee `real_copy` will return to `main`, but an additional flow step that crosses function prevents stack tracking. The version I've shown here will never flow back out of `real_copy`; a version that also added flow-steps from return value and/or pointer/reference-typed arguments back to the callsite could appear to return from a different callsite that may target the same function. In this case I've skipped providing any flow edges back to the callsite, since the sink is inside the callee.

**Comment by smowton** [comment]
Edit: C/C++ also has a variant on the dataflow library called the IR Dataflow Library, found at `semmle.code.cpp.ir.dataflow.*`. This makes an attempt at simple function pointer tracking. It may resolve more indirect function calls than the normal dataflow library, but it doesn't catch the case in the test program you gave, so using additional taint steps is still necessary.

**Comment by KeuntaeShin** [comment]
@smowton , 

I really appreciate your consideration. Based on your query, a new query has been completed for eliminating dependency on the localExprFlow:
```
override predicate isAdditionalTaintStep(DataFlow::Node fromNode, DataFlow::Node toNode) {
  exists(Function callee, VariableCall vc, int argIdx |
   callee = vc.getVariable().getAnAssignedValue().getAChild*().(FunctionAccess).getTarget() and
   fromNode.asExpr() = vc.getArgument(argIdx) and
   toNode.asParameter() = callee.getParameter(argIdx)
  
  )
}
```
