### ISSUE TITLE
LGTM.com - false positive 'Useless conditional'

### ISSUE THREAD

**Issue by AlanGreene** [github/codeql#8064]
**Description of the false positive**

**URL to the alert on the project page on LGTM.com**

There are two instances of 'Useless conditional' false positives in React components:

1. https://lgtm.com/projects/g/tektoncd/dashboard/snapshot/70ab3df92dad30ee83dea8fe58116619e70ecf8b/files/src/containers/TaskRun/TaskRun.js?sort=name&dir=ASC&mode=heatmap#x759b1a295815a469:1
   - `isLoadingTaskRun` is defined at https://lgtm.com/projects/g/tektoncd/dashboard/snapshot/70ab3df92dad30ee83dea8fe58116619e70ecf8b/files/src/containers/TaskRun/TaskRun.js?sort=name&dir=ASC&mode=heatmap#L111 and comes from a call to `react-query` using a custom React hook. It is updated dynamically by `react-query` to reflect the current state of the request.

1. https://lgtm.com/projects/g/tektoncd/dashboard/snapshot/70ab3df92dad30ee83dea8fe58116619e70ecf8b/files/packages/components/src/components/Table/Table.js?sort=name&dir=ASC&mode=heatmap#xb07d5271cc520438:1
   - `loading` is received as a prop by this component, see https://lgtm.com/projects/g/tektoncd/dashboard/snapshot/70ab3df92dad30ee83dea8fe58116619e70ecf8b/files/packages/components/src/components/Table/Table.js?sort=name&dir=ASC&mode=heatmap#L124

**Comment by RasmusWL** [comment]
Thanks for reporting this, I've forwarded it to the JS team to take a look :+1:

**Comment by asgerf** [comment]
In both cases the alert happens because the value of the variable has been checked earlier in the same function:

1. It was checked by the early return on [line 204](https://lgtm.com/projects/g/tektoncd/dashboard/snapshot/70ab3df92dad30ee83dea8fe58116619e70ecf8b/files/src/containers/TaskRun/TaskRun.js?sort=name&dir=ASC&mode=heatmap#L204).

2. Similar situation, the code appears in the false branch of the ternary expression [line 203](https://lgtm.com/projects/g/tektoncd/dashboard/snapshot/70ab3df92dad30ee83dea8fe58116619e70ecf8b/files/packages/components/src/components/Table/Table.js?sort=name&dir=ASC&mode=heatmap#L203).

**Comment by AlanGreene** [comment]
You're absolutely right! Apologies, I completely missed those on review. Guess I've got a bit of tunnel vision after looking at the code for so long. Thanks for pointing out my mistake, closing this issue.
