### ISSUE TITLE
(Java) Taint Tracking fail on Argument of MethodAccess without Caller

### ISSUE THREAD

**Issue by thangpd3160** [github/codeql#8242]
I'm trying to write a custom query to detect CVE-2019-26891 (insecure deserialization) on liferay 6 but I've been struggling for 1 week without any movement.

In short, I debug the query and see the partial flow stop at the parameter pollerRequestString (line 73). I expected it could go to pollerRequestString argument at line 81, but I can't understand why it's not going to that place. 

Is that a feature of codeQL? If not, what could I do to extend the taint tracking flow?

![image](https://user-images.githubusercontent.com/77983946/155645030-ee227653-daef-479f-b7b9-9af580a71880.png)
Link of db: https://drive.google.com/file/d/1_qR2Az8a-gKhTIjuyL4eDsE1BCnmn_tw/view
Link of query I used: https://drive.google.com/file/d/1NdED9qO37TeolIZuZH6rRq0bOarkGUSi/view

**Comment by RasmusWL** [comment]
Hi @thangpd3160 I took a look at your query, and the DB. The problem seems to be that there is a default barrier for the argument to `parsePollerRequestParameters`. Barriers block all incoming and outgoing flow. You can inspect this yourself by adding the predicate below, and do a Quick Evaluation of it (from right-click menu).

If you do not agree that this is correct behavior, please let me know, and I can forward this feedback to the Java team.

```codeql
predicate debug_isBarrier(DataFlow::Node node) {
  node.getEnclosingCallable().getName() = "processRequest" and
  exists(MyTaintTrackingConfig cfg |
    cfg.isBarrier(node)
  )
}
```

**Comment by thangpd3160** [comment]
Thank @RasmusWL. I inspected your predicate myself. As the stracktrace of the CVE, the flow should have passed though the `parsePollerRequestParameter` argument. So, is there anyway to work around with this default barrier? If not, I want to understand why this is a default behavior, so that I can know whether this is a correct behavior.
![image](https://user-images.githubusercontent.com/77983946/155710869-4b86b7ba-722b-4e07-9f67-eacdfac7c370.png)

**Comment by RasmusWL** [comment]
Hi @thangpd3160, I'll ping the Java team to take a closer look, as this is not my area of expertise.

**Comment by thangpd3160** [comment]
Thank @RasmusWL. I look forward to the responses and ways to work around it!

**Comment by atorralba** [comment]
Hi @thangpd3160, Java team member here 👋 

We looked into your issue, and we found the root cause: in the code you provided, the call to `Validator.isNull` is what's causing the subsequent uses of `pollerRequestString` to be sanitized. This is because the taint tracking library defines some global sanitizers that apply to all configurations, and those include methods doing validation on their arguments with `String.contains` and `String.charAt`. Coincidentally, `Validator.isNull` is using `String.charAt` to do its nullability check, so the taint tracking library considers it's validating the value (although it actually isn't).

To work around this, we suggest the following:

* Change your configuration to extend `DataFlow::Configuration` instead of `TaintTracking::Configuration`. That way you won't be using the default implementation of the `TaintTracking::isBarrier` predicate, which includes the global sanitizers.
* To include the taint tracking features that differentiate a taint tracking configuration from a data flow one, override the `isAdditionalFlowStep` and `allowImplicitRead` predicates in your configuration to include the code in `TaintTracking::Configuration`:

```codeql
// Add any additional taint steps to this predicate if needed, else leave it as none()
predicate isAdditionalTaintStep(DataFlow::Node node1, DataFlow::Node node2) { none() }

override predicate isAdditionalFlowStep(DataFlow::Node node1, DataFlow::Node node2) {
  this.isAdditionalTaintStep(node1, node2) or
  defaultAdditionalTaintStep(node1, node2)
}

override predicate allowImplicitRead(DataFlow::Node node, DataFlow::Content c) {
    (this.isSink(node) or this.isAdditionalTaintStep(node, _)) and
    defaultImplicitTaintRead(node, c)
}
```
* You'll also need to `import semmle.code.java.dataflow.internal.TaintTrackingUtil` to be able to use `defaultAdditionalTaintStep` and `defaultImplicitTaintRead`.

This way you should see a flow path reaching your intended sink using the database you provided and the modified query.

**Comment by thangpd3160** [comment]
Hi @atorralba. Thanks for your suggestion, I have successfully worked around this issue!
