### ISSUE TITLE
[JS] Potential False Positive: Remote Property Injection

### ISSUE THREAD

**Issue by Naman-ntc** [github/codeql#8273]
For prototype pollution, `userVal !== '__proto__' && userVal !== 'constructor'` is considered as a sanitizer guard. I was wondering if such conditions will also sanitize remote property injection. 

Specifically, the following code is marked vulnerable but I believe should be safe. Of course, I agree that it can be ignored by CodeQL if sufficient usage is not present.
```js
var http = require('http');
var url = require('url');

x = {};
var server = http.createServer(function(req, res) {
    var userVal = req.url;
   if (userVal !== '__proto__' && userVal !== 'constructor') {
        x[userVal] = 23; // OK?  
    }
})
```

**Comment by erik-krogh** [comment]
> I was wondering if such conditions will also sanitize remote property injection. 

It is sufficient to guard against `__proto__` and `constructor` in some cases, but there are other cases where bad things can happen without having to use prototype related property names.   

Consider e.g. CVE-2019-2391 in `bson`. ([the fix for that CVE](https://github.com/mongodb/js-bson/commit/3809c1313a7b2a8001065f0271199df9fa3d16a8)).    
The vulnerability basically boils down to a magic `_bsontype` property that could be set by a user, and setting this `_bsontype` property to weird values would cause `bson` to get confused, and that could cause bad things to happen.   
I'm not sure if that CVE is strictly remote-property-injection, but it was a related CVE I had in recent memory.   

So to answer your question: I don't think the example shown is a false positive, but thanks for the input.
