### ISSUE TITLE
CodeQL lost some class parsing when parsing the project and building the database

### ISSUE THREAD

**Issue by LinShiG0ng** [github/codeql#8363]
**Description of the issue**

Hi bro，I have a question about Codeql Parse a projects and build databases，
I found the question when I used Webgoat to practice Codeql
First of all, this is the directory screenshot of the Sqlinjection part of the Webgoat project
![image](https://user-images.githubusercontent.com/66135346/157183703-24b8c822-725b-4917-aa4a-872953cd5d54.png)
There‘s java file named SqlInjectionChallenge

Here is a screenshot of the source directory in the database created by CodeQL
<img width="531" alt="image" src="https://user-images.githubusercontent.com/66135346/157184469-48662ec9-98f8-4f1a-acc3-5cfead9b2e28.png">
The Java file SqlInjectionChallenge is missing
That i don't konw why

Hope to get some answers from you

**Comment by LinShiG0ng** [comment]
Well just now I noticed that Codeql parsing is not only missing SqlInjectionChallenge，also missing SqlInjectionLesson12a.java and Servers.java。
![image](https://user-images.githubusercontent.com/66135346/157185979-6b4bd229-92e5-4af0-913d-a241716367af.png)
<img width="587" alt="image" src="https://user-images.githubusercontent.com/66135346/157186107-4559fcbb-0290-4763-a3f2-4c573cd6c68b.png">

Maybe there's more missing that I haven't found yet

**Comment by aibaars** [comment]
The webgoat project is written using Lombok, a sort of Java dialect. Lombok code is transformed into proper Java code using an annotation processor during compilation. This interferes with the CodeQL analyzer which "sees" the source code before it is transformed into valid Java code causing it to skip such files.  This can be worked around using the instructions in the answer to https://github.com/github/codeql/issues/4984 . You can also download a pre-build CodeQL database from LGTM.com instead of building one yourself. See https://lgtm.com/projects/g/WebGoat/WebGoat/ci/#ql .

**Comment by LinShiG0ng** [comment]
Ok, thank you for your answer
