### ISSUE TITLE
Compiled CodeQL packs cannot reference another pack from one of its query suites

### ISSUE THREAD

**Issue by Jeeppler** [github/codeql#8412]
**Description of the issue**

I am unable to run queries for a project written in C. The queries keep failing with the same error: Compiled CodeQL packs cannot reference another pack from one of its query suites.

~~~
$ codeql database analyze c-lang ~/.codeql/packages/codeql/cpp-queries/0.0.10/codeql-suites/cpp-code-scanning.qls --format=sarifv2.1.0 --output=c-lang.sarif
Running queries.
A fatal error occurred: Compiled CodeQL packs cannot reference another pack from one of its query suites. 'codeql/cpp-queries@0.0.10' references 'codeql/cpp-queries'.
~~~

CodeQL CLI version:

~~~
codeql --version
CodeQL command-line toolchain release 2.8.2.
Copyright (C) 2019-2022 GitHub, Inc.
~~~

I was unable to find anything regarding the issue in the documentation. What are Compiled CodeQL packs? Why do I get this error?

**Comment by hvitved** [comment]
@dbartol or @aeisenberg could you take a look, please?

**Comment by aeisenberg** [comment]
I was on vacation and back now. I'll pick this up.

**Comment by aeisenberg** [comment]
The reason behind this error is that we need to ensure that all of a compiled query pack's dependencies are contained within the pack. This ensures that once a pack is compiled, the query results will remain constant because it does not depend on anything external that can change.

There are two things here:

1. The failing query suite specifies a qlpack name even though it does not need to. Deleting line 6 (`from: codeql/cpp-queries`) of `~/.codeql/packages/codeql/cpp-queries/0.0.10/codeql-suites/cpp-code-scanning.qls` will allow the command to pass.
2. The codeql CLI is being too strict with its check. If the qlpack referenced in the `from` directive is the same pack that contains the suite being run, then we should not be throwing an error here.

I will make both fixes. @[Jeeppler](https://github.com/Jeeppler), you can manually edit the compiled qlpack as I describe in (1), which should get this working again.

**Comment by aeisenberg** [comment]
Will be fixed in next CodeQL CLI release.
