### ISSUE TITLE
Running codeql on prebuild-container

### ISSUE THREAD

**Issue by vsoch** [github/codeql#8502]
**Description of the issue**

Hi! :wave: So I'm trying out codeQL for some of my projects - it works great for simple builds (e.g., Python) but I'm hitting issues for more complex builds (e.g., c++). Most of the examples expect an action (within or outside a container) that perform the build after codeql init, and then running codeql analyze. The setups that I have are either:

1. building a base container of the code directly in the action to use later [e.g., here](https://github.com/dyninst/dyninst/blob/master/.github/workflows/base-containers.yaml)
2. using a pre-built base container to run tests or perform other scanning [e.g.,here](https://github.com/dyninst/dyninst/blob/master/.github/workflows/test-dyninst.yaml) or [here](https://github.com/dyninst/dyninst/blob/master/.github/workflows/libabigail.yaml)

The build is pretty complex - and yes this is pretty crappy that it doesn't work with one nice make / cmake command, but this project is really old and I don't have much control over that. So I can't easily do any of the suggestions in the examples. What I'd like to be able to do is either:

1. Be able to point codeql at some directory in the container (even without git)
2. build a container in one job, and then easily use it as a container base in the next step (in practice this does not work, it cannot find the reference. Saving to an artifact to load doesn't help us because we already need the reference.

Even if we could push a temporary container, per the issue (1) I don't think it would work! So I'm opening an issue hoping we can discuss some options. I'm wondering if either there could be support at more easily running codeql directly on a directory I specify in a container (how does it find files?) or providing a base container that has everything ready to go that I could somehow integrate with an automated build. Thanks for your help - let me know if you want to see or discuss anything in particular!

**Comment by criemen** [comment]
Hi,

the codeql-action cannot look inside your docker containers, so if you run your C++ build as part of `docker build`, CodeQL will not work with that due to fundamental limitations:
CodeQL needs to observe your build while it's running, and building inside the Docker container hides all your compiler invocations from us.
If you need to build your code inside a docker container, you cannot use the provided action, but you can still use the [CodeQL CLI](https://github.com/github/codeql-cli-binaries) _inside_ the docker container.
This is a bit more involved, though.
We have documentation for that [here](https://docs.github.com/en/code-security/code-scanning/using-codeql-code-scanning-with-your-existing-ci-system/installing-codeql-cli-in-your-ci-system).
