### ISSUE TITLE
LGTM.com - false positive - TrustManager that accepts all certificates

### ISSUE THREAD

**Issue by Hakky54** [github/codeql#8653]
**Description of the false positive**

Hi all, first thank you all for this great project. I am using it for quite some time and I am happy about it
I came across a false-positive and wondered what your opinion would be and if you guys also see it like that.

LGTM gives an alert because an unsafe trust manager is being used which would be not safe because it trusts all certificates without validation. In my library I provide indeed this option but it is not enabled by default. The end-user can use it as it has the option, but it is their call and because this option is not enabled by default I don't think it should raise an alert and therefore it is in my opinion a false-positive. However if it would be enabled by default I would definitely be a valid alert. What do you think?

**URL to the alert on the project page on LGTM.com**
https://lgtm.com/projects/g/Hakky54/sslcontext-kickstart/snapshot/9f7c9eb709c57e02ff28a9c0e518221f355c655f/files/sslcontext-kickstart/src/main/java/nl/altindag/ssl/util/SSLContextUtils.java#x5d1dbfa012045b79:1

**Comment by smowton** [comment]
I think generally speaking we would struggle to convincingly distinguish whether the application is secure or insecure by default, and the presence of an insecure implementation is not very onerous for developers to audit and mark as intentional, so I think it would be best to leave this query as is. Thanks for reporting, though -- in general we are interested in lowering our FP rate using reports like these.
