### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by szalpal** [github/codeql#8723]
I'm not a Python expert, but this is a recursive function, therefore I believe such pattern shouldn't impose problems, e.g.:

```python
def bfs_recursive(graph, visited_vertices=[]):
   ...
   visited_vertices.append(current)
   bfs_recursive(graph, visited_vertices)

graph = ...
bfs_recursive(graph)
```

[[**URL to the alert on the project page on LGTM.com**](https://github.com/NVIDIA/DALI/pull/3795#issuecomment-1096366254)](https://lgtm.com/projects/g/NVIDIA/DALI/snapshot/75a2b95b2083ebe05b6c51f726d603ab8941ae11/files/dali/python/nvidia/dali/_utils/autoserialize.py?sort=name&dir=ASC&mode=heatmap#xcd3ca46f01ecf9d1:1)

**Comment by aibaars** [comment]
Modifying the value of default parameters is a common pitfall in Python. After the call to `bfs_recursive(graph)` the default value of the `visited_vertices` parameter will no longer be `[]`, instead it will contain all the vertices of `graph`. 

See also: https://web.archive.org/web/20201112004749/http://effbot.org/zone/default-values.htm

**Comment by intrigus-lgtm** [comment]
This does not look like a false positive to me.
Let's open `python3` in a terminal and paste this code:
```python
def test(list=[]):
     list.append("test")
     print(visited)
```
and press enter twice.
If you now type `test()` and press enter, the result will look like this:
```bash
>>> test()
['test']
```

if you repeat this, the result will look like this:
```bash
>>> test()
['test', 'test']
```
Every invocation prints an additional element, because the default parameter `list` is computed only *once* when the function is **created**.

This small example can be translated to your lgtm alert.
In your case, calling `_discover_autoserialize(module, visited=[])` repeatedly would probably lead to problems.
This is because `visited` already contains modules that have been visited by *previous*  invocations, even if the given `module` is a different one.
Or is this indeed what you want?

Having a function for the base case and the recursive case *may* (I'm not a Python expert) be easier to understand and make lgtm happy.

Anyway, I hope this answer was helpful.

**Comment by szalpal** [comment]
Thank you for the responses and help. Indeed you're right. Thanks again!
