### ISSUE TITLE
LGTM.com - false positive [Node.JS Express]

### ISSUE THREAD

**Issue by asportnoy** [github/codeql#8807]
The error is saying that the query parameter could be either a string or an array, which could allow users to bypass sanitizing/validation. However, I have validation middleware which checks the type and ensures it is not an array. If I open that route with the query string specified multiple times (which is what would cause it to be an array), the validator correctly sends me an error and prevents the flagged code from running.

[LGTM page](https://lgtm.com/projects/g/codeths/kitcoin/snapshot/4295ff7509b236f0bd1476b5543084848c7bb392/files/src/webserver/routes/api/users.ts?sort=name&dir=ASC&mode=heatmap#xf4ffac7a69a0ff93:1)
[Code](https://github.com/codeths/kitcoin/blob/1c2911d426d9a37b3b5c1e6bbaa4dbfb38b9364a/src/webserver/routes/api/users.ts#L78)

**Comment by aeisenberg** [comment]
Thank you for raising this issue. It looks like you have [defined a sanitizer on line 46](https://lgtm.com/projects/g/codeths/kitcoin/snapshot/4295ff7509b236f0bd1476b5543084848c7bb392/files/src/webserver/routes/api/users.ts?sort=name&dir=ASC&mode=heatmap#L46), but the queries are not recognizing it.  Since this is security related, the team maintaining the javascript libraries will be interested. I will let them know. However, I am not sure if there is much they can do.

lgtm.com has facilities for suppressing individual alerts or disabling a query. This may be the most efficient option for you.
