### ISSUE TITLE
Codeql failed to create the database. I tried it on Linux and windows. It's the same error

### ISSUE THREAD

**Issue by JxxxxxL** [github/codeql#9031]
![image](https://user-images.githubusercontent.com/103913142/166614917-11f465f0-1d36-4769-bf17-0b2c2d7e6f64.png)

**Comment by aeisenberg** [comment]
It looks like codeql is trying and failing to autobuild your project. Instead, you will need to call explicit  build commands.

[See the docs for more info.](https://codeql.github.com/docs/codeql-cli/creating-codeql-databases/#specifying-build-commands)

**Comment by techvsi-datho** [comment]
> It looks like codeql is trying and failing to autobuild your project. Instead, you will need to call explicit build commands.
> 
> [See the docs for more info.](https://codeql.github.com/docs/codeql-cli/creating-codeql-databases/#specifying-build-commands)

Hi. I'm tried your suggest. seem like not worked for me.
`codeql database create my-db --language=javascript --source-root=. --command="yarn build"`
Any solution for us?

**Comment by redsun82** [comment]
👋 @techvsi-datho: please feel free to open a [new issue](https://github.com/github/codeql/issues/new?template=ql---general.md) with more details about your problem, which seems unrelated to the original issue.

In particular, in order to perform javascript analysis (as opposed to java like the original poster did), you actually don't need to provide the `--comand` flag.

If you end up opening an issue, providing the output of `codeql --version` and the output of the command you tried to run would be much helpful for us 🙌
