### ISSUE TITLE
General issue

### ISSUE THREAD

**Issue by mainsean435** [github/codeql#9258]
**Why can't run QL queries on javascript database?**

Hello,

I'm using  codeql vscode extension(v1.6.6), databases  for other languages are working but unfortunately, when I try running queries on the javascript database it fails with:

=====
Error running query: Resolving database upgrade scripts failed: [2022-05-23 04:32:17] [DETAILS] resolve upgrades> Searching for upgrades that apply to c1ee5346e068f6e0b687e75b4ba3f04a7382f4c4.
[2022-05-23 04:32:17] [DETAILS] resolve upgrades> Scanning for [codeql-pack.yml, qlpack.yml] from "*path to folder with query is shown here*"
=====

I came across some issues here where the solution was upgrading the database but that didn't work for my problem.
Thanks.

**Comment by edoardopirovano** [comment]
Greetings! Thanks for raising this issue with us. In order to help me further debug this, would you be able to share:

1. Which project you are analysing, and how you obtained the database for this (e.g. did you download the database from LGTM.com or create it yourself with CLI?).
2. Which version of the CodeQL CLI you are using (this is visible at the bottom right of VS Code).

Hopefully with that information I should be able to figure out what is going on that is causing you this issue and help resolve it for you!

**Comment by mainsean435** [comment]
> Greetings! Thanks for raising this issue with us. In order to help me further debug this, would you be able to share:
> 
> 1. Which project you are analysing, and how you obtained the database for this (e.g. did you download the database from LGTM.com or create it yourself with CLI?).
> 2. Which version of the CodeQL CLI you are using (this is visible at the bottom right of VS Code).
> 
> Hopefully with that information I should be able to figure out what is going on that is causing you this issue and help resolve it for you!

Hello, am using CodeQL CLI v2.9.2
I created the database from [this project](https://github.com/DevSlop/Pixi.git)
```bash
mkdir databases
git clone https://github.com/DevSlop/Pixi.git
codeql database create ./databases/pixi_db --language="javascript" --source-root="./Pixi"
```

**Comment by mainsean435** [comment]
I resorted to using the latest version of  [vscode-codeql-starter](https://github.com/github/vscode-codeql-starter) and the queries are now running okay.
Thank you sir.
