### ISSUE TITLE
Resources for integration of new languages

### ISSUE THREAD

**Issue by j-sauer** [github/codeql#9370]
I do like the idea of codeql and want to use it for a toy language or later for F# (as a side project).
Does there exist a guide/documentation/resources on how to integrate a new programming language?

**Comment by tausbn** [comment]
Unfortunately, I don't think we have any good guides for how to integrate a new programming language. The first thing you'll need is a way of turning your code into a CodeQL database. This is the part that we usually refer to as an "extractor".

The level of effort required to implement an extractor varies a lot depending on the language. Some languages (e.g. Ruby) need only the AST (and so basically just a way of encoding syntax trees in the database). For other languages (like C# or Java), it may be necessary or desirable to extract more information from the compiler as it builds the source code in question (i.e. the code has to build in order to be extracted). 

For Ruby in particular, you may enjoy reading [this](https://github.blog/2022-02-01-code-scanning-and-ruby-turning-source-code-into-a-queryable-database/) post on how Ruby support was implemented.

(You can also look at how the Ruby and C# extractors and CodeQL libraries are implemented in the [CodeQL](https://github.com/codeql) repo, as all the relevant source code should be available there.)

Assuming you can write down a [`tree-sitter`](https://tree-sitter.github.io/tree-sitter/) grammar for the language in question, then it should be fairly easy to adapt the Ruby extractor (which is written in Rust) to this new grammar.

**Comment by j-sauer** [comment]
Thanks a lot. That helps a lot :)
Regarding the database: Do you have a more detailed description how the schema etc. has to be?

**Comment by tausbn** [comment]
There's not really a set formula for how to set up the `.dbscheme` files. I would suggest looking at the various `.dbscheme` files in the CodeQL repo. (And if you go the tree-sitter route, you don't even have to worry about these files, since they are automatically generated from the grammar.)

For instance, [this](https://github.com/github/codeql/blob/main/ruby/ql/lib/ruby.dbscheme) is the aformentioned autogenerated file for Ruby.

Unfortunately there isn't a wealth of documentation available about QL database schemas, but the way they interact with QL is essentially as follows:

- Database types (identified by starting with an `@` sign) can be used as superclasses for classes defined in QL, e.g. `class Foo extends @foo { ... }`.
- Predicates in the schema (e.g. `files` from the Ruby schema above) can be referenced in exactly the same way as other QL predicates (so, putting `files(x, "test")` will match `x` with anything in the `files` relation that has the filename `test`).

Assigning a meaning to what's in the database and database schema is essentially completely up to the person writing the extractor. :slightly_smiling_face:

**Comment by intrigus-lgtm** [comment]
Here is a somewhat related previous discussion:
https://github.com/github/securitylab/discussions/134
(**Also, don't forget to check out #codeql-hacking in the GitHub Securitylab Slack**)

**Comment by j-sauer** [comment]
Thank you very much :)
I guess that suffices for the start.
