### ISSUE TITLE
Regex doesn't work properly

### ISSUE THREAD

**Issue by MFaisalZaki** [github/codeql#9562]
I am trying to recognize `#pragma pack` directive for `MSVC`. Therefore, I have wrote this simple query:

```
import cpp

from PreprocessorDirective directive
where directive.getHead().regexpMatch("pack*")
select directive
```
to capture the following two pack pragmas in this sample:
```
#pragma pack(push, 1)
#include "my_header.h"
#pragma pack(pop)
```

However, after various tries with `regexpMatch` and `matches` the query cannot capture the proper pattern even though I have tried the same pattern using [RegExr](https://regexr.com) and it is working as expected.

**Comment by hmakholm** [comment]
Your regular expression should be `"pack.*"` -- that is, `pack` followed by zero or more arbitrary characters.
`"pack*"` would mean the that the text of the directive needs to be `pac` followed by zero or more copies `k`.

(It looks like you were trying to use filename globbing syntax rather than regular expressions).

You could also write `.matches("pack%")` if you prefer the more SQL-like pattern syntax that `matches` uses.

Finally, for general neatness, you'll probably want `directive` to have type `PreprocessorPragma` rather than `PreprocessorDirective`).
