### ISSUE TITLE
How to make a taint tracking connection bettween a API of Interface and its implementation API in java using codeql?

### ISSUE THREAD

**Issue by soh0ro0t** [github/codeql#9820]
I occured a quite regular issue that need to connect a API of an Interface to its implemental API when uses codeql to scan java code to do trace. There is a very common interface and its definition is like bellow:
```java
public interface MyInterface {
    void myApi(DataCls data)
}
```
and its implementation code is like bellow:
```java
public class MyImpl {
    void myApi(DataCls data) {...}
}
```
then its reference code is like bellow:
```java
MyInterface myif = new MyImpl()
MyImpl.myApi(myData)    /************tag3*************/
```
I query the code of tag3 and found its result is not a MethodAccess type, therefore I can not get the method of myApi in MyImpl class from there,  How could I resolve it? anyone can help me?

**Comment by aeisenberg** [comment]
Do you mean:

```
myif.myApi(myData)
```

Otherwise, `myApi` would be a static method. I don't think it really matters either way, though. My suggestion is to use vscode and open up the AST Viewer on this file. It will show you the ast nodes in use for any location.

For instance, I put this code snippet into a database. 

```java
package my;

public interface Foo {
    void myApi(String data);
}

class MyImpl implements Foo {
    public void myApi(String data) { }

    public static void main(String[] args) {
        Foo f = new MyImpl();
        f.myApi("");
    }
}
```

Here is what the AST looks like:
<img width="337" alt="_Extension_Development_Host__Foo_java_—_vscode-codeql-starter__Workspace_" src="https://user-images.githubusercontent.com/363559/179003779-fa6e6fc0-e69e-44f4-9ab5-c1cf3bf9a278.png">

Please let me know if you have any further questions.

**Comment by soh0ro0t** [comment]
Sorry, I didn't make it clear.It should be a method access thought instance, not a static call. The snippet code is supposed to be: 
```java
MyInterface myif = new MyImpl()
//MyImpl.myApi(myData)    /************tag3*************/
myif.myApi(myData) /************tag3*************/
```
Thank for your help and it's quite useful for me to view `AST VIEWER`, and I got a way to reach the implementation code through myApi call.
