### ISSUE TITLE
C++ Query: DataFlow Query Contingent on Control Flow 

### ISSUE THREAD

**Issue by bdrodes** [github/codeql#9871]
I'm relatively new to CodeQL so this might have an obvious answer, but in writing a DataFlow query, I want to stop data flow down a given control flow depending on how the data is used. Specifically, consider this scenario:

```
int *a = NULL;
...
assert(a != NULL);
...
x = *a + 1;
```

I would like to find a null dereference of 'a', but since 'a' went through an assert, I do not want to flag a false positive. The problem is `a` does not flow through the assert, so I see no constructs in DataFlow to stop from flagging the deref. The best I can see is BarrierGuard, but the assert is not a guard expression, so I was unable to get it to work for an arbitrary function call. 

Another possibility might be to look backwards on a sink to determine if there is a use of the varable in the assert using SSA, but that would likely give a false negative for cases like this:

```
int *a = NULL;
...
if(some_bool())
    assert(a != NULL);
...
x = *a + 1;
```

What is the mechanic I can use on a dataflow to stop a flow going through a specific control flow generally speaking?

**Comment by bdrodes** [comment]
@edoardopirovano I tried barrier guards, but they seem to be limited to being conditional expressions, not arbitrary expressions. Did I misinterpret that? I also tried to create one and it failed to work for this case, so I assume it was due to it not being in an actual conditional expression.

**Comment by edoardopirovano** [comment]
Aha, indeed you are correct that will not work. Apologies for my misleading first reply. This query may indeed be a little trickier to write than one might hope. I chatted to @jketema about this, and he suggested that using `StackVariableReachability` might be a good way to reason about the local control flow here.

**Comment by jketema** [comment]
To add: the underlying reason data flow will not work here is that the C++ data flow library uses def-use flow, so there is flow from `*a = NULL` (def) to `assert(a != NULL);` (use) and from `*a = NULL` (def) to `x = *a + 1;` (use), but not from `assert(a != NULL);` (use) to `x = *a + 1;` (use).

**Comment by bdrodes** [comment]
Thanks @jketema , that was my understanding too that it would only follow def/use for the dataflow, but I was hoping there was an advance guard mechanic that would let me be nuanced in a way that included control flow. In fact, I had another similar issue (https://github.com/github/codeql/issues/9885) where I was trying to get more fidelity out of a dataflow traversal, and my guess is what I'm trying to do generally with dataflow might not be possible? 

Specifically, I'd like to be able to say "at a condition, continue along any dataflow through a specific branch or branches". In my particular case, I'd like to say, "if the guard checks if the data being traversed in not NULL, continue through the not NULL path for data flow". If that is possible, then I imagine the assert problem here is also solvable in a similar mechanic, but perhaps what I want isn't possible (yet)?

@edoardopirovano I have been back and forth with using StackVariableReachability. My general concerns are the variable has to be in the stack, so instantly I'm sure I lose fields in objects, but maybe that's not too bad for an initial proof of concept. Additionally, it forces me into a strict control flow traversal. I'm not sure if that will work generally or what the impacts are. 

I did a test with StackVariableReachability and it does seem to be a potential route forward, but it doesn't seem to pick up on sources returning from nested calls. I've also found it can be tricky (but perhaps not impossible) to reason through StackVariableReachability barriers, because if you aren't careful, it will remove entire nodes from the control flow incorrectly leading to massive false negatives. 

The query I'm trying to create is a null dref finder. Our existing finder used StackVariableReachability and seemed to attempt a work around to this problem with nested dataflows in the StackVariableReachability, but still ended up with egregious false postives/negatives. 

My latest solution is to precisely define a NULL source, and a sink as any deref, and just have a dataflow barrier that detects guards. This ALMOST works except for (1) cases like this assert case I raised in this thread and (2) cases where null checks are nested in other conditionals, leading to the guard not dominating the control flow, yet dataflow through those paths should be ignored (this is the kind of use I was getting at in this thread https://github.com/github/codeql/issues/9885). Perhaps StackVariableReachability can get me item 2, but it provides no way to sanitize edges out, only entire nodes. I feel like if I could get the same fidelity in sanitization as a general dataflow it might work. Any suggestion for how to do that?

**Comment by rdmarsh2** [comment]
The issue with using the dataflow library here is that it traverses an extended version of the SSA graph, rather than the CFG, so there isn't a node representing that control flow split explicitly. I don't think there's an easy solution there - the only thing that's been discussed is inserting additional nodes into the SSA graph to create dataflow nodes at these control flow splits, but that's rather involved.

With `StackVariableReachability`, the main issues are that it only has node barriers rather than allowing edge barriers, and that it doesn't handle interprocedural cases. I think the fact that `isBarrier` takes a `Variable` would let you handle that last case properly, unless there's aliasing between `x` and `d`.

In terms of internal things, there was a hackathon project to write a generalized, interprocedural version of the `StackVariableReachability` library. I think that would address both your issues with `StackVariableReachability`, and I've been separately experimenting with using it for use-after-free detection. If that work continues to go well, it may land in the experimental folder at some point in the future. Also, one of the queries written as part of the hackathon was a [Java null dereference query](https://github.com/aschackmull/ql/blob/controlflow/hack/java/ql/src/Likely%20Bugs/Nullness/NullnessPath.ql), and that might be a good reference to see how the library worked (although the API is likely to change to use parameterized modules).

**Comment by bdrodes** [comment]
I think the responses above are enough to resolve my original question for now. Thanks.
