### ISSUE TITLE
LGTM.com - false positive: unused variable introduced in if-clause but used afterwards

### ISSUE THREAD

**Issue by oscargus** [github/codeql#9981]
**Description of the false positive**

The variable is used after the if-clause (lines 124 and 134). This is probably some corner case, the Exception following?, as this typically does not indicate.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/matplotlib/matplotlib/snapshot/408783a6a8773115ab85417d6968f6640de238ca/files/lib/matplotlib/tri/tripcolor.py?sort=name&dir=ASC&mode=heatmap#x68c395a1a7bb0efe:1

**Comment by intrigus-lgtm** [comment]
I'm not 100% sure, but I'd say this is actually a true positive, here's why:
The assignment to `point_colors` in line 73 only ever happens when `if facecolors is not None:` holds in line 68.

The use of `point_colors` in line 124 is guarded by a `if facecolors is not None:` (line 120) check.
If this check is true, an exception is raised meaning that we will not reach line 124 and so the assigned value in line 73 can not be read.

The use of `point_colors` in line 134 is similarly guarded.
But this time, the guard is `if facecolors is None:` (line 132).
But the assignment to `point_colors` only happens when `facecolors` is **not** `None`.
And there is no assignment to `facecolors` between line 73 and 132.
So if we previously performed the assignment in line 73, `facecolors` was **not** `None`, so we will not enter the block guarded by the if in line 132.

Hope this helps.

**Comment by hmakholm** [comment]
Indeed: The only uses of `point_color` I can see after the conditional are in line 124 and 134. But these lines can only be reached if `facecolors` _is_ `None`, which means they are not actually reachable from the line with the alert.

**Comment by oscargus** [comment]
You are correct. Sorry about the fuzz...

**Comment by oscargus** [comment]
The fact that line 95 is actually not required either (as facecolor is set to a non-None value, although that can only be realized by figuring out that C is not None)? Is it worthwhile opening something about that or is that just a too large step to be feasible to check?

**Comment by hmakholm** [comment]
Yeah, deducing that `C` is not `None` is probably a bit of a tall order. The `len(C)` in line 89 would have thrown if it was, but that kind of reasoning is a bit of a rabbit hole to go into. Since we're prioritizing most of our engineering resources for improvements to our security analyses, it is unlikely that an issue requesting such enhancements would receive work priority.
